### ISSUE TITLE
[Taskbar Labels for Windows 11] Centered, fixed size does not have a centered indicator since v1.3

### ISSUE THREAD

**Issue by Tellinq** [ramensoftware/windhawk-mods#1007]
@m417z 

When using `Centered, fixed size`, the active window indicator is shifted towards the right, instead of maintaining the centered position. This seems to have happened since 1.3's introduction. The rest of the indicator styles were also tested and this behavior is not present.

See video for demonstration:

https://github.com/user-attachments/assets/ee32738d-c52a-459b-864b-cf720dbc1639

[Debug logs.txt](https://github.com/user-attachments/files/17176886/wh.logs.txt)

**Comment by Tellinq** [comment]
Way I managed to get around this was specifying the minWidth to be `indicatorElement.Width()`

![image](https://github.com/user-attachments/assets/453e3cba-7259-4d5d-8ad4-141a1f779fe5)

I'm not sure if I would call this a fix, but hey, it works out.

**Comment by m417z** [comment]
Yes, I noticed this as well. Not sure why the fix works, but it's consistent with the other styles, and so far it's less buggy than the previous method which was jumpy with a full taskbar and adaptive width. Fixed in version 1.3.1.
