### ISSUE TITLE
[Vertical Taskbar for Windows 11] Right clicking some notification icons shows menu on different monitor

### ISSUE THREAD

**Issue by rjmana** [ramensoftware/windhawk-mods#1023]
Author: @m417z 

When i right click notification area icons, some of the menus show up on another monitor on the bottom middle. Steam and hwinfo are fine where the menu shows up next to the area clicked. But i use a program called eartrumpet and it goes to a second monitor to the middle and bottom of that screen. Same with the mega app, remove usb device prompt, edit: and epic games launcher, battle.net launcher. Icons in the pop out dock are fine

(i looked through the other issues and didn't see this come up so hopefully it's not a duplicate report)
![secondmonitormenu](https://github.com/user-attachments/assets/8bbd4088-7c76-4b99-b2f4-6b7fff49333a)

**Comment by m417z** [comment]
Fixed in version 1.2.5, hopefully for all programs. Let me know if any programs still have this behavior after the update.

**Comment by rjmana** [comment]
Still have the issue unfortunately, however my monitors are set up in a non-standard way and monitor 1 isn't my main. The attached image shows my layout where monitor 3 is my main screen. (image no 1)

I tested it again by shifting things around and if monitor 1 (bottom right) is my main monitor, right click menus operate as intended.
When monitor 3 is main (bottom left), right click menus show at the bottom of monitor 1. (image no 2)
When monitor 2 is main (top left), right click menus show at the top of monitor 1. (image no 3)

My issue is a probably a niche case so I'm not too worried about it! I appreciate the work you've put into this coz I've wanted my right side taskbar back for so long

![Screenshot 2024-10-04 235017](https://github.com/user-attachments/assets/2a02bfe7-8571-4ac7-bba7-b131bf0def6c)
![Screenshot 2024-10-04 235521](https://github.com/user-attachments/assets/9666203e-9a7c-451d-9e45-bd7af3243752)
![Screenshot 2024-10-04 235443](https://github.com/user-attachments/assets/cec98617-3983-407a-8117-74d8c96ad352)

**Comment by m417z** [comment]
I see that my fix works in the new 24H2 version of Windows 11, but not in 23H2 due to the relevant function being inlined. I'll look for a more universal fix when I have time.

**Comment by rjmana** [comment]
Forced an update to 24H2 and it's working as intended. Thanks for looking into it!!
