### ISSUE TITLE
[Taskbar on Top for Windows 11] Preview builds aren't supported

### ISSUE THREAD

**Issue by AlanWade** [ramensoftware/windhawk-mods#1033]
Unfortunately the preview builds are either not supported or not working. I am using build 26120 but the mod dosnt work, can this be looked at?

Many Thanks

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by AlanWade** [comment]
Debug log as requested attached.
Thanks for checking it.
[DbgViewMini v1.0.1.txt](https://github.com/user-attachments/files/17262697/DbgViewMini.v1.0.1.txt)

**Comment by m417z** [comment]
I see nothing wrong in the logs. Nothing happens when the mod is enabled? If you maximize a window, does it maximize as if the taskbar is on top?

Also, are you using other third-party customization tools such as ExplorerPatcher or StartAllBack? Are you using other mods which might conflict with this one?

**Comment by AlanWade** [comment]
Ahh many appologies Micheal, I was using Start11 and as soon as I disabled it the mod worked as it should.
Thanks for your help and pushing me in the right direction

Alan

Från: Michael Maltsev ***@***.***>
Skickat: den 4 oktober 2024 21:03
Till: ramensoftware/windhawk-mods ***@***.***>
Kopia: AlanWade ***@***.***>; Author ***@***.***>
Ämne: Re: [ramensoftware/windhawk-mods] [Taskbar on Top for Windows 11] Preview builds aren't supported (Issue #1033)


I see nothing wrong in the logs. Nothing happens when the mod is enabled? If you maximize a window, does it maximize as if the taskbar is on top?

Also, are you using other third-party customization tools such as ExplorerPatcher or StartAllBack? Are you using other mods which might conflict with this one?

-

**Comment by m417z** [comment]
Great, I'm glad that it works now.
