### ISSUE TITLE
[Start button always on the left] Widget overlaps Start button

### ISSUE THREAD

**Issue by MuscularPuky** [ramensoftware/windhawk-mods#1036]
![스크린샷 2024-09-25 185525](https://github.com/user-attachments/assets/7bfaaad3-7ee3-4b63-9be1-0f6633b69931)
![스크린샷 2024-09-25 185715](https://github.com/user-attachments/assets/e920fccd-b888-4f55-9917-5021dc070819)

v1.1 has no this problem in main taskbar (because mod loaded slower than main taskbar and faster than secondary taskbar)

![스크린샷 2024-09-25 185543](https://github.com/user-attachments/assets/7450f3c8-81e4-4bf1-aa98-f4275b26a5ea)

but v1.1.1 patch increased mod load spped so now the problem got worse

**Comment by Tellinq** [comment]
This isn’t necessarily limited to widgets. If you have enough taskbar items to fill the entire row, you can overlap the start button that way as well

**Comment by m417z** [comment]
That's because the mod makes the start button act as if it doesn't take space, which is done to keep the rest of the items centered. An alternative is to add margin on the right, but it will be seen more often because of the tray. The best solution here is to figure out how the taskbar layout is implemented and have it stay on the left properly, like the weather widget is fixed on the left. That doesn't look so simple, though.

**Comment by NoCandy** [comment]
But on your picture on the app page you have a screen where you are able to make the widget start after the startmenu. Is that another mod that makes it do that? For me the startbutton and widget overlap.
![Screenshot 2024-11-01 022338](https://github.com/user-attachments/assets/b408a66d-ec19-46af-b009-2da03f72d0fe)
Mods installed : - Start button always on the left
                          - Windows 11 Taskbar Styler
                          
Even if I disable taskbar styler or run it with theme "none" i have the same issue.

**Comment by NoCandy** [comment]
Wow everything was fixed with the latest update and you did it in less than 24h. Thanks a lot truly!
![Screenshot 2024-11-01 191629](https://github.com/user-attachments/assets/8b61f5d3-c19f-42cd-bf10-d569e92bdbe6)

**Comment by m417z** [comment]
> But on your picture on the app page you have a screen where you are able to make the widget start after the startmenu. Is that another mod that makes it do that?

It's an outdated screenshot from an earlier mod version, which had the problem that items weren't truly centered.

Version 1.1.2 was a quick fix to add padding to the weather widget, something that could also be done with [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler).

I gave it some extra thought, and managed to come up with a better implementation which solves both the overlapping issues, and the jumping animation. Try it in version 1.2.
