### ISSUE TITLE
[Taskbar on top for Windows 11] Activation area becomes huge when taskbar is set to auto hide

### ISSUE THREAD

**Issue by berkkrkc09** [ramensoftware/windhawk-mods#1038]
Author: @m417z

Normally when you set the taskbar to auto hide, to show it you move the cursor to the last ~2 pixel layer at the bottom of the screen like this:
![bottom](https://github.com/user-attachments/assets/587c39b9-06f3-4871-8289-8bdf49346180)
                                       (Red line indicates position of cursor)

But with the mod activated the top activation area becomes much larger like this:
![top](https://github.com/user-attachments/assets/3a8d386c-2fac-4542-9cc9-64fb1a5f436d)
                                       (Red line indicates position of cursor)

This problem makes it so user can't interact with the window controls and in this instance it prevents me from using the URL/Search bar.
To prevent this behaviour, top activation area should be re-adjusted in the code or atleast should be changeable from the settings.

**Comment by berkkrkc09** [comment]
Is this being worked on? Were you able to reproduce the issue? I can provide any info you need or at least update the mod description to warn people about this incompatibility.

**Comment by berkkrkc09** [comment]
Just saw this message was added to the mod description: "The option to automatically hide the taskbar isn't supported."
I close this then.

**Comment by m417z** [comment]
It was added to the mod description just to make it clear that it's not supported at this time. It doesn't mean that it will never be implemented. Let's keep the issue open to make it easier to find it and leave additional feedback.

**Comment by CalculonPrime** [comment]
I think I've fixed this.  I also fixed the 2px or so band of background visible above the taskbar (should be no background visible).

I made the constants that determine the trigger area and inset distance just code constants and not user settings because these aren't really knobs a user should be playing with, but I can change this if needed to get it accepted.

[taskbar-on-top.patch](https://github.com/user-attachments/files/23250206/taskbar-on-top.patch) (patch file)
[taskbar-on-top.wh.cpp.txt](https://github.com/user-attachments/files/23250169/taskbar-on-top.wh.cpp.txt) (full mod)

Let me know of any changes suggested.  I have tested it with different window sizes in VMware Windows 11 guests, and toggled autohide mode on and off, but not much else.

**Comment by m417z** [comment]
@CalculonPrime thanks for posting your solution, you're welcome to submit a pull request here:
https://github.com/m417z/my-windhawk-mods

**Comment by ikender** [comment]
Please update if/when this gets implemented. Thanks!

**Comment by TheGamer1445891** [comment]
@m417z is it possible to make the top & vertical taskbar have the auto-hide animations on the future? (and the new auto-hide animations support)

**Comment by strimpa123** [comment]
> [@TheGamer1445891](https://github.com/TheGamer1445891) Currently the vertical taskbar doesn't support auto-hide at all. Taskbar on top got basic support recently, but no animation support. I'm not sure about the new animation, I didn't test with it. Feel free to create a new issue for any of the gaps.

Hello, i see a specific bug on the basic support on the new auto hide with on top taskbar, and i hope it helps. It feels inconsistent when minimizing a window and when the user tries to move the mouse too quickly out of the minimize button making the task bar does not show even when the window is minimized already.

**Comment by strimpa123** [comment]
> > [@TheGamer1445891](https://github.com/TheGamer1445891) Currently the vertical taskbar doesn't support auto-hide at all. Taskbar on top got basic support recently, but no animation support. I'm not sure about the new animation, I didn't test with it. Feel free to create a new issue for any of the gaps.
> 
> Hello, i see a specific bug on the basic support on the new auto hide with on top taskbar, and i hope it helps. It feels inconsistent when minimizing a window and when the user tries to move the mouse too quickly out of the minimize button making the task bar does not show even when the window is minimized already.

here is the video demonstrating it

https://github.com/user-attachments/assets/0c77043b-c0bb-41ce-84f7-31dc3b935cbe
