### ISSUE TITLE
Windhawk Crashes if mod enabled: Taskbar on top for Windows 11

### ISSUE THREAD

**Issue by unCutlass** [ramensoftware/windhawk-mods#1042]
Author: @m417z 

[DbgViewMini v1.0.1.txt](https://github.com/user-attachments/files/17268014/DbgViewMini.v1.0.1.txt)

Windhawk Crashes if mod enabled: Taskbar on top for Windows 11

Other mods enabled; 
* Click on eempty taskbar space
* Cycle taskbar buttons with mouse wheel
* Modernize Folder Picket Dialog
* taskbar height and icon size
* Tasbbar Labels for Windows 11
* Taskbar minimize/restore on scrolll
* Taskbar notification icon spacing
* Windows 11 Notification Center Styler
* Windows 11 Start menu Styler
* Windows 11 Taskbar Styler

--Update-- Taskbar notification icon spacing 
[DbgViewMini v1.0.1(Taskbar notification icon spacing).txt](https://github.com/user-attachments/files/17268294/DbgViewMini.v1.0.1.Taskbar.notification.icon.spacing.txt)

1. Pinpoint to the mod, that makes the app crash - All Mods are enabled
2. However, if i enabled the mods only (For Taskbar on top for Windows 11 & Taskbar notification icon spacing), it does not crash

--Update #2-- Click on empty taskbar space
[DbgViewMini v1.0.1(Click on empty taskbar space).txt](https://github.com/user-attachments/files/17268321/DbgViewMini.v1.0.1.Click.on.empty.taskbar.space.txt
1. Another mod may cause the issue - All mods are enabled
2. If these mods are enabled only (For Taskbar on top for Windows 11 & Taskbar notification icon spacing, Click on empty taskbars space), it does not crash

Note: 
1. Windhawk persistently crashes if all the mods mentioned are enabled, after restarting or from hibernate (if it was already on crash state previously).
2. Windhawk does not crash if you renable the mods as long it didn't crash from its previous state (restart or hibernate)
3. Windhawk does not crash if you configure the mod enabled initially only for (Taskbar on top for Windows 11, Taskbar notification icon spacing, Click on empty taskbar space)

**Comment by m417z** [comment]
You say "Windhawk Crashes", but I assume you mean that explorer crashes?

Did I understand correctly that it only happens after restart or hibernate?

Not sure if I missed it, but does it happen only if all these mods are enabled? Can you find the minimal amount of mods to have to reproduce the crash?

Also, can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by unCutlass** [comment]
> You say "Windhawk Crashes", but I assume you mean that explorer crashes?

Yes 

> Did I understand correctly that it only happens after restart or hibernate?

Yes

> Not sure if I missed it, but does it happen only if all these mods are enabled? 

Yes if all the mods are enabled, the crash only starts

>Can you find the minimal amount of mods to have to reproduce the crash?

Will do,

> Also, can you capture a crash dump? You should be able to get it with the following steps:
> 
> * Open regedit
> * Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
> * Create a key named `LocalDumps`
> * Create a DWORD value named `DumpType` with value `2`
> * Trigger the crash
> * Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

After editing capturing the crash dump, should i revert the changes, ive done?

**Comment by m417z** [comment]
> After editing capturing the crash dump, should i revert the changes, ive done?

Up to you. I like having this enabled. Then, if there's a crash, I have a dump I can look at. Only the last 10 or so dumps are saved so it takes a limited amount of space.

**Comment by valsu** [comment]
Looks like I have the same problem as the OP. Any progress on this issue? I can upload my crash dumps if its helps.

**Comment by m417z** [comment]
@valsu yes, please upload a crash dump. Also note that I published a new version yesterday which fixes a crash, did you try it?

**Comment by valsu** [comment]
@m417z Hi, thanks for the heads-up! I just updated the extension and rebooted. Apparently the update did the trick, everything is working normally again.

**Comment by m417z** [comment]
Great, thanks for confirming. If you see that there are still unsolved crashes, please let me know.
