### ISSUE TITLE
[Taskbar on top for Windows 11] Tray menu items are not clickable

### ISSUE THREAD

**Issue by m417z** [ramensoftware/windhawk-mods#1055]
When taskbar is on the top and I want to "right click" on "WiFi"/"Sound"/"Battery"/"Time and Date" icons, then drop down menu appears, but menu items cannot be clicked with a left mouse. It is only possibly to use arrows on the keyboard to navigate up or down, then press enter to open selected option.

Example in GIF:

![t7kZNBV](https://github.com/user-attachments/assets/9235a160-d2e2-4993-8202-4498d3f48684)

_Originally reported here:
https://www.reddit.com/r/Windows11/comments/1fw2dd8/comment/lqzviev/_

**Comment by Cubody** [comment]
Same with right click on notification center

**Comment by m417z** [comment]
Fixed in version 1.0.2.
