### ISSUE TITLE
When the taskbar is full and Taskbar Labels enabled, i dont have the "see more" dots.

### ISSUE THREAD

**Issue by psorincatalin** [ramensoftware/windhawk-mods#108]
Hello, i noticed when the taskbar is full and Taskbar Labels enabled, i dont have the "see more" dots. 

With mod enable :
![image](https://user-images.githubusercontent.com/23208231/211281750-b0530a6a-e70a-41e0-bdf5-6aed5cd3d9f9.png)

Without mod enable : 
![image](https://user-images.githubusercontent.com/23208231/211281832-ec979726-65f3-4079-8162-60df14e8f0cd.png)

Maybe in "Disable grouping on the taskbar" mod, you can add an option to group if taskbar is full.

Or just fix this issue 

Thank you !

_Originally posted by @IlanZ93 in https://github.com/ramensoftware/windhawk-mods/issues/36#issuecomment-1375356178_

**Comment by m417z** [comment]
Fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version;
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11
