### ISSUE TITLE
[Classic Explorer navigation bar] There is an empty space between the command bar and the address bar

### ISSUE THREAD

**Issue by Klimat13** [ramensoftware/windhawk-mods#1080]
![Explorer](https://github.com/user-attachments/assets/9dcd2a8c-4301-4531-a601-18fcc05a8858)

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by Klimat13** [comment]
[Classic Explorer navigation bar.txt](https://github.com/user-attachments/files/17355946/Classic.Explorer.navigation.bar.txt)

**Comment by m417z** [comment]
I could reproduce it with the `FileExplorerTabLineFix` (51960011) Microsoft flag which Microsoft probably enabled for a small amount of users at this point.

**Comment by m417z** [comment]
Should be fixed in version 1.0.5.

**Comment by Klimat13** [comment]
Is indeed now fixed, thank you =)!
