### ISSUE TITLE
Start button always on the left: windows icon jumps

### ISSUE THREAD

**Issue by Cubody** [ramensoftware/windhawk-mods#1086]
When using [Start button always on the left](https://windhawk.net/mods/taskbar-start-button-position):
If something changes on the taskbar (a new window appears or closes), the windows icon jumps back and forth for a while, it is very annoying, although it does not need to be updated, it is static, there is still a conflict with some of the mods (perhaps [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler)), the task bars are superimposed on the windows icon

**Comment by m417z** [comment]
Yes, that's a known limitation that's mentioned in the mod's description.

> * There's a jumpy animation when a centered taskbar is animated.

**Comment by m417z** [comment]
Fixed in version 1.2.
