### ISSUE TITLE
[Taskbar on top] Missing SHAppBarMessage handling causing compatibility issues

### ISSUE THREAD

**Issue by riverar** [ramensoftware/windhawk-mods#1087]
This Windhawk mod does not appear to be hooking/handling [ABM_GETTASKBARPOS](https://learn.microsoft.com/windows/win32/shell/abm-gettaskbarpos) and other shell messages (via SHAppBarMessage). This results in compatibility issues with software (like [EarTrumpet](https://github.com/File-New-Project/EarTrumpet/discussions/1614)) that query for the position of the taskbar for positioning of its windows and receive "bottom", when it's really at the top/side/etc.

cc: @m417z

**Comment by m417z** [comment]
Done in both Taskbar on top for Windows 11 and Vertical Taskbar for Windows 11.

**Comment by riverar** [comment]
@Cubody Can you re-test EarTrumpet?
