### ISSUE TITLE
(Classic context menu on Windows 11) Win11 Menu in File Explorer Navigation Pane

### ISSUE THREAD

**Issue by SandTechStuff** [ramensoftware/windhawk-mods#1095]
@m417z

When right clicking on any folder in the file explorer navigation pane, the Windows 11 context menu appears instead of the classic one. Everywhere else seems to correctly use the classic context menu.

https://github.com/user-attachments/assets/f929db06-3193-4e8a-88d2-1495f3f0916d

**Comment by m417z** [comment]
Fixed in version 1.0.1.
