### ISSUE TITLE
[Taskbar height and icon size] explorer.exe keeps restarting

### ISSUE THREAD

**Issue by Socrqte** [ramensoftware/windhawk-mods#1104]
Hi,

I just installed Windhawk to replace StartAllBack but I can't get the "Taskbar height and icon size" mod to work. Each time I enable it, my explorer.exe keeps restarting. I tried different options in the settings but nothing seems to work...

I searched in the known issues but I couldn't find anything matching mine. Is it a known issue and is there a known solution? 

Here is the debug log when I enable the mod. Don't know if that can help.

Thanks in advance!
[debug.txt](https://github.com/user-attachments/files/17435868/debug.txt)

**Comment by m417z** [comment]
The file link doesn't work for me. Please try uploading it again, or use an alternative service such as Pastebin.

Also, please capture a crash dump. You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by Socrqte** [comment]
Here's the pastebin : https://pastebin.com/gJqPXj3n

And the crash dump : https://file.io/Md0oRMmTOWYg (the file was too big to be uploaded directly here)

**Comment by m417z** [comment]
Thanks. Looks like you have quite an old build. Version v1.2.14 should fix the crash, please try it and let me know if it helped.
