### ISSUE TITLE
[Taskbar minimize/restore on scroll] Does not work on Win11 24H2 26120.2122 (preview build)

### ISSUE THREAD

**Issue by snowwind621** [ramensoftware/windhawk-mods#1115]
Machine translation
Taskbar miniaturization/restore on scroll does not work on Win11 24H2 26120.2122 version
Is it a preview version issue?
Without this mod, my computer feels very uncomfortable to use
I hope it can be resolved
Thank you.

**Comment by m417z** [comment]
> Is it a preview version issue?

Maybe.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by snowwind621** [comment]
[log.txt](https://github.com/user-attachments/files/17499688/log.txt)

**Comment by m417z** [comment]
I don't see errors in the logs. I'll have to install this build and test it. I'll do that when I have the chance.

**Comment by m417z** [comment]
I believe that it's fixed now in version 1.0.7. Please try it and let me know if it works.
