### ISSUE TITLE
Feature Request: Mod for theming Menu Bar of programs

### ISSUE THREAD

**Issue by WildByDesign** [ramensoftware/windhawk-mods#112]
I am not a programmer. Is it technically possible via a Windhawk mod to apply theming to the menu bar of programs?

The reason why I ask is because I have been a longtime fan of your Win32 Dark Mode for Notepad mod for Windhawk. Recently, I have combined Windhawk and this mod with Mica For Everyone for beautiful results with Classic Win32 Notepad. I hate the new UWP Notepad, so that is why I am trying this combination.

I have created a feature request issue (https://github.com/MicaForEveryone/MicaForEveryone/issues/267) over at the Mica For Everyone repo which has some screenshots that you can see of how far I've gotten. 

In my opinion, the only thing missing is the theming of the Mica or Acrylic to the menu bar of Notepad. As noted in that issue (including screenshots), System Informer (previously Process Hacker) has recently found a method to apply theming to their menu bar and therefore I am able to apply Mica or Acrylic to System Informer menu bar.

Thank you for your time and for your great program.

**Comment by ItsProfessional** [comment]
Instead of using the dark notepad mod, which applies a hardcoded dark mode to the notepad window, use the intended method of applying a dark theme to windows. Note: This will apply the dark theme in all windows, not just notepad.

The intended method of applying a dark style to windows is by using a **visual style**. Microsoft does not officially provide a dark-styled visual style, so you have to resort to third party visual styles that provide a dark mode.

The only well-done and stable visual style (visual styles are also known as *msstyles*) that I know of and would recommend is the visual style that is part of the [rectify11 project](https://github.com/MishaTY/Rectify11Installer).

Visual Styles, because of the way they are implemented, don't have the menubar issues you are mentioning.
Perhaps you would want to look into that that instead of trying to use hardcoded dark-theme windhawk mods.

**Comment by WildByDesign** [comment]
Thank you for your recommendation for Rectify11. I hadn't heard of it before so I just had a look at it. Very impressive. I used to do a lot of Windows modding 10-15 years ago but I've tried to be more simplistic in recent years.

I would prefer to just install the msstyles or at least the smallest amount of modifications from Rectify11 instead of the whole thing.

- If I just extract the dark visual style resources from that project, would it extend to the whole bottom section of Notepad?

- Or would certain system file(s) still need to be patched?

The reason why I ask is because I was looking through some of the code and noticed:
https://github.com/MishaTY/Rectify11Installer/blob/master/Rectify11Installer/Win32/DarkMode.cs

I wasn't sure if the part about `DwmExtendFrameIntoClientArea` is specifically just for adding the Mica effect or if it is also necessary for applying the dark theme to the lower half of Notepad as well.

I appreciate your suggestions and help.

**Comment by ItsProfessional** [comment]
First, install a theme patcher such as SecureUxTheme. Look it up on google, it is open source. Download the themetool.exe file from the releases. and run it as an administrator. click install on the right hand side, and restart your computer.

Then, download [themes.7z](https://github.com/MishaTY/Rectify11Installer/blob/master/Rectify11Installer/Resources/themes.7z?raw=true) from the rectify11 github repository.

Extract the themes.7z file to a folder. You can do this with a program like 7-zip or winrar

In the extracted themes.7z file, there is another "themes" folder. Now, copy the **contents** of themes folder (it should have 3-4 .theme files and a "Rectify11" folder) to:
C:\Windows\Resources\Themes

Open the ThemeTool.exe again, and select the Rectify11 dark theme on the left. and click on "patch and apply"

If everything went right, you should see an amazing dark theme in every win32 program, including notepad.

Oh, and if you want to get the best experience, by using rectify11 visual styles along with micaforeveryone (for the mica effect), use the "rectify11 black" theme in themetool.exe when patching and applying the theme.

the apps will get an pure black mode, but when you enable micaforeveryone, it will have the mica effect and wont show the pitch black mode.

**Comment by WildByDesign** [comment]
I am incredibly pleased with this. Thank you so much for steering me in the right direction here on what I wanted to achieve. Your instructions worked perfectly.

Those dark themes are smooth like butter and easy on the eyes. It exceeded my expectations by a long shot. Cheers!
