### ISSUE TITLE
Windows 11 Taskbar Styler - don't work after relaunch explorer

### ISSUE THREAD

**Issue by ZloyPirozhok** [ramensoftware/windhawk-mods#1133]
Windows 11 Pro 23H2 22631.4317

When you restart explorer the app stroke on taskbar becomes standard for windows 11, the screenshots showed this. 

This does not happen only when restarting explorer, but it always happens if you restart explorer and open it. 

It also happens on any theme that is in windhawk (Tested on Bubbles).
![chrome_4Xl7qrzgnQ](https://github.com/user-attachments/assets/27fe2f49-2b0b-4468-b49c-c8d9d07d146f)
![chrome_7DRohJsjSh](https://github.com/user-attachments/assets/021613ad-f9f9-4a31-a810-dab08a2c20c7)

**Comment by m417z** [comment]
Are you using other customization apps such as TranslucentTB? Some customization tools tools, like the mod, use XAML diagnostics to monitor for taskbar changes, and there can only be one active monitoring process at a time.

**Comment by ZloyPirozhok** [comment]
I apologize for the long reply, I didn't get the notification for some reason.
Yes, I was using ExplorerBlurMica and there along with it comes TranslucentTB. I uninstalled it and that's it, problem gone, thanks a lot!!!!
