### ISSUE TITLE
Classic Explorer navigation bar: white empty space below explorer tab bar

### ISSUE THREAD

**Issue by emp-00** [ramensoftware/windhawk-mods#1136]
@m417z Running on Win11Pro 23H2 22631.4317 - since today there's a huge white and empty space below the explorer tab bar, see screenshot. If I remember correctly, I updated to 1.0.5 yesterday, so this issue might have been introduced by this new revision? I tried disabling, closing all explorer windows and re-enabling the mod: the issue is reproducible.

Thanks for checking.

![image](https://github.com/user-attachments/assets/82709a2b-5c2d-4818-914b-4b4788bce438)

**Comment by m417z** [comment]
Actually 1.0.5 fixed a similar issue: https://github.com/ramensoftware/windhawk-mods/issues/1080.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by emp-00** [comment]
@m417z - thanks for your help. Here comes the log as per instructions. After re-enabling the mod I opened an explorer window (Win-E)) and then got this, hopefully this gives you a lead? The problem as per screenshot still persists.

DbgViewMini v1.0.1
Listening for OutputDebugString messages...
19:39:28.842 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
19:39:28.843 8516 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.22631
19:39:28.843 8516 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.5.1
19:39:28.844 8516 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: explorer-frame-classic
19:39:28.844 8516 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.5
19:39:28.865 8516 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FF9765B0000
19:39:28.865 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
19:39:28.865 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
19:39:28.865 8516 explorer.exe  [WH] [explorer-frame-classic] [737:Wh_ModInit]: >
19:39:28.865 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
19:39:28.867 8516 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: explorerStyle
19:39:28.867 8516 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: explorerStyle
19:39:28.867 8516 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: classicNavigationBar
19:39:28.867 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
19:39:28.867 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
19:39:28.868 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
19:39:28.868 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
19:39:28.868 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Module: 00007FF948CE0000
19:39:28.868 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Path: C:\WINDOWS\SYSTEM32\explorerframe.dll
19:39:28.868 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Version: 10.0.22621.4249
19:39:28.878 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_07A475B82CD59476A3D510DE8438C1451: 1#explorerframe.dll#856803452-2834432#bool __cdecl CanShowModernNavBar(void)#1796068#public: static bool __cdecl CachedExplorerExtensionState::IsModernNavBarAvailable(void)#
19:39:28.878 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
19:39:28.878 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF948E967E4
19:39:28.879 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF9765B1980
19:39:28.879 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
19:39:28.879 8516 explorer.exe  [WH] [LoadedMod::HookSymbols::<lambda_1>::operator ()]: Hooked 00007FF948E967E4: bool __cdecl CanShowModernNavBar(void)
19:39:28.879 8516 explorer.exe  [WH] [LoadedMod::HookSymbols::<lambda_2>::operator ()]: Optional symbol 1 doesn't exist (from cache)
19:39:28.880 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
19:39:28.880 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
19:39:28.880 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Module: 00007FF946510000
19:39:28.880 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Path: C:\WINDOWS\system32\Windows.UI.FileExplorer.dll
19:39:28.880 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Version: 10.0.22621.4249
19:39:28.880 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_BD3EA9CA3363C571A35FF2DC001279251: 1#windows.ui.fileexplorer.dll#2978174319-1409024#private: int __cdecl XamlIslandViewAdapter::GetScaledXamlIslandLogicalHeight(void)#
19:39:28.881 8516 explorer.exe  [WH] [LoadedMod::HookSymbols::<lambda_2>::operator ()]: Optional symbol 0 doesn't exist (from cache)
19:39:28.881 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
19:39:28.881 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
19:39:28.882 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Module: 00007FF91D450000
19:39:28.882 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Path: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.FileExp_cw5n1h2txyewy\FileExplorerExtensions.dll
19:39:28.882 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Version: 2124.22809.20.0
19:39:28.882 8516 explorer.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_AD5C786935AC4A598D392FCFA4D000971: 1#fileexplorerextensions.dll#1724195720-3686400#public: void __cdecl winrt::FileExplorerExtensions::implementation::NavigationBarControl::OnApplyTemplate(void)#1818284#public: virtual int __cdecl winrt::impl::produce<struct winrt::FileExplorerExtensions::factory_implementation::CommandBarExtension,struct winrt::WindowsUdk::UI::Shell::IFileExplorerCommandBarExtensionStatics>::GetHeight(struct winrt::Windows::Foundation::Size,struct winrt::Windows::Foundation::Size *)#719424
19:39:28.883 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
19:39:28.883 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF91D60BEAC
19:39:28.883 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF9765B1840
19:39:28.884 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
19:39:28.884 8516 explorer.exe  [WH] [LoadedMod::HookSymbols::<lambda_1>::operator ()]: Hooked 00007FF91D60BEAC: public: void __cdecl winrt::FileExplorerExtensions::implementation::NavigationBarControl::OnApplyTemplate(void)
19:39:28.884 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
19:39:28.884 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF91D4FFA40
19:39:28.884 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF9765B18A0
19:39:28.884 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
19:39:28.884 8516 explorer.exe  [WH] [LoadedMod::HookSymbols::<lambda_1>::operator ()]: Hooked 00007FF91D4FFA40: public: virtual int __cdecl winrt::impl::produce<struct winrt::FileExplorerExtensions::factory_implementation::CommandBarExtension,struct winrt::WindowsUdk::UI::Shell::IFileExplorerCommandBarExtensionStatics>::GetHeight(struct winrt::Windows::Foundation::Size,struct winrt::Windows::Foundation::Size *)
19:39:28.886 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
19:39:28.886 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
19:39:28.887 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF97C6DFC70
19:39:28.887 8516 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF9765B1A20
19:39:28.887 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
19:39:28.887 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
19:39:28.898 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::AfterInit
19:39:28.898 8516 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::AfterInit
19:39:42.416 8516 explorer.exe  [WH] [explorer-frame-classic] [599:CanShowModernNavBar_Hook]: >
19:39:42.987 8516 explorer.exe  [WH] [explorer-frame-classic] [565:Feature_NavigationBarControl_OnApplyTemplate_Hook]: >

**Comment by m417z** [comment]
Thanks, fixed in version 1.0.6.
