### ISSUE TITLE
[Taskbar auto-hide when maximized] Taskbar delay to hide

### ISSUE THREAD

**Issue by Undisputed00x** [ramensoftware/windhawk-mods#1158]
Like the title says the mod delays to hide the taskbar when a windows gets maximized resulting in a weird resizing animation of that window. Disabling animations in the taskbar through "System properties > Advanced system settings > Performance settings" doesn't make it any better

<details>
<summary>

 ### Example of problem
</summary>
<p>

https://github.com/user-attachments/assets/361ccb53-ac03-4740-801e-c2488d334328

</p>
</details> 

<details>
<summary>

 ### Example of a "fix"
</summary>
<p>

https://github.com/user-attachments/assets/593abdba-9cdd-4610-8b18-5ffb8fef9136

</p>
</details>

**Comment by m417z** [comment]
Fixed in version 1.1.
