### ISSUE TITLE
Taskbar labels mod: Window appears open on taskbar even after closing

### ISSUE THREAD

**Issue by Biosphakus** [ramensoftware/windhawk-mods#1173]
After the new Windows Update (2024H2), I'm experencing a bug with the Taskbar labels mod for Windhawk.

My normal setup looks like this:
![grafik](https://github.com/user-attachments/assets/308d5f5f-5c4d-4961-9f35-844a6dd65aba)

But now, when I close a window, it sometimes remains underlined (without text):
![grafik](https://github.com/user-attachments/assets/45ffab2a-9a76-45a3-a27e-eec18c248cc2)

Strangely, this behaviour doesn't always happen and sometimes it can be fixed by re-opening the closed app and closing it again.

**Comment by m417z** [comment]
Try to come up with a way to reproduce the issue. Also, I see that you have other customizations in place, possibly [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) styles. Does the issue happen without them?

**Comment by Biosphakus** [comment]
Thanks for your reply! As far as I'm aware, the Taskbar labels mod is the only mod I'm using.

These are my settings:
`{"taskbarItemWidth":150,"minimumTaskbarItemWidth":50,"maximumTaskbarItemWidth":150,"runningIndicatorStyle":"fullWidth","progressIndicatorStyle":"sameAsRunningIndicatorStyle","fontSize":11,"leftAndRightPaddingSize":8,"spaceBetweenIconAndLabel":8,"labelForSingleItem":"%name%","labelForMultipleItems":"[%amount%] %name%","mode":"labelsWithoutCombining","excludedPrograms[0]":"excluded1.exe"}`

I hope this can help to reproduce and fix the issue.

**Comment by m417z** [comment]
I tried playing with your settings and pinned items, but wasn't able to reproduce it.

> As far as I'm aware, the Taskbar labels mod is the only mod I'm using.

Are you sure? On the screenshot, your Explorer taskbar button doesn't have round corners, which is not how the taskbar looks by default:

![image](https://github.com/user-attachments/assets/63580ece-4c0c-4daa-a462-0a49321efb2f)

**Comment by Biosphakus** [comment]
I've checked again: No other mods in Windhawk. 
![grafik](https://github.com/user-attachments/assets/30b76587-50b1-4e62-9225-0578c46ac5d0)

And I do have rounded corners. Apparently, it looks like this because of how the picture was clipped, I'm sorry for the confusion. Here's a full view of my task bar:

![grafik](https://github.com/user-attachments/assets/7738c08c-9d2f-485f-aad7-10b619045a09)

Unfortunately, the issue persists. Could it have to do something with the taskbar settings I've made within Windows? I have a left-aligned task bar layout and no clock on the right side. Would it be helpful to provide any logs?

**Comment by m417z** [comment]
I looked at the code again, and I found a possible reason for this. Please try this version and let me know if it helps:
https://github.com/m417z/my-windhawk-mods/blob/fb35490002b7f03117e63ce1372c50f7d5bed0b3/mods/taskbar-labels.wh.cpp

To try it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the test mod code, click "Compile Mod", then "Exit Editing Mode".

**Comment by Biosphakus** [comment]
Thanks a lot for your effort! This doesn't seem to have fixed it, unfortunately. For a while, the problem didn't occur but now it's back, unfortunately.

**Comment by m417z** [comment]
In this case, let's try some debug logs. Replace your test version with this one:
https://github.com/m417z/my-windhawk-mods/blob/a5d7a4171dae9b7fbbd874d429c4f1cc7271b8ae/mods/taskbar-labels.wh.cpp
Make sure the original Taskbar Labels mod is still disabled, open the test mod, click on Edit, replace the code with the new version, click "Compile Mod", then "Exit Editing Mode".

After that, collect debug logs as following:

* Go to the test mod, enable it, then go to the Advanced tab.
* Set **Debug logging** to **Detailed debug logs**.
* Click on **Show log output**.
* Reproduce the problem, copy the log and post it here. Also specify which app you used for the reproduction, and post a screenshot (or even better, a video recording).
* Set **Debug logging** back to **None**.

**Comment by Biosphakus** [comment]
I'm still on it! The problem persists but it's a bit hard to reproduce when I try to (since it doesn't happen all the time... but when it does, it's quite persistent). I'll let you know once I have a log and recording showing the problem.

**Comment by m417z** [comment]
I stumbled upon [this Reddit thread](https://www.reddit.com/r/Windows11/comments/1gv19a4/what_are_these_grey_bars_under_my_program_icons/) which indicates that it's a Windows issue that's unrelated to Windhawk:

> This is a bug I started seeing during a preview of 24H2 in July-August. It's still here in the latest stable public 24H2 release. It's on feedback hub yet it hasn't been fixed for 4 months.
