### ISSUE TITLE
(Better file sizes in Explorer details) Show folder size without having to open properties

### ISSUE THREAD

**Issue by SandTechStuff** [ramensoftware/windhawk-mods#1175]
@m417z

What a mod to randomly drop, this is really cool. Would it be possible to also show folder sizes in details? Folder sizes are not shown in details normally, which means you have to make an extra click or two to view the size in properties.

![folderNoSize](https://github.com/user-attachments/assets/e6181fd8-6b94-4e81-8d5f-391f88a20a4e)
_No size in details_

![properties](https://github.com/user-attachments/assets/416d04f6-8aee-4001-92f6-db8b514db85c)
_The size in properties_

**Comment by Alienmoon** [comment]
> @m417z
> 
> What a mod to randomly drop, this is really cool. Would it be possible to also show folder sizes in details? Folder sizes are not shown in details normally, which means you have to make an extra click or two to view the size in properties.
> 
> ![folderNoSize](https://private-user-images.githubusercontent.com/164842290/381364967-e6181fd8-6b94-4e81-8d5f-391f88a20a4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDg5NDAsIm5iZiI6MTczMDMwODY0MCwicGF0aCI6Ii8xNjQ4NDIyOTAvMzgxMzY0OTY3LWU2MTgxZmQ4LTZiOTQtNGU4MS04ZDVmLTM5MWY4OGEyMGE0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNzE3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZThiZjZjN2QzNjMyZjJjYTllNTY2NWMwOThhZDVhMDlhMTYwNzBhZjZlNGEyNjljYmFlM2QxZGU3MmFkMGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kFJv8cEA7wFyHgNp4Xc8e7geCJXmwVSclpKfl4HzVI8) _No size in details_> 

That would be an awesome and really useful Mod to have +1

**Comment by m417z** [comment]
Yeah, it was inspired by a spontaneous suggestion in the Discord channel yesterday. Showing sizes of folders would be cool, too. I spent some time trying to come up with something, hoping that I could use the functionality that shows folder sizes on hover, but couldn't find a way so far.

**Comment by m417z** [comment]
I managed to come up with an implementation, check out version 1.1.

**Comment by SandTechStuff** [comment]
Nice work. Good call on the shift key option, didn't realize showing folder sizes would be noticeably slower, though it does make sense. It essentially has to go through every file inside the folder and add up the sizes right?

**Comment by m417z** [comment]
> It essentially has to go through every file inside the folder and add up the sizes right?

Yes, that's also what happens when you hover over a folder, just with a timeout - at some point it gives up, in which case no size is shown.

But it actually isn't as slow as I thought. It's quite bad in C:\Windows, for example, but not in many other folders with a saner amount of files.

**Comment by m417z** [comment]
Version 1.2 adds an option for getting folder sizes via "Everything" integration, which results in immediate folder sizes without having to calculate them manually.
