### ISSUE TITLE
Taskbar tray icon spacing - Overflow area shifted up ...

### ISSUE THREAD

**Issue by Marshall-Brooks** [ramensoftware/windhawk-mods#1179]
@m417z 

I don't think this was happening last week:
![image](https://github.com/user-attachments/assets/1c332afc-3d30-4958-9c44-81d8c28772de)

I normally have 15 to 16 overflow icons and I use the mod to show them in 2 rows of 8 each, instead of three or four rows of 5.

It looks like recently the mod is showing them at the top of the previous overflow area, instead of the bottom right above the taskbar.

After further research, it seems to be intermittent (it is not doing it now for me), and I don't know how to reproduce it.

**Comment by m417z** [comment]
Could it be related to Windows 11 Taskbar Styler styles? Can you disable the mod (and other potentially conflicting mods) and check whether the issue still happens?

**Comment by Marshall-Brooks** [comment]
It is hard to track down.

I thought it was a memory glitch and was not happening anymore, but I was going to check that for you and it was too high again.

I opened Windhawk to disable Taskbar styler, but when I opened WH (without disabling any mods), it started working properly again.

Maybe it's a coincidence, but I had 16 overflow systray icons above and I thought I had that with the issue now, and after opening WH, I had 17 (There's an Outlook icon in addition to the ones shown), so maybe with multiples of the number of rows, but I dragged Outlook from the systray overflow to the systray main and it still worked properly.

Short answer - it USUALLY works properly, but sometimes it does not, but I can't discern a pattern for it.

**Comment by m417z** [comment]
I looked in more details into this issue. From what I see, it only happens on the first the overflow popup is shown after explorer.exe is launched, and so it can be reproduced by restarting explorer.
Here's a version with several improvements, please give it a go and let me know if it fixes the bug for you:
https://github.com/m417z/my-windhawk-mods/blob/e62157940864d24def530135e9c307936bb16ae6/mods/taskbar-notification-icon-spacing.wh.cpp

**Comment by Marshall-Brooks** [comment]
Michael,

Thanks for looking into this.

I did very limited testing, but the new modified code seems to have fixed the issue.

I copied and compiled and installed the new modification code and restarted Explorer and didn't see the issue. Closed and re-started Windhawk and didn't see the issue, and re-booted the PC and didn't see the issue. The icons seem to be all on one row right above the taskbar like I would expect them to be shown.

I appreciate you looking into this. It was a minor annoyance, but I'm glad it is fixed now!

Have a Merry Christmas and a great New Year!!!

Marshall Brooks
From: Michael Maltsev ***@***.***>
Sent: Thursday, December 12, 2024 5:39 PM
To: ramensoftware/windhawk-mods ***@***.***>
Cc: Brooks, Marshall (US) ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [ramensoftware/windhawk-mods] Taskbar tray icon spacing - Overflow area shifted up ... (Issue #1179)


I looked in more details into this issue. From what I see, it only happens on the first the overflow popup is shown after explorer.exe is launched, and so it can be reproduced by restarting explorer.
Here's a version with several improvements, please give it a go and let me know if it fixes the bug for you:
https://github.com/m417z/my-windhawk-mods/blob/e62157940864d24def530135e9c307936bb16ae6/mods/taskbar-notification-icon-spacing.wh.cpp

**Comment by m417z** [comment]
Thanks for confirming, fixed in version 1.1.1. Merry Christmas!

**Comment by Marshall-Brooks** [comment]
Hi Michael,

Just wanted to let you know, apparently Tray Icon Spacing 1.1.1. also fixed some of the issues I was having with TB Styler needing to be restarted multiple times to hide unwanted systray icons.  I eliminated those lines from my startup routine and WH seems to be running fine.

Thank you again and Merry Christmas again!!!


Marshall Brooks

From: Michael Maltsev ***@***.***>
Sent: Monday, December 16, 2024 5:19 PM
To: ramensoftware/windhawk-mods ***@***.***>
Cc: Brooks, Marshall (US) ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [ramensoftware/windhawk-mods] Taskbar tray icon spacing - Overflow area shifted up ... (Issue #1179)


Thanks for confirming, fixed in version 1.1.1. Merry Christmas!
