### ISSUE TITLE
[Vertical Taskbar for Windows 11] Systray icons in multiple columns

### ISSUE THREAD

**Issue by nicolafarina** [ramensoftware/windhawk-mods#1191]
Hi there,

can be considered adding multi columns support for systray icons when vertical taskbar is in use? It is what Windows 10 default taskbar does when moved on sides (and the same for StartAllBack, f.e.).

This would be really great!

Thanks

**Comment by m417z** [comment]
Thanks for the suggestion. There's already an issue about it: https://github.com/ramensoftware/windhawk-mods/issues/1068, closing as a duplicate.
