### ISSUE TITLE
Open pinned items with double click

### ISSUE THREAD

**Issue by mantheakis** [ramensoftware/windhawk-mods#1199]
I am running Windows 11 Pro version 24H2 on a desktop system.

Also installed on my system is StartAllBack 3.8.12 and Windhawk 1.5.1. 

StartAllBack is only used to customise the Taskbar with small icons, tightly spaced and never combined with no labels - all the other features are ignored/disabled.

The only Windhawk mod that I have loaded is "Open pinned items with double click" but it does not work. I can still run applications pinned to the Taskbar with a single-click. (I desperately want to disable single-clicks and enable double-clicks - a long-time habit enabled by 7+ Taskbar Tweaker with earlier versions of Windows 10 and 11.)

Attached is the detailed debug log output for the "Open pinned items with double click" mod.

I would be really grateful if @m417z could fix this - and thank you for all your work!

[Windhawk-Log-Open pinned items with double click.txt](https://github.com/user-attachments/files/17623991/Windhawk-Log-Open.pinned.items.with.double.click.txt)

**Comment by m417z** [comment]
From version 3.8, StartAllBack uses its own taskbar, and most Windhawk mods don't work with it.

Currently, you can either stop using StartAllBack, stick to an older version of StartAllBack before 3.8, or give up on the Windhawk mods that aren't compatible.

**Comment by mantheakis** [comment]
So, apologies - I disabled StartAllBack and the "Open pinned items with double click" mod works after restating.

Looks like I have to choose between the two :)

**Comment by mantheakis** [comment]
Wow - I uninstalled StartAllBack and switched to Windhawk mods - it has everything I need, and lots more!
