### ISSUE TITLE
Taskbar Clock Customization - Add ability to add different web field for tooltip

### ISSUE THREAD

**Issue by superluig164** [ramensoftware/windhawk-mods#121]
For example, I could add the summary from an RSS feed as a field in the tooltip.  My use case, I live in Canada.  They have RSS feeds for all areas, and each includes a title and summary.  Title would be a quick forecast or storm warning, summary would be a longer version with more info, and I'd love to be able to see that in the tooltip.

**Comment by m417z** [comment]
Added in Taskbar Clock Customization v1.2.
