### ISSUE TITLE
Better file sizes in Explorer details

### ISSUE THREAD

**Issue by mirt81** [ramensoftware/windhawk-mods#1222]
Copy Folders with Detailed Infos open show verry wrong Foldersize . . . 

Th@nks !

**Comment by m417z** [comment]
Please post more details and a screenshot. What do you mean by "Copy Folders with Detailed Infos"? What do you mean by "verry wrong Foldersize"?

**Comment by mirt81** [comment]
![Screenshot 2024-11-09 150415](https://github.com/user-attachments/assets/f28dd9bb-ab69-401d-9551-0afd86ae1d3d)

This is also when empty Recycle . . . sorry English not my main Speeching .

**Comment by mirt81** [comment]
This is Only when Copy Folders single or muliple Files are Shown correct ! ?

**Comment by mirt81** [comment]
[Log.txt](https://github.com/user-attachments/files/17687984/Log.txt)

**Comment by mirt81** [comment]
If toggeling the "Use MB/GB for large files" turned on or of there is differnce for wrong shown Size . . . one shows much more size and other less much more wrong size.

Whish a good Time !

**Comment by m417z** [comment]
Thanks, from my tests it's not related to "Use MB/GB for large files", only to "Show folder sizes". Fixed in version 1.5.2, please try it and confirm that the issue is fixed.

**Comment by mirt81** [comment]
IT´s fixed . . . really Speeedy with "Everything" now !
