### ISSUE TITLE
Taskbar Volume Control / Tray System Icon Tweaks - Open Volume Mixer Directly

### ISSUE THREAD

**Issue by JFMugen** [ramensoftware/windhawk-mods#1227]
Hey there, firstly thanks for the awesome app. One thing that constantly annoys me is how hard to open volume mixer compared to EarTrumpet for example. Right now it needs 3 steps

1- Click on Wifi/Sound sign

![SS241110140004](https://github.com/user-attachments/assets/e76ea771-fde3-4296-8283-f2db34deb0e2)

2- Click on Volume Mixer button

![SS241110140019](https://github.com/user-attachments/assets/853c8feb-e81b-47b7-bad7-333c57a46c0b)

3- Scroll down until you finally see programs

![SS241110140030](https://github.com/user-attachments/assets/55e26aed-bd45-4c15-bd15-b70645ef2c8a)

I was thinking, maybe we can bypass first 2 steps with an (or 2) option? What needs to be done is 

1- Wifi/Sound button will open Volume Mixer directly

2- Hide "Output Device" and "Spatial Sound" parts so you can directly see the list. I personally never use them, but that might be me.

Second one would be nice, but first one is the most important one here. 

What do you think? It looks like a good fit for both mods, but probably more suited for "Tray System Icon Tweaks". Hopefully I managed to explain it well :) 

_*tag the mod's author using their GitHub handle ->_ @m417z

**Comment by Wolverine1977** [comment]
Taskbar Volume Control - Great Mod, is there a way to increase the size of the displayed volume indicator. i.e. % increase the OSD for use on 4K monitors to make it easier to see. Thanks :)

**Comment by m417z** [comment]
@Wolverine1977 currently there's no such option. If you'd like to see it, please create a new issue instead of commenting in an unrelated issue, thanks.

**Comment by m417z** [comment]
Here are a couple of tips to make it easier:

> 1- Click on Wifi/Sound sign

You can use Win+A.

> 2- Click on Volume Mixer button

With [Windows 11 Notification Center Styler](https://windhawk.net/mods/windows-11-notification-center-styler), you can define a keyboard shortcut for it. For example, the following will allow triggering the button with Alt+A:

Target:
```
Button#VolumeL2Button
```
Style:
```
AccessKey=a
```

> 3- Scroll down until you finally see programs

You can hide the other elements with Windows 11 Notification Center Styler with the following styles:

### Output device

Target:
```
ContentPresenter#PageContent > Grid > ScrollViewer#ListContent > Border#Root > Grid > ScrollContentPresenter > ItemsControl > ItemsPresenter > StackPanel > ContentPresenter[1]
```
Style:
```
Visibility=Collapsed
```

### Spatial sound

Target:
```
ContentPresenter#PageContent > Grid > ScrollViewer#ListContent > Border#Root > Grid > ScrollContentPresenter > ItemsControl > ItemsPresenter > StackPanel > ContentPresenter[2]
```
Style:
```
Visibility=Collapsed
```

These steps don't offer a perfect solution, but that's probably the best that can be achieved with existing mods.

**Comment by JFMugen** [comment]
@m417z Styles were very helpful, appreciate it :) 

This is totally out of topic but just trying my chance, is it possible to hide this as well? It just annoys me a bit visually, so I would like to hide if possible. 

![image](https://github.com/user-attachments/assets/dab2b908-e068-4ccd-9b12-1e2ea9a9d861)

**Comment by m417z** [comment]
You should be able to find this, and any other target with UWPSpy. Here's a guide to get started:
https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md

Let me know if you need help with one of the steps.

**Comment by JFMugen** [comment]
@m417z previous time I tried I couldn't make it work some reason but this time I did

Looks like its > Windows.UI.Xaml.Controls.Grid#FooterGrid

**Comment by vos6434** [comment]
You could also just hide the windows audio icon and use ear trumpet as a full on replacement
![image](https://github.com/user-attachments/assets/d2d32baf-486f-4d24-8213-9019a2ee2050)

**Comment by JFMugen** [comment]
@vos6434 I used to but it was somewhat inconsistent, like sometimes it didn't register until I click on taskbar etc.

**Comment by m417z** [comment]
> > 1- Click on Wifi/Sound sign
> 
> You can use Win+A.
> 
> > 2- Click on Volume Mixer button
> 
> [...] the following will allow triggering the button with Alt+A:
> [...]

Turns out there's the Ctrl+Win+V keyboard shortcut to open the volume mixer right away.

You can also also use the [Click on empty taskbar space](https://windhawk.net/mods/taskbar-empty-space-clicks) mod to trigger the keyboard shortcut on empty space double/middle click.

**Comment by JFMugen** [comment]
@m417z Yeah I am aware of both, but with the styler codes you give earlier really helped, and it doesn't feel as annoying anymore. 

Btw "click on empty taskbar space" is really damn helpful, I am using it for something else.
