### ISSUE TITLE
Some mods not working with "Customize the old taskbar on Windows 11" enabled (StartAllBack)

### ISSUE THREAD

**Issue by Liberato116** [ramensoftware/windhawk-mods#1228]
Activating the old taskbar option on mods has no effect on them working or not while using the "Enhanced classic taskbar" from StartAllBack. Tested with "Middle click to close on the taskbar" and "Taskbar Clock Customization" mods (logs attached).
[MiddleClickLog.txt](https://github.com/user-attachments/files/17689937/MiddleClickLog.txt)
[ClockCustomizationLog.txt](https://github.com/user-attachments/files/17689947/ClockCustomizationLog.txt)

**Comment by m417z** [comment]
From version 3.8, StartAllBack uses its own taskbar, and most Windhawk mods don't work with it.

Currently, you can either stop using StartAllBack, stick to an older version of StartAllBack before 3.8, or give up on the Windhawk mods that aren't compatible.
