### ISSUE TITLE
"Pinned" label missing on live SideBySide2 - Windows 11 Start Menu Styler v1.1.6

### ISSUE THREAD

**Issue by deantumabcao** [ramensoftware/windhawk-mods#1234]
I reported this bug on the W11 Start Menu Styling Guide repo but only the manual installation code was fixed. Live v1.1.6 still has this bug.

Resolved Issue: https://github.com/ramensoftware/windows-11-start-menu-styling-guide/issues/103

Live v1.1.6 SideBySide2:
<img width="551" alt="image" src="https://github.com/user-attachments/assets/4dca597c-9a3d-4f44-8890-4858d3cf7626">

**Comment by m417z** [comment]
Fixed in v1.2.
