### ISSUE TITLE
[Taskbar Clock Customizer] Add a way to make double line clock possible

### ISSUE THREAD

**Issue by ardashir77** [ramensoftware/windhawk-mods#1251]
Tagging as requested: @m417z 

Basically what I said in the title; maybe add $hours and $minutes as separate patterns to allow for them to be added separately. My idea is to have a vertical bar that somehow resembles this classic eww bar from Linux: 

![image](https://github.com/user-attachments/assets/7c18fb42-5778-4b04-bc54-c26ef3ffa03a)

**Comment by m417z** [comment]
Added in version 1.4.

![image](https://github.com/user-attachments/assets/3966b6c7-b1b0-4bb6-9bfd-2809896fc905)
