### ISSUE TITLE
Windows Explorer - Turn new windows to tabs

### ISSUE THREAD

**Issue by JFMugen** [ramensoftware/windhawk-mods#1257]
I think the title is self-explanatory, instead of opening a new window when we click a folder, it will create a new tab instead. 

Looks like there is an external program for this but since it kinda hacks by closing the window first and opening the tab later which looks very clunky, it's not usable in my eyes -> https://github.com/w4po/ExplorerTabUtility

**Comment by LEveLiQ** [comment]
this feature is on the latest beta build, 22635.4515. to enable it you need vivetool:
```
vivetool /enable /id:49143212
```

**Comment by JFMugen** [comment]
@LEveLiQ Thanks for letting me know but I will wait for stable, I am not using insider

**Comment by LEveLiQ** [comment]
> @LEveLiQ Thanks for letting me know but I will wait for stable, I am not using insider

what I'm saying is since it is going to be an official feature, a mod is not going to be necessary in my opinion.
