### ISSUE TITLE
Windows 11 Taskbar Styler - request better accomodation of 3rd party clocks

### ISSUE THREAD

**Issue by explor202** [ramensoftware/windhawk-mods#1258]
@m417z I love your Taskbar Styler mod, but T-Clock Redux doesn't work (at all) with it. I tried Eleven Clock, but it doesn't skin correctly for me. Is there any way to incorporate better handling of 3rd party clocks like T-Clock? I really prefer to see just the time in standard format, and T-Clock handled that perfectly until I added your mod.

**Comment by SeijiSuenaga** [comment]
Just a suggestion if you're using Windows 11 and you just want to see the time in standard format: the Taskbar Clock Customization mod in Windshark might be able to do what you want.  Specifically, you can configure your desired time format in "Bottom line", then scroll down to the "Top line style (Windows 11 version 22H2 and newer)" section and turn off the "Visible" switch.

**Comment by explor202** [comment]
@SeijiSuenaga thanks for the suggestion, but the issue is that these clock mods don't seem to work with the taskbar styler mod. I can install and configure them, but they never replace the built in clock of the styler.

**Comment by explor202** [comment]
Did some more checking, it appears my issue is firewall related.
