### ISSUE TITLE
Chrome/Edge scroll tabs with mouse wheel-scrolling in the four edges

### ISSUE THREAD

**Issue by NailaoFF** [ramensoftware/windhawk-mods#1259]
especially in right. When I use the scroll bar, I accidentally trigger tab scrolling.
![38eb30b4-d158-419e-be27-c11237e3c3dd](https://github.com/user-attachments/assets/2acadd78-c278-4f65-b969-6ec4133bb72a)

**Comment by m417z** [comment]
Seems to be specific to Edge since they have that extra margin around the web contents, unlike other Chromium-based browsers such as Chrome or Brave.

**Comment by m417z** [comment]
Fixed in version 1.1.
