### ISSUE TITLE
Taskbar Clock Customization - allow for vertical adjustment of time if middle and bottom lines are blank

### ISSUE THREAD

**Issue by explor202** [ramensoftware/windhawk-mods#1260]
@m417z if a user doesn't configure the middle and bottom lines (I don't need to see the date and headlines), can an option to adjust the time be added so it can be centered in the taskbar? There are options for left, center and right alignment, but that doesn't allow for vertical adjustment, only horizontal. When the other lines aren't used, the time is displayed higher than other data so it's out of alignment. 

![image](https://github.com/user-attachments/assets/a2bfc7c6-15b0-4ff3-a8aa-0c5af4676dd6)

**Comment by m417z** [comment]
There's an option to hide the top line, then you'll have only the bottom line left, vertically-aligned.

![image](https://github.com/user-attachments/assets/edfec433-372f-4725-b3b2-271b3efdd21d)

**Comment by explor202** [comment]
Thank you!
