### ISSUE TITLE
[Windows 11 Taskbar Styler] Incompatible with other tools which use XAML diagnostics, such as ExplorerBlurMica or TranslucentTB 

### ISSUE THREAD

**Issue by grandrange** [ramensoftware/windhawk-mods#1262]
Hello! I use ExplorerBlurMica and Windhawk. The "Windows 11 Taskbar Styler" modification has the ability to hide the RunningIndicator, but this modification is not compatible with ExplorerBlurMica. Everything works, but after restarting the computer, you have to restart the modification.

This topic talked about it:
https://github.com/ramensoftware/windhawk-mods/issues/1133

I don't really want to give up ExplorerBlurMica because it fixes a lot of problems, such as explorer flashes on dark theme, visual design, and so on. Please tell me if it is possible to hide RunningIndicator without deleting ExplorerBlurMica. I don't use other Taskbar Styler options, maybe this hiding can be used separately somehow?

**Comment by m417z** [comment]
That's a known limitation - Multiple tools/mods that use XAML diagnostics conflict with each other. It's a Microsoft API that's barely documented, and I don't know whether there's a solution to have multiple XAML diagnostics consumers.

> I don't use other Taskbar Styler options, maybe this hiding can be used separately somehow?

It can be done with a dedicated mod, but it'd require some effort to implement it. If you'd like to try it, you can take taskbar-labels and add code that hides it around here:
https://github.com/ramensoftware/windhawk-mods/blob/799488e7933b684caa77565ce1df5698833139ac/mods/taskbar-labels.wh.cpp#L1015-L1017

For example, try adding this after these three lines (untested):
```cpp
indicatorElement.Visibility(Visibility::Collapsed);
continue;
```

**Comment by grandrange** [comment]
> For example, try adding this after these three lines (untested)

It works, thank you again! And thanks for your mods, they are great!
