### ISSUE TITLE
Windows 11 Taskbar Styler does not work

### ISSUE THREAD

**Issue by corpse01mdl** [ramensoftware/windhawk-mods#1270]
[log.txt](https://github.com/user-attachments/files/17878433/log.txt)

Not really sure what is going on. If someone could help, please.

**Comment by m417z** [comment]
I don't see initialization in the logs. Perhaps you're using the Win10 taskbar, or a third-party implementation such as ExplorerPatcher or StartAllBack? Can you post a screenshot of your taskbar?

**Comment by corpse01mdl** [comment]
Oh, thank you for such a prompt reply @m417z! I was actually using the Win10 taskbar, indeed 🤦

Do you know if there is any alternatives for this mod, but for Win10? I would really like to have the WinXP taskbar...

**Comment by m417z** [comment]
Check out https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/105.
