### ISSUE TITLE
[Taskbar Clock Customization] Oh no abbreviated clock & time reverted #52 in Bulid 27754 X(

### ISSUE THREAD

**Issue by MuscularPuky** [ramensoftware/windhawk-mods#1274]
#52 `ddd` always displayed at first, %web_full% gone
disabling abbreviated clock & time doesn't affect at flyout

**Comment by m417z** [comment]
I'm working on a new version with compatibility fixes to the abbreviation changes. Please try this version and let me know if you still see any issues:
https://github.com/m417z/my-windhawk-mods/blob/b34d4bf01759e1efac50dcc1ed364304619c0286/mods/taskbar-clock-customization.wh.cpp

**Comment by keatit71** [comment]
i was having issue with the clock being gone entirely and the new version you made fixed the problem for me thanks

**Comment by m417z** [comment]
Fixed in version 1.4, please let me know if you encounter any other issues with the new "Show abbreviated time and date" option.
