### ISSUE TITLE
When using taskbar-icon-size with taskbar-vertical taskbar on secondary monitor gets scrunched up

### ISSUE THREAD

**Issue by perpleksed** [ramensoftware/windhawk-mods#1283]
@m417z 

Taskbar on main monitor is OK, taskbar on second monitor becomes this:

![изображение](https://github.com/user-attachments/assets/32c15641-825f-4918-af30-dd81e60e079b)

**Comment by m417z** [comment]
From the mod description:

> ### Compatibility
> [...]
> Some of the other taskbar mods, such as [Taskbar height and icon size](https://windhawk.net/mods/taskbar-icon-size), aren't compatible with this mod.

**Comment by perpleksed** [comment]
Oh, that's unfortunate. Sorry
