### ISSUE TITLE
[explorer-details-better-file-sizes] bug,Conflicts with the Everything software itself.

### ISSUE THREAD

**Issue by easyatm** [ramensoftware/windhawk-mods#1289]
When calculating folder size using Everything, it conflicts with the Everything software itself. Opening the path in the Everything software causes both Everything and the Explorer window to hang for an extended period. The log shows:

[674:CFSFolder__GetSize_Hook]: Failed to get size: Reply Timeout for D:\Windhawk\UI

**Comment by m417z** [comment]
Fixed in version 1.4.5.

**Comment by easyatm** [comment]
Have you considered retrieving folder sizes in the background, similar to macOS? For example, first displaying the file list and then gradually showing the folder sizes. If this is too complex to implement, I would hope to include a "shift" key toggle (even if using Everything), as there will inevitably be some delay.

**Comment by m417z** [comment]
> Have you considered retrieving folder sizes in the background

That could be nice, but it'll require some non-trivial research to understand how the list is rendered and how such data can be added asynchronously, and then it'll possibly require some non-trivial implementation. I don't plan looking at it at this point.

> include a "shift" key toggle (even if using Everything), as there will inevitably be some delay

I think the delay isn't significant enough to warrant a Shift key option. Also, [an Everything SDK update](https://www.voidtools.com/forum/viewtopic.php?p=71958#p71958) will make it much faster, which will hopefully make the delay imperceivable.

**Comment by easyatm** [comment]
I tested it, and it is indeed very fast, measuring in milliseconds, consistently showing 0.
I can compile the Everything3 SDK source code using Clang in Visual Studio 2022 without modifications, but when integrating Everything3.c into a single source file, I encounter many type errors. Even adding extern "C" {} might only handle function interfaces; the internal code is still being compiled with the C++ compiler.
I want to try this in Windhawk. How can I add C source files to the compilation process in mod.wh.cpp?

Also, have you considered modifying this mod recently?

**Comment by m417z** [comment]
> How can I add C source files to the compilation process in mod.wh.cpp?

You can try specifying it in `@compilerOptions`. It might work, but I didn't try it myself.

> Also, have you considered modifying this mod recently?

I took a quick look, and integrating it was easier than I though. You can try this version:

https://github.com/m417z/my-windhawk-mods/blob/197371b0b5b9346f745f51fec69854bbf51bc246/mods/explorer-details-better-file-sizes.wh.cpp

To try it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the test mod code, click "Compile Mod", then "Exit Editing Mode".

**Comment by easyatm** [comment]
Using @compilerOptions -x c D:\software tools\Windhawk\AppData\EditorWorkspace\Everything3.c added a C source file, but I still got the following error:
error: invalid argument '-std=c++23' not allowed with 'C'
If need to modify the everything3.c source file to be compatible with the C++ compiler, it may require a lot of changes.

I compiled it into a DLL and successfully used it in Windhawk, with basically no latency or delay, the file is very small, and each file recreates the IPC connection.

**Comment by easyatm** [comment]
> > How can I add C source files to the compilation process in mod.wh.cpp?
> 
> You can try specifying it in `@compilerOptions`. It might work, but I didn't try it myself.
> 
> > Also, have you considered modifying this mod recently?
> 
> I took a quick look, and integrating it was easier than I though. You can try this version:
> 
> https://github.com/m417z/my-windhawk-mods/blob/197371b0b5b9346f745f51fec69854bbf51bc246/mods/explorer-details-better-file-sizes.wh.cpp
> 
> To try it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the test mod code, click "Compile Mod", then "Exit Editing Mode".

Wonderful, you actually extracted the code directly, it's very fast and usable.
