### ISSUE TITLE
[Vertical Taskbar for Windows 11] Large padding on Widgets item

### ISSUE THREAD

**Issue by rechington** [ramensoftware/windhawk-mods#1290]
@m417z On version 24H2 build 26100.2454, the Widget item a has very wide padding, presumably for all the different weather events it can display. Is it possible to fix this, maybe force the Widget to only display an icon with the temperature?

![Image for reference](https://github.com/user-attachments/assets/83850240-e0fc-43f3-ac49-af2970f96e1e)

**Comment by m417z** [comment]
Is it different when the taskbar isn't vertical? I'd assume that it's the same except for the rotated icon, so I'm wondering whether it's a Windows issue.

For now, you might want to try using the [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) mod to customize its height or other parameters to your preference.

**Comment by rechington** [comment]
Oh it is, my apologies for missing this. I used centered icons on the horizontal taskbar, so I didn't realise how ugly it is by default with left aligned ones. I will check out Taskbar Styler to see if it can improve it, thank you.
