### ISSUE TITLE
[Taskbar Labels for Windows 11] Explorer crashes after switching to secure desktop

### ISSUE THREAD

**Issue by Bert-Proesmans** [ramensoftware/windhawk-mods#1292]
Hi, I've reinstalled my system with Win11 24H2 (26100.2454 - Enterprise [IoT] [LTSC]) and now explorer.exe crashes 2 seconds after returning from the secure desktop (aka where the user permission elevation form is displayed by default).
I've narrowed it down to specifically mod "Taskbar Labels for Windows 11", the symptoms are 90%+ reproducible.

How to reproduce;
1. Open any program as administrator; powershell or task manager or whatever
2. Complete the elevation prompt (from secure desktop)
3. On the session desktop wait 1-2 seconds
4. Witness the wallpaper background going black and taskbar dissapearing (<- explorer crashes)
5. Wait 1 second, wallpaper comes back (<- explorer restarts)
6. Wait 3 seconds, taskbar reappears (xaml taskbar loaded) ( !! The taskbar sometimes takes longer to re-appear after explorer crashes, up to 30 seconds according to my experience)

What is expected;
The taskbar should not dissapear and reappear after completing the elevation form.

Author; @m417z 
[Taskbar Labels for Windows 11 log.txt](https://github.com/user-attachments/files/17981564/Taskbar.Labels.for.Windows.11.log.txt)
~~I'll get you a dump file of the crash a bit later~~
EDIT; A temporary WeTransfer link containing the zipped dump file was sent via the discord server

**Comment by m417z** [comment]
Can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by m417z** [comment]
Fixed in version 1.3.3.
