### ISSUE TITLE
[Windows 11 Start Menu Styler] Doesn't work

### ISSUE THREAD

**Issue by rechington** [ramensoftware/windhawk-mods#1294]
@m417z the debug logs are empty as described in the troubleshooting guide, but I don't know how to use Microsoft's DebugView. I tried restarting StartMenuExperienceHost.exe, Windhawk, and Windows, none achieving any results.

Other Windhawk mods I use:
Better file sizes in Explorer details, Disable grouping on the taskbar, Modernize Folder Picker Dialog, Primary taskbar on secondary monitor, Taskbar tray system icon tweaks, Turn off change file extension warning, Vertical Taskbar for Windows 11
Other mods I use:
Nilesoft Shell, ExplorerBlurMica, MacType

Disabling all of these and running only Start Menu Styler still did not make it work.

**Comment by m417z** [comment]
Might be similar to [this issue](https://github.com/ramensoftware/windhawk-mods/issues/747). Please try to reinstall Windhawk, let me know if that helps.

**Comment by rechington** [comment]
Sorry I didn't come across that thread while searching for a solution 😫 That indeed fixed it! Even with the portable version, just had to make sure to manually delete everything first. This will probably fix a bunch of other small issues I had, thank you!!
