### ISSUE TITLE
win10-taskbar-on-win11-24h2 does not seem to work.

### ISSUE THREAD

**Issue by Charles-George** [ramensoftware/windhawk-mods#1306]
@Anixx

It says it should work with TBT 7+ but the latest beta of TBT 7+ says the W11 taskbar is not compatible.

let me know if you need anything or other things I can try, thanks.

**Comment by Anixx** [comment]
What is TBT 7+?

**Comment by Charles-George** [comment]
https://ramensoftware.com/7-taskbar-tweaker

**Comment by Anixx** [comment]
Do you have Win10 taskbar or Win11 taskbar?

**Comment by Charles-George** [comment]
it looks like Win11.

**Comment by Anixx** [comment]
Then the mod does not work. Give me the logs.

**Comment by Charles-George** [comment]
I'm now getting enough of what i need from some other mods on windhawk.
