### ISSUE TITLE
taskbar not translucent after updating the mod.

### ISSUE THREAD

**Issue by spindashh** [ramensoftware/windhawk-mods#1311]
Been using Windows 11 Taskbar Styler to make my desktop look completely transparent but after one of the latest updates the taskbar is now opaque. checked the windows personalization settings to make sure it wasnt anything on that part.

picture one is how it used to look:

![Screenshot 2024-12-07 000211](https://github.com/user-attachments/assets/048e1dc1-b734-4711-aa3a-80fb2affe311)

picture 2 is now:

![Screenshot 2024-12-07 000025](https://github.com/user-attachments/assets/ec85d814-d4f7-49fa-b01a-2c9f044446cc)

**Comment by m417z** [comment]
Hi, it looks similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/1146. Please see my reply there. Closing as a duplicate.
