### ISSUE TITLE
[Taskbar Labels for Windows 11] v1.3.3 regression to thumbnail titles

### ISSUE THREAD

**Issue by mcgwiz** [ramensoftware/windhawk-mods#1329]
In v1.3.1, when "Hide labels, don't combine taskbar items" was enabled, the taskbar preview thumbnails that appear on hover display title text above each. However, in v1.3.3, the title text is no longer displayed. This is important information since the window title is not shown as a label directly on the taskbar when this mode is set.

**Comment by m417z** [comment]
v1.3.3 had other issues: the thumbnail labels were affected by Windows taskbar properties, and also affected clicks on uncombined groups, see https://github.com/ramensoftware/windhawk-mods/issues/1126.

I didn't find a quick fix to have the taskbar thumbnails show correctly for items without labels, but I added an option to show thumbnail labels on all thumbnails that can be used as a workaround. Please try v1.3.5.

**Comment by mcgwiz** [comment]
Trying out v1.3.5. The new option seems to address the issue - thank you.
