### ISSUE TITLE
[Better file sizes in Explorer details] Display Folder sizes within libraries

### ISSUE THREAD

**Issue by Savisthorv** [ramensoftware/windhawk-mods#1331]
Plugin: Better file sizes in Explorer details by @m417z

Currently library folders do not display file sizes when navigating through libraries, while the same folders are displayed through direct navigation.

![Library](https://github.com/user-attachments/assets/fe9f7ee5-1e6a-49c7-a4fe-b8e48327b9ab)
![Documents](https://github.com/user-attachments/assets/e81b3312-728e-47f9-8136-a9090bf995ac)

**Comment by m417z** [comment]
Fixed in version 1.4.6.
