### ISSUE TITLE
vertical taskbar mod not working after windows 11 update Build 27764

### ISSUE THREAD

**Issue by hao365** [ramensoftware/windhawk-mods#1334]
![微信截图_20241212111050](https://github.com/user-attachments/assets/04ab2245-5acb-48ac-be7a-1966e4462088)

**Comment by m417z** [comment]
Looks like a duplicate of https://github.com/ramensoftware/windhawk-mods/issues/1271, see my comment with a workaround in that issue. Let me know if it's a different issue.

**Comment by hao365** [comment]
Resolved, Thx.
