### ISSUE TITLE
Win11 Start Menu Styler: "All Apps" list gone

### ISSUE THREAD

**Issue by WiktorWdowiak** [ramensoftware/windhawk-mods#1341]
**I am using Win11 Start Menu Styler by @m417z  with the Windows11_Metro10 theme.**
After applying the theme, the Start Menu has the "All Apps" list gone. I've tried pasting the theme's code into the Advanced tab, but to no avail. After exploring further, I noticed that the list is gone in every theme, even after restarting Windhawk/removing & adding the mod again. I tried using the mod version from this pull request: https://github.com/ramensoftware/windhawk-mods/issues/1335 but it also didn't work. I attached a screenshot of the issue.
![image](https://github.com/user-attachments/assets/5c96ef11-e97f-4a05-b9a3-10af5d8e9ca1)

**Comment by m417z** [comment]
Maybe similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/1297
What's your Windows 11 version? Are you using a preview build?

**Comment by WiktorWdowiak** [comment]
I'm using the 24H2 (26120.2510) Dev Build - I've been using the mod for some time now, and it's worked fine before, only noticed that today.

**Comment by m417z** [comment]
OK, closing as a duplicate. From my reply in the other issue:

> Preview builds (Dev, Canary, Beta, Release Preview) aren't generally supported. They're a moving target, some things might work, and other things might be incompatible. For best compatibility with Windhawk, avoid using preview Windows builds.
