### ISSUE TITLE
DWM crashes with "Classic Theme Enable with extended compatibility" mod

### ISSUE THREAD

**Issue by oep42** [ramensoftware/windhawk-mods#1344]
**Mod Dev:** @levitation
**Mod Name:** Classic Theme Enable with extended compatibility, Version 1.3.1
**Issue:** DWM crashes
**System:** Windows 11 Pro, Version 22H2 (OS Build 22621.2506). CPU: AMD Ryzen 9 7900. RAM: 64 GB.

There seems to be a problem with the Windhawk mod "Classic Theme Enable with extended compatibility". When this mod is active, sometimes DWM crashes and the system is automatically logged off. Then everything that was not saved, will be lost.

If you log in after such an automatic log-out, you will see this message: "Your session was logged off because DWM crashed. Please contact your administrator for further information and check the event log."

![Your session was logged off because DWM crashed](https://github.com/user-attachments/assets/57372713-1d5f-4e0d-85d8-b10e5e701dba)

I suppose that this error is related to the mod: "Classic Theme Enable with extended compatibility", but I am not completely sure, because these six mods were also installed with Windhawk when this error happened:
- Classic Task Dialog Fix, Version 1.1.0; 
- Classic Taskbar 3D buttons Lite, Version 1.3; 
- Classic Taskbar background fix, version 1.0.3; 
- Classic theme transparency fix, Version 1.0; 
- Classic UWP Fix, Version 0.3; 
- Clientedge Everywhere, Version 1.0.

The process inclusion list of "More advanced settings" of Windhawk, contained during this crash only these two items: dllhost.exe; winlogon.exe.

**General description of what happens with this crash, according to Windows Event Viewer:**
The Desktop Window Manager process exites 8 times with "Primary display device ID: AMD Radeon(TM) Graphics", and after that it exites one more time (the last time before the crash) with "Primary display device ID: Microsoft Basic Display Driver". After that, DWM crashes. 
 
**More details about what happens with this crash:**
These are the last events in the Event Viewer before the crash:

- [Warning; Source = Dwminit; Event ID = 0:] The Desktop Window Manager process has exited. (Process exit code: 0x80070490, Restart count: 7, Primary display device ID: AMD Radeon(TM) Graphics)
- [Information; Source = Desktop Window Manager; Event ID = 9027:] The Desktop Window Manager has registered the session port.
- [Warning; Source = Dwminit; Event ID = 0:] The Desktop Window Manager process has exited. (Process exit code: 0x80070490, Restart count: 8, Primary display device ID: AMD Radeon(TM) Graphics)
- [Information; Source = Desktop Window Manager; Event ID = 9027:] The Desktop Window Manager has registered the session port.
- [Warning; Source = Dwminit; Event ID = 0:] The Desktop Window Manager process has exited. (Process exit code: 0x80070490, Restart count: 9, Primary display device ID: Microsoft Basic Display Driver)
- [Information; Source = Desktop Window Manager; Event ID = 9027:] The Desktop Window Manager has registered the session port.

**The crash of DWM as shown in the Event Viewer:**
[Error; Source = Application Error; Event ID = 1000; Task Category = Application Crashing Events:]
Faulting application name: StartMenuExperienceHost.exe, version: 10.0.22621.2506, time stamp: 0xc48453f8
Faulting module name: amdxx64.dll, version: 31.0.14070.0, time stamp: 0x6491faed
Exception code: 0xc0000005
Fault offset: 0x0000000000481c89
Faulting process id: 0x0x19C8
Faulting application start time: 0x0x1DB4E0E392222F9
Faulting application path: C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0393743.inf_amd64_52bb45d16658cef5\B393344\amdxx64.dll
Report Id: 6bfea85f-1982-4c57-b125-5ea2c8cac80c
Faulting package full name: Microsoft.Windows.StartMenuExperienceHost_10.0.22621.2506_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: App

![Crash of DWM (14-12-2024)-01](https://github.com/user-attachments/assets/6c6b0372-d6d6-48e4-9b3b-550812a6563c)

![Crash of DWM (14-12-2024)-02](https://github.com/user-attachments/assets/149c808f-c4c7-4f8f-8f8d-0f949fbbfd18)

I have saved logs from the Advanced tab of Windhawk after logging in after a crash. These have different timestamps than the time of the crash, so they seem to be unrelated to the crash.

**Comment by levitation** [comment]
@oep42 Please note that this mod injects into winlogon.exe not into dwm.exe. Additionally this mod does nothing after enabling classic theme. It does not hook any functions. So if dwm.exe crashes then I suspect there is general problem with Classic Theme in your machine, not with this mod in particular.

**Comment by levitation** [comment]
> "The process inclusion list of "More advanced settings" of Windhawk, contained during this crash only these two items: dllhost.exe; winlogon.exe." 

In my readme file I recommend enabling four programs:

conhost.exe
dllhost.exe
dwm.exe
winlogon.exe

So it looks to me your setup is nonstandard and then anything can cause the crash you have.

**Comment by levitation** [comment]
I notice also that it has been a while since you installed this mod. So naturally it might be helpful to think - what has changed today or yesterday that you now have the crashes? Or did you reboot your computer today/yesterday and installed some unusual software earlier which activated only now after the restart?

**Comment by oep42** [comment]
@levitation Thank you for your response.

Prior to using the "Classic Theme Enable with extended compatibility" mod, I never experienced a DWM crash. So I have to assume that such a crash is somehow related to using this mod, or any of its additional Classic Theme related mods, or using ExplorerPatcher, or using Open-Shell-Menu, or using 7+ TaskBar Tweaker.

> Please note that this mod injects into winlogon.exe not into dwm.exe. Additionally this mod does nothing after enabling classic theme. So if dwm.exe crashes then I suspect there is general problem with Classic Theme in your machine, not with this mod in particular.

None of the used mods inject into dwm.exe. A DWM crash only occurs after logging on to Windows and after the appearance of the classic Windows user interface. So I guess it is more obvious that a DWM crash is caused by ExplorerPatcher, or Open-Shell-Menu, or 7+ TaskBar Tweaker, or any process triggered by these programs.

I had the same DWM crashes with the earlier 1.2.1 version of the "Classic theme enable with extended compatibility" mod. It is hard to know what triggers this crash because it occurs very rarely. It usually occurs within a few minutes after logging on to Windows, but it has also occurred when Windows has been running for hours. I do not really understand the error information in the Windows event viewer. Does this information give any indication of what program or process related to the Classic Theme may cause a DWM crash? May ExplorerPatcher or Open-Shell-Menu or 7+ TaskBar Tweaker interact with dwm.exe in a way that triggers a DWM crash? Would it make sense to unblock dwm.exe in my firewall? (At this moment, dwm.exe is blocked by default, and I will not get notified when dwm.exe tries to connect to the internet.)

-----

> So it looks to me your setup is nonstandard and then anything I am not aware of could cause the crash you have. I suggest you to run your finger over the readme instructions and see what is different, then start eliminating the differences one by one.

Eliminating the differences one by one with the readme instructions, and then seeing if that makes a difference, is a somewhat problematic approach to finding the cause of a problem that usually occurs very rarely. So it's hard to know in the short term, whether any change will solve the problem or not. And in the long term, after many changes in the system, it may be impossible to know what change, if any, is responsible for a DWM crash not to occur anymore.

I understand the suggestion to follow the readme instructions completely in case of problems, as a way to solve the problem of DWM crashes. However, when I decide to skip some additional classic theme related mods because they do not offer any added value for me, it makes sense to also skip the processes in the Windhawk inclusion list that are only releated to such skipped mods.

I understand that the "Classic Theme Enable with extended compatibility" mod only injects in the winlogon.exe process, and that the "Classic theme transparency fix" mod only injects in the dllhost.exe process. As far as I know, all the other used mods do not inject in any process. This is why I included only dllhost.exe and winlogon.exe in the Windhawk process inclusion list.

(Because only the skipped "Disable rounded corners in Windows 11" mod and the skipped "Aero Tray" mod inject in the dwm.exe process, there is no need to include the dwm.exe process in the Windhawk inclusion list. Because only the skipped "Classic Conhost" mod injects in the conhost.exe process, there is no need to include the conhost.exe process in the Windhawk inclusion list.)

I understand that it is better to minimize the intrusion of Windhawk mods into the system, and therefore to use only those mods that are necessary to achieve the desired result, and to add only those processes to the Windhawk process inclusion list that are necessary to achieve that desired result.

-----

> For getting started with debugging, you may want to try this mod, which is a simpler version - https://windhawk.net/mods/classic-theme-enable - though with this mod you may have additional issues.

In the past, I tried this simpler mod, but with it, I did not succeed to get the Classic Theme and the 3D taskbar buttons. Now I tried this simpler mod again, by replacing in Windhawk the "Classic theme enable with extended compatibility" mod by the simpler "Enable Classic Theme by handle method". 

Unlike in the past, I was able now to get the Classic Theme and 3D taskbar buttons to work with the simpler "Enable Classic Theme by handle method" mod. This time, I followed the instructions for the "Activate Classic Theme with extended compatibility" mod [as edited by OrthodoxWin32](https://docs.google.com/document/d/1Ko9WhRFB7XHqsAug3KKSo4PsuUxSL9_SToHiouRU1k8/edit). Perhaps the change in my firewall to allow "C:\Windows\explorer.exe" to communicate with the Internet, and then to download symbols, is why the simpler mod works now. Assuming that this simpler mod is less intrusive on the system, and therefore less likely to cause problems, I decided to use this mod for now to get the Classic Theme. (I have been warned about the drawbacks of this simpler mod. So far it seems to work well for me.)

------

I will close this issue, because a DWM crash cannot be caused by the "Classic theme enable with extended compatibility" mod.

**Comment by levitation** [comment]
@oep42 Yes, internet access is needed for various mods, as well as for ExplorerPatcher. The mods that do not inject into any particular process, they inject into all processes, except certain system processes. Some of the mods need internet access as well, but I do not remember which ones. Probably the ones that hook by symbols. You may disable internet access for most of the time, but it is often necessary to temporarily re-enable it after Windows update.

**Comment by oep42** [comment]
After updating all drivers associated with the motherboard hardware, the DWM crashes stopped. So the DWM crashes seem to have been caused by a bug in the software of the motherboard hardware. (The DWM crashes only occurred when using the "Classic Theme Enable with Extended Compatibility" mod, which earlier led me to believe that this mod was the cause of the problem.)
