### ISSUE TITLE
explorer-details-better-file-sizes - Folders do not sort by size when "mix files and folders..." setting is disabled

### ISSUE THREAD

**Issue by ProudAnselmoIII** [ramensoftware/windhawk-mods#1347]
[explorer-details-better-file-sizes_debug.txt](https://github.com/user-attachments/files/18142509/explorer-details-better-file-sizes_debug.txt)

[Screenshot 2024-12-15 180501](https://github.com/user-attachments/assets/1f397421-1917-4dcb-8bca-fcc981da94ed)

@m417z what the title says. Folders won't sort by size if they're grouped together

**Comment by m417z** [comment]
Fixed in version 1.4.6.
