### ISSUE TITLE
[Taskbar Clock Customization] Default web content items settings cause explorer.exe to constantly download in the background

### ISSUE THREAD

**Issue by roulings** [ramensoftware/windhawk-mods#1358]
The default settings (or sample values) for the web content items section in the Taskbar Clock Customization mod apply automatically, which causes explorer.exe to download around 1 MB/s constantly while the computer is connected to the internet.

I have replicated the bug in the screenshot below.

![image](https://github.com/user-attachments/assets/63abbfc8-476a-4640-8154-15fc8e9477e3)

**Comment by m417z** [comment]
What's on your screenshot are not the default settings, all values are empty but the URL. As a result, the content extraction fails, and it tries again and again.

**Comment by m417z** [comment]
I had a look at it. What I said in my previous comment isn't quite right - the settings on the screenshot result in an empty content.

I can't see it in the screenshot, but my best guess is that you set "Web content update interval" to zero, in which case the URL is queried non-stop.
