### ISSUE TITLE
Resource Redirect not loading theme.ini

### ISSUE THREAD

**Issue by NoNameNeeded5** [ramensoftware/windhawk-mods#1388]
Even though redirections work when you enter the paths manually in the settings GUI (like you normally would) the theme.ini has absolutely no effect.
Resource Redirect won't do anything with it.

I've ruled out that there's anything wrong with the theme.ini (I've tried more than one theme).
It just doesn't do anything at all.

I use version 1.1.9 of Resource Redirect.

I read that there was a bug with files larger than 32KB but that's not the problem in my case.

P.S. My OS is Windows 11 (23H2).

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by NoNameNeeded5** [comment]
[debug.txt](https://github.com/user-attachments/files/18267824/debug.txt)

**Comment by m417z** [comment]
The theme folder (not file) shouldn't end with "theme.ini".

**Comment by NoNameNeeded5** [comment]
The theme folder should have a file extension??
Maybe someone should have pointed that out...

How's the file supposed to be called then?

I now have a folder that ends in theme.ini and the file that is called theme.ini

Still doesn't seem to be doing anything...

**Comment by m417z** [comment]
What I mean is that the settings ask for thr path of the folder that contains the theme.ini file, not the path of the theme.ini file itself.

**Comment by NoNameNeeded5** [comment]
Oh ok, NOW I get it.

I misunderstood what you said.
Sorry.

And yes, it seems to work now.
