### ISSUE TITLE
task bar clock and other items are not vertically aligned while using "taskbar-icon-size" mod.

### ISSUE THREAD

**Issue by anaysharma** [ramensoftware/windhawk-mods#140]
first of all, thanks for this awesome app!

this issue occurred after latest update, the icons and clock on the right corner of the taskbar are no longer centered vertically.

![issue preview image](https://user-images.githubusercontent.com/56938211/226105019-71d587b4-3cb3-464d-96c3-6994aaf76701.png)

> mod settings:
```
{"IconSize":19,"TaskbarHeight":40}
```
> system info:
```
OS: windows 11 home single language
OS version: 10.0.22621 Build 22621
Windhawk version: 1.1 beta
```

**Comment by m417z** [comment]
According to the screenshot, you don't have the latest update installed (KB5023706). Any reason for that?
There have been many changes to the taskbar lately, and it's difficult to support all versions. I tried to support Windows 11 21H2 and 22H2 with latest updates, and didn't look at older versions. If you prefer to not install the latest updates (it's a good idea to update for security patches, too), you can install the previous version of the mod for now. Let me know if you need help with that, it's not that straightforward but not difficult.

**Comment by anaysharma** [comment]
updating the windows fixed it, thanks for help.
