### ISSUE TITLE
[Taskbar Labels] Wrong badge position for UWP apps

### ISSUE THREAD

**Issue by Trixlight** [ramensoftware/windhawk-mods#152]
![ApplicationFrameHost_2023-03-29_06-34-43](https://user-images.githubusercontent.com/33410668/228405514-fa135b34-244a-469b-af94-0344bbadcb45.png)

Might be a problem with my version of Windows, needs testing.

Windows 11 22610.1
Windhawk v1.1 beta
Mod version 1.1.1

**Comment by m417z** [comment]
This issue was fixed in version 1.1 of the mod. You're saying that you're using version 1.1.1 - please make sure that's the case and that no other version/fork is installed.

**Comment by Trixlight** [comment]
The fix doesn't seem to work for uwp apps. Testing on the latest? stable build of Windows 11.
![VirtualBoxVM_2023-03-30_10-13-32](https://user-images.githubusercontent.com/33410668/228736156-a9f5523d-6e3d-4188-bc77-e148b27ad465.png)

**Comment by m417z** [comment]
Thanks for reporting. Fixed in version 1.1.2.
