### ISSUE TITLE
[Disable grouping] Missing "shift+click" functionality to open new instance of process

### ISSUE THREAD

**Issue by m417z** [ramensoftware/windhawk-mods#158]
> on the normal taskbar, if you shift+click the toolbar icon it'll spawn a new instance
> 
> eg. clicking the taskbar label for an open instance of notepad will open a second instance of notepad

_Moved from https://github.com/m417z/my-windhawk-mods, originally posted by @twig-atl on Mar 20, 2023_

**Comment by m417z** [comment]
@twig-atl should be fixed with version 1.1 of the mod.

**Comment by twig-atl** [comment]
Thanks @m417z !
