### ISSUE TITLE
[Error] Virtual Desktop Preserve Taskbar Order

### ISSUE THREAD

**Issue by Hugocorreaa** [ramensoftware/windhawk-mods#167]
I coun't install this mod on win11

![image](https://user-images.githubusercontent.com/66891476/231487165-b81eb9f4-389d-403b-8046-3dc732f7e6b9.png)

**Comment by m417z** [comment]
1. What's your Windhawk version?
2. Can you please post the content of the following file: `C:\ProgramData\Windhawk\EditorWorkspace\compiler_errors.log`

**Comment by Hugocorreaa** [comment]
I didn't see that my windhawk wasn't update. I updated and it works. Thank you
