### ISSUE TITLE
[Taskbar Thumbnail Reorder] Doesn't work on Win11 25336.100

### ISSUE THREAD

**Issue by Horrah123456** [ramensoftware/windhawk-mods#171]
Download mod and install is not available, it can be opened normally but the left mouse button cannot move the preview image

**Comment by m417z** [comment]
That's an insider build and it's unsupported at this point. It was reported before in the Windhawk Discord channel, I tried to find a quick fix but too many changed were made in recent insider versions. I'll look at it at some point, but it's not a priority.

**Comment by m417z** [comment]
Version 1.0.8 adds support for Windows 11 version 24H2. Insider versions support might improve as well as a result.
