### ISSUE TITLE
Wheeling in icons also control volume [Taskbar Volume Control]

### ISSUE THREAD

**Issue by mateusfn98** [ramensoftware/windhawk-mods#172]
I have a lot of icons in my taskbar, and sometimes i miss the area without icons.
If possible and easy, please add the wheeling on icons to trigger the action.

**Comment by m417z** [comment]
What do you mean? There are two areas you can choose in the settings - the notification area, or the whole taskbar. The whole taskbar should work on the whole taskbar, including all icons. Can you post a screenshot or a video and show your mod configuration and the location where mouse scrolling does and doesn't work? Also, are you using Windows 10 or 11?

**Comment by mateusfn98** [comment]
I have a lot of windows tweaks :/
I'll try to find what tool is causing it!
Thanks!

**Comment by mateusfn98** [comment]
Oh my god, after a lot of tries, I found it!
Don't know why, but X-MOUSE BUTTON it's the cause.
Don't hurry to fix it, I can use other mouse keybinder, thanks! :D
