### ISSUE TITLE
[Taskbar Clock Customization] Add timezone to format

### ISSUE THREAD

**Issue by klkvsk** [ramensoftware/windhawk-mods#173]
I'd like to show my current timezone, but it's not in the API for GetTimeFormatEx, so it should be fetched separately.
Timezone can be shown in different formats, I suggest adding following template placeholders:
- `%tz_name%` = `Europe/Paris`
- `%tz_abbr%` = `CET` 
- `%tz_hour%` = `+2`
- `%tz_hourmin%` = `+2:00`
- `%tz_utc%` = `UTC +2` (but if with minutes then `UTC +6:30`)

**Comment by m417z** [comment]
I added the timezone in ISO 8601 format. More formats may be added in the future if there's demand for it.

**Comment by klkvsk** [comment]
Great work! Thanks

**Comment by bdoviack** [comment]
Is there a way to show multiple time zones? For example, we have some production sites in Asia and it would be great to see their local time in addition to our local time. Labels or names for each timezone would be a great bonus too.

**Comment by m417z** [comment]
@bdoviack the mod doesn't have such an option, but Windows allows to do that natively, in which case the extra timezones are displayed on hover and on click:
https://www.anoopcnair.com/windows-11-add-additional-time-zone-clocks/

**Comment by bdoviack** [comment]
Yes, I have that multi-timezone feature enabled but it would be great to have it always visible. There are similar solutions available like https://www.1stclock.com/world-time-zone-clock.php but your approach seems less resource intensive and more "elegant"

Thanks for the efforts you've provided so far.

**Comment by digvijayad** [comment]
> Is there a way to show multiple time zones? For example, we have some production sites in Asia and it would be great to see their local time in addition to our local time. Labels or names for each timezone would be a great bonus too.

@m417z I was also looking for having multiple timezone always displayed. Is that not possible?

**Comment by digvijayad** [comment]
@bdoviack I was able to get it to always display in taskbar, see the solution in this issue. 
https://github.com/ramensoftware/windhawk-mods/issues/1082#issuecomment-2678992993
