### ISSUE TITLE
Some options don't work.

### ISSUE THREAD

**Issue by crz4all** [ramensoftware/windhawk-mods#18]
Taskbar Clock Customization.
It simply loses all settings on restart, I have to configure everything again.

Middle click to close on the taskbar
Do not work.

**Comment by m417z** [comment]
> Taskbar Clock Customization.
> It simply loses all settings on restart, I have to configure everything again.

Looks like the issue [discussed here](https://github.com/ramensoftware/windhawk-mods/discussions/13). Are you using the latest version of the mod, v1.0.3?

> Middle click to close on the taskbar
> Do not work.

What your Windows version? What's your version of explorer.exe?

**Comment by m417z** [comment]
https://github.com/ramensoftware/windhawk-mods/discussions/13#discussioncomment-3156107
> I was still using a beta version.
> After I updated, it's working.
