### ISSUE TITLE
Taskbar height and icon size - behavior is inconsistent on win11 tablet mode

### ISSUE THREAD

**Issue by MuscularPuky** [ramensoftware/windhawk-mods#184]
it seems the arrangement of the taskbar (not the icons) is unspecified.

first enable: 
![image](https://user-images.githubusercontent.com/93962018/232758828-230a7940-25cd-4b34-aad8-5ef4a26879d6.png)
cloeck and tray icons are normal

![image](https://user-images.githubusercontent.com/93962018/232758576-df7a236a-742b-4ecd-a717-e4bbe1cb7708.png)
changing height not works cuz the taskbar is not aligned bottom

after restart explorer: 
![image](https://user-images.githubusercontent.com/93962018/232757768-606008c7-6e6a-479f-87be-54cfd5f587bc.png)
the clock and tray icons are out of place.

![image](https://user-images.githubusercontent.com/93962018/232758087-f97bdfcc-d835-43b9-8993-a4a0de68cb45.png)
changing height works fine cuz the taskbar is aligned bottom.

these can't revert until disable the mod and restart explorer.

both seem to have advantages for me. 

+MS hardcoded the tablet mode taskbar at height of 48 and 72

**Comment by m417z** [comment]
Do you know how to enable tablet mode without an actual tablet? I tried enabling it but what I got looked like the picture on the left, and wasn't functional at all with the mod:

![image](https://user-images.githubusercontent.com/4129781/233807961-b28f4e65-c5b3-47fc-a59e-274c40cdc677.png)

**Comment by MuscularPuky** [comment]
i found it: reg.exe add "hkey_current_user\software\microsoft\windows\currentversion\explorer\advanced" /v "tabletposturetaskbar" /t "reg_dword" /d 1 /f

**Comment by MuscularPuky** [comment]
if you are seeing taskbar like left pic it worked successfully.

first mod enable (normal):
![image](https://user-images.githubusercontent.com/93962018/233896094-f42abebb-d744-4a55-b6d7-e1c6a8eb4987.png)


after restart windows (bug):
![image](https://user-images.githubusercontent.com/93962018/233896069-5b78dc46-cd03-45dd-8c4b-e38fd56f33ad.png)

![image](https://user-images.githubusercontent.com/93962018/233896012-e6ebbbd4-660f-4b02-b131-0ade13863771.png)

**Comment by MuscularPuky** [comment]
I just noticed some issue mentions this recently so I comment how I could solce this problem

Soultion A (I'm using currently): disable then enable the Tablet Optimized Taskbar for 1~2s every security event trigger `ID 4624` `LogonType 7`. the intercal could be adjusted based on your PC spec and mine is 2s. at that toggling "TabletPostureTaskbar" reg value's needed.

Solution B (not tested but will work I think): set `VerticalAlignment = Bottom` to taskbar frame with Windows 11 Taskbar Styler. I not tried this so don't know exactly key name but won't be difficult to find it

**Comment by MuscularPuky** [comment]
> I just noticed some issue mentions this recently so I comment how I could solce this problem
> 
> Soultion A (I'm using currently): disable then enable the Tablet Optimized Taskbar for 1~2s every security event trigger `ID 4624` `LogonType 7`. Task Scheduler'll be helpful. the intercal could be adjusted based on your PC spec and mine is 2s. at that toggling "TabletPostureTaskbar" reg value's needed.
> 
> Solution B (not tested but will work I think): set `VerticalAlignment = Bottom` to taskbar frame with Windows 11 Taskbar Styler. I not tried this so don't know exactly key name but won't be difficult to find it
> 
> +notice: sometimes Windows 11 Taskbar Styler losses its hooking so could won't work rarely bur it's only needed when log on so won't be problem #880

Solution B Target: `SystemTray.SystemTrayFrame`
Worked fine

**Comment by MuscularPuky** [comment]
In Tablet Mode: DON'T CHANGE Taskbar Height
Windows recognizes Taskbar is Tablet Mode only when Height is EXACTLY 48px, and DOES NOT read any Settings config or Registry key
I'd knew that even 3 years ago and used a trick with 47px to decrease notification icons spacing—to bypass Touch Optimize, but I forgot that😕 so I and you guys reading this chased goose at result😖
Even now I recalled, this is really stupid mechanism. the Taskbar is 48px🤣 That's why they can't bring Taskbar resizing uh huh?
