### ISSUE TITLE
"Disable grouping on the taskbar" bug

### ISSUE THREAD

**Issue by hoangqy** [ramensoftware/windhawk-mods#185]
when i use "smart view" on samsung flow app, there crash in taskbar
Debug logging:
[DebugViewConsole 1.8.0.102.txt](https://github.com/ramensoftware/windhawk/files/11265370/DebugViewConsole.1.8.0.102.txt)

**Comment by m417z** [comment]
Can you please create and upload a crash dump?

You can use ProcDump. Run `procdump64.exe -mp -e explorer.exe` and trigger the crash. The dump will be written to a file, the details will be printed in the ProcDump console window.

**Comment by hoangqy** [comment]
After checking again I found the error occurred when I use 2 mods "Taskbar Labels for Windows 11" and "Taskbar Labels for Windows 11"
crash dump: https://drive.google.com/file/d/12Du8Yc4k9d9-Q9Ug2fsjSz14Pkm6LB7N/
mod settings: 
[mod settings.txt](https://github.com/ramensoftware/windhawk-mods/files/11268519/mod.settings.txt)

**Comment by TGSAN** [comment]
Same error on Remote Desktop UWP, explorer loop crash when create a new window. (Downgrade to v1.0 will fix it, but uwp still grouping on taskbar)

**Comment by m417z** [comment]
I wasn't able to reproduce it but I believe that it's now fixed in version 1.2. Please try it and let me know whether it's fixed.

**Comment by hoangqy** [comment]
it's fixed, thanks
