### ISSUE TITLE
Mod request: Disable taskbar thumbnails when hovering over programs on the taskbar

### ISSUE THREAD

**Issue by ItsProfessional** [ramensoftware/windhawk-mods#187]
When I use the "disable taskbar grouping" mod, I do not really need the taskbar thumbnails to show up when hovering over the taskbar items (especially in conjunction with the "taskbar labels" mod), and they only clutter things up for me. A mod that disables these thumbnails would be great

**Comment by m417z** [comment]
Done: [Disable Taskbar Thumbnails](https://windhawk.net/mods/taskbar-thumbnails).
