### ISSUE TITLE
Mod Request: Taskbar Labels for Windows 11 - Allow excluding certain applications from getting labels

### ISSUE THREAD

**Issue by ruipin** [ramensoftware/windhawk-mods#203]
It would be cool if, similar to 7+ Taskbar Tweaker, it was possible to exclude certain applications from getting Taskbar Labels added by the Taskbar Labels for Windows 11 mod. Honestly, I might even consider taking a punt at it some day.

Thanks for your amazing work with Windhawk!

**Comment by drygoatair** [comment]
This would be great. Or maybe only add labels to applications that have multiple instances running.

**Comment by wouter-b** [comment]
Or fix the inclusion/exclusion list ;-)
only explorer.exe seems to work now.

**Comment by m417z** [comment]
> Or fix the inclusion/exclusion list ;-)

There's nothing to fix, it works as intended. The custom lists control which programs the mod affects. In this case, the mod affects only one program, explorer.exe which controls the taskbar. In other words, the lists aren’t relevant for this mod. But it would be a nice addition to add configuration regarding which programs should or shouldn’t have labels. I’ll consider adding it in one of the future updates.

**Comment by Abreuvoir** [comment]
Toggling grouping and labels on a per app basis with Taskbar Inspector was probably the main reason I used 7+TT.

I would really like this feature to come back too.

**Comment by lunar-os** [comment]
would be cool to decide the label text for each program

**Comment by m417z** [comment]
Showing/hiding labels per-program is now possible in version 1.3.
