### ISSUE TITLE
Mod idea: Color active program

### ISSUE THREAD

**Issue by mateusfn98** [ramensoftware/windhawk-mods#207]
It would be nice if the active program indicator had a different color.

**Comment by m417z** [comment]
It's not directly related to labels, changed it to a new mod idea.

Note that it's possible with the [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) mod, but it will require some experimentation. For example, here are some ideas:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/3#issuecomment-1873448568

**Comment by mateusfn98** [comment]
Perfect, I did it, thanks!
