### ISSUE TITLE
[taskbar-grouping] Doesn't work properly on second display

### ISSUE THREAD

**Issue by Nico04** [ramensoftware/windhawk-mods#212]
This script works perfectly on main display, but it's juts ignored on secondary display, as shown in picture here :
![image](https://github.com/ramensoftware/windhawk-mods/assets/34476051/b38ebe39-5d89-4bb8-a094-81bfe14eb278)

**Comment by m417z** [comment]
I wasn't able to reproduce it, see Edge below. Did you close and re-open the Firefox windows after enabling the mod? Is it specific to Firefox?

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/c4d4b36d-6eef-482a-b348-2051273278e1)

**Comment by Nico04** [comment]
Well, to be honnest, I can't reproduce it today.
Yesterday it was very reproductible.
Maybe a bug with bad loaded Windhawk plugin ?
Anyway, thanks for the quick answer, I guess you can close it now.
I'll tell you if I find a reproductible way.
