### ISSUE TITLE
[Slick Window Arrangement] Maintaining the aspect ratio of windows while resizing

### ISSUE THREAD

**Issue by shadowmelds** [ramensoftware/windhawk-mods#221]
mod-enhancement：Scale the window to maintain the proportion when holding down a key

**Comment by ReanimationXP** [comment]
"Zooming" is the wrong terminology here - but +1 for "maintaining the aspect ratio of windows while resizing" being a feature. "Shift" is the key most commonly associated with being held down for this function in apps like Photoshop.
