### ISSUE TITLE
[Windows 11 Taskbar Styler] Change styles based on an element's visual state

### ISSUE THREAD

**Issue by mateusfn98** [ramensoftware/windhawk-mods#229]
Change the color of the active program.
Example:
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/53b4c695-d4bd-4489-9c78-1d88fa431d78)
Suggestion (Edge running maximized):
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/bf043894-7091-4ef2-b6b1-6111f09ec4f7)

**Comment by m417z** [comment]
With Windows 11 Taskbar Styler v1.2, it's now possible to define styles per visual state. Check out the mod description for an example.
