### ISSUE TITLE
The Mod named "Taskbar height and icon size" can't work after updating Windows

### ISSUE THREAD

**Issue by Fxxndxn** [ramensoftware/windhawk-mods#244]
The Mod named "Taskbar height and icon size" and explorer.exe can't work after updating Windows.

**Comment by m417z** [comment]
@Fxxndxn moved to the windhawk-mods repo.

Please run the mod with debug logs and post the output.
* Disable the mod.
* Enable **Detailed debug logs** in the mod's Advanced tab.
* Click on **Show log output**.
* Enable the mod.
* Verify that it doesn't work, copy the log output and paste it here.

**Comment by mhgranzotto** [comment]
DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
18:25:34.262 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
18:25:34.262 7132 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.3.1
18:25:34.262 7132 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-icon-size
18:25:34.262 7132 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.2
18:25:34.356 7132 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FF97F3C0000
18:25:34.357 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
18:25:34.357 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
18:25:34.358 7132 explorer.exe  [WH] [taskbar-icon-size] [807:Wh_ModInit]: >
18:25:34.358 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
18:25:34.358 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: IconSize
18:25:34.358 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: IconSize
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 16
18:25:34.359 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
18:25:34.359 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarHeight
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarHeight
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 34
18:25:34.359 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
18:25:34.359 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarButtonWidth
18:25:34.359 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarButtonWidth
18:25:34.360 7132 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 34
18:25:34.360 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
18:25:34.360 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
18:25:34.360 7132 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.View.dll
18:25:34.361 7132 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#1682034385#6828032#public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const #199568#public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)#1017552#public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)#1702796#private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)#2889948#__real@4048000000000000#5718640#public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
18:25:34.361 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
18:25:34.361 7132 explorer.exe  [WH] [taskbar-icon-size] [573:HookSymbols]: Couldn't resolve all symbols from cache
18:25:34.361 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol2
18:25:34.361 7132 explorer.exe  [WH] [LoadedMod::FindFirstSymbol2]: Module: 00007FF95C170000
18:25:34.361 7132 explorer.exe  [WH] [LoadedMod::FindFirstSymbol2]: Path: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll
18:25:34.362 7132 explorer.exe  [WH] [LoadedMod::FindFirstSymbol2]: Version: 623.11001.10.0
18:25:34.403 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
18:25:34.408 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\46ED9E4BB32B434F98DF567B18D6B2E91\Taskbar.View.pdb - path not found
18:25:34.408 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\46ED9E4BB32B434F98DF567B18D6B2E91\Taskbar.View.pd_ - path not found
18:25:34.408 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\46ED9E4BB32B434F98DF567B18D6B2E91\file.ptr - path not found
18:25:34.408 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/index2.txt
18:25:35.684 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
18:25:35.685 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/46ED9E4BB32B434F98DF567B18D6B2E91/Taskbar.View.pdb
18:25:35.838 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
18:25:35.838 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/46ED9E4BB32B434F98DF567B18D6B2E91/Taskbar.View.pd_
18:25:36.350 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
18:25:36.350 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/46ED9E4BB32B434F98DF567B18D6B2E91/file.ptr
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x80190194
18:25:36.500 7132 explorer.exe  [WH] [LoadedMod::LogFunctionError]: Mod taskbar-icon-size error: engine\symbol_enum.cpp(197)\windhawk.dll!00007FF96CF8D0BE: (caller: 00007FF96CF7AE92) Exception(6) tid(1c60) 806D0005 
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol2
18:25:36.500 7132 explorer.exe  [WH] [taskbar-icon-size] [578:HookSymbols]: Wh_FindFirstSymbol failed
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
18:25:36.500 7132 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod

**Comment by m417z** [comment]
```
18:25:35.685 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/46ED9E4BB32B434F98DF567B18D6B2E91/Taskbar.View.pdb
18:25:35.838 7132 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
```

The symbol file wasn't published by Microsoft right away. It's published now, you can see that the link now works:
https://msdl.microsoft.com/download/symbols/Taskbar.View.pdb/46ED9E4BB32B434F98DF567B18D6B2E91/Taskbar.View.pdb

That happens sometimes, more commonly with preview updates. You seem to have [update KB5027303](https://support.microsoft.com/en-us/topic/june-27-2023-kb5027303-os-build-22621-1928-preview-1ada2c0a-fa85-43f8-91c4-6ee13fdf278b) installed. To minimize such problems in the future, you might want to avoid preview updates.

The mod should work now on your system. Let me know if you need more help.
