### ISSUE TITLE
"Disable grouping on the taskbar" no longer working after I update Windhawk

### ISSUE THREAD

**Issue by waterbottlebottle** [ramensoftware/windhawk-mods#250]
First off, thank you so much for this mod, it's such a help for me.

I updated Windhawk for the first time in a long while, and the mod, but now "Disable grouping on the taskbar" isn't working for me. Any ideas of what I could try? Before the update it had been working fine for me.

**Comment by waterbottlebottle** [comment]
Update: after a lot of experimenting, I think there was a new conflict with Stardock's Start11 tool, which I also have installed on my machine.

I'm not sure if the new problem came from the Start11 update, or the Windhawk update, or the mod update.... I think based on order it was the Windhawk or mod update... but while it all used to work before, it no longer works with Start11 as I had it before.

The good news is, I told Start11 to stop "enhance taskbar" and added your "Taskbar Labels" mod, and that seems to more or less do the same thing and work now. Thanks!

**Comment by Tellinq** [comment]
That’s not from an update, some setting turned on in Start11.

Start11’s “enhanced taskbar” is merely adding a separate overlay over your actual taskbar. Since it’s an overlay, any changes that interact with the actual Windows 11 taskbar, such as Windhawk’s taskbar grouping mod, will not be reflected visually.

**Comment by m417z** [comment]
Seems to be an incompatibility with one of the Start11 options that has a workaround. Closing. Let me know if you need more help.
