### ISSUE TITLE
Feature request: For Middle click to close on taskbar mod: Add an option to kill window (bypass Do you want to save?)

### ISSUE THREAD

**Issue by n-src** [ramensoftware/windhawk-mods#255]
I would like for this mod to forcefully exit the application when I middle click on apps. I understand this might not be good as a default behavior for everyone, but I would like to see it implemented as an option.  if anyone can provide the code, please share. Thanks.

**Comment by m417z** [comment]
Added an option for it in version 1.0.7. Holding Ctrl while middle clicking will end the running task. The key combination can be configured or disabled in the mod settings.
