### ISSUE TITLE
"Disable grouping on taskbar" constantly resets icon groupings

### ISSUE THREAD

**Issue by derickso** [ramensoftware/windhawk-mods#259]
Open a program (like an image viewer) and it appears on right most position of taskbar

After a few seconds, the icon will reset position and group with the other image viewer icons

**Comment by m417z** [comment]
Is it Windows 10 or 11? Is the "Place ungrouped items together" option enabled? Can you post a video showing the bug?

**Comment by m417z** [comment]
The issue is perhaps the same as https://github.com/ramensoftware/windhawk-mods/issues/423, which is now fixed. If not, please provide more details.
