### ISSUE TITLE
Taskbar styler: Select active window button

### ISSUE THREAD

**Issue by ygoe** [ramensoftware/windhawk-mods#271]
How can I select the active window button in the taskbar for changing its style? It seems only possible to change the style of all buttons. I noticed that the active window is barely visible in the Windows 11 taskbar and would like to increase the focus of its background a bit.

I used UWPSpy (BTW, it says "WUP" at one point on the website) but couldn't see any useful information. Not comparable to Snoop or even a browser's DOM Inspector.

**Comment by m417z** [comment]
> How can I select the active window button in the taskbar for changing its style?

Currently, you can't, but want to try and make that possible in the future. It was previously asked [here](https://github.com/ramensoftware/windhawk-mods/issues/229), so closing as duplicate.

> Not comparable to Snoop or even a browser's DOM Inspector.

Yes, it's a very simple tool by an author who doesn't actually know much about UWP. But it's better than what was available before, which is nothing at all or maybe some textual logs.

> BTW, it says "WUP" at one point on the website

Fixed, thanks.
