### ISSUE TITLE
"Show all apps by default in start menu" by m417z never starts

### ISSUE THREAD

**Issue by huntermunts** [ramensoftware/windhawk-mods#281]
StartMenuExperienceHost.exe is never ran and the mod doesn't work on my system, I updated to 22H2 windows 11 a few days ago and wanted to find a fix for the way windows forces you to use their broken UI instead of defaulting to all apps, other mods on windhawk work fine and its only this mod. If I configured it wrong or if I need to escalate the privileges of windhawk let me know what steps to take, I did some research and didn't find any documentation.

**Comment by m417z** [comment]
I recently discovered that the mod doesn't work if Windhawk isn't installed at the default Program Files folder. This issue will be fixed in the next version. Where do you have it installed?

**Comment by huntermunts** [comment]
I installed windhawk on my D:\ drive at D:\Windhawk. I uninstalled windhawk and reinstalled in C:\Program Files and the mod works great. Thank you for the quick reply.
