### ISSUE TITLE
[Taskbar minimize/restore on scroll] Doesn't work if window isn't on current Virtual Desktop

### ISSUE THREAD

**Issue by HenryTheVacuum** [ramensoftware/windhawk-mods#295]
Not sure if intended, but at least an option to enable virtual desktop switching. Currently you have to revert back to the normal way of clicking taskbar items to restore/open if the app window is on a different virtual desktop.

**Comment by m417z** [comment]
@HenryTheVacuum can you explain what you mean with this issue? A video recording that demonstrates the problem will help. If an app window is on a different virtual desktop, then it's not accessible from the taskbar, not when clicking and not when scrolling.

**Comment by HenryTheVacuum** [comment]
For me, all windows from all desktops are in my taskbar. There is a native
Windows setting you have to enable.

**Comment by m417z** [comment]
Are you talking about virtual desktops, or about monitors? Is it this option?

![image](https://github.com/user-attachments/assets/3ebe62b0-1983-4f56-a082-12e1ef3ad7d9)

**Comment by HenryTheVacuum** [comment]
Virtual desktops only. I only have 1 monitor just to clarify.

**Comment by HenryTheVacuum** [comment]
Open the desktops view, win + tab, then right click on an app and select
view on all desktops

**Comment by m417z** [comment]
OK, so what's the problem? If I set "view on all desktops" for a window, then the window is visible on all virtual desktops. The title says "if window isn't on current Virtual Desktop". Can you post a video that demonstrates the problem?

**Comment by HenryTheVacuum** [comment]
[Virtual Desktop 1]
Windows Explorer
[Virtual Desktop 2]
Microsoft Edge

If I'm on Desktop 2, I cannot scroll restore/minimize the taskbar item for Windows Explorer.
If I'm on Desktop 1, I cannot scroll restore/minimize the taskbar item for Microsoft Edge.

**Comment by m417z** [comment]
Please post a video, I keep guessing but I don't know if that's what you mean.

https://github.com/user-attachments/assets/ee58531f-b309-440e-8984-37b0ad04619f

**Comment by HenryTheVacuum** [comment]
Sorry, it works if "view on all desktops" is enabled. It does not work if that is disabled.

**Comment by HenryTheVacuum** [comment]
https://github.com/user-attachments/assets/60f58078-5c08-49a5-84ad-243b06fcddd3

**Comment by m417z** [comment]
I don't think that what you're showing is possible in Windows, are you using a tool that customizes virtual desktops? Normally windows which are on different virtual desktops aren't visible on the taskbar.

**Comment by HenryTheVacuum** [comment]
![ApplicationFrameHost_pJ78qVz50L](https://github.com/user-attachments/assets/6df8591b-5fc4-45ce-aa44-23d465246ba6)

Windows 11 Home

**Comment by m417z** [comment]
Thanks, didn't know about this option. I can reproduce it.

**Comment by m417z** [comment]
Fixed in version 1.0.7.

**Comment by HenryTheVacuum** [comment]
Amazing, thx!
