### ISSUE TITLE
[Taskbar clock customization 1.2.1] Top/bottom line -> line spacing option like T-Clock (e.g. for slim height taskbars)

### ISSUE THREAD

**Issue by emp-00** [ramensoftware/windhawk-mods#296]
Loving Windhawk (!) but I have the following issue/suggestion concerning the mod "Taskbar clock customization 1.2.1" in combination with the mod "Taskbar height and icon size":

My Windhawk configuration:
- Running Win11 22H2 build 22621.2134 (latest as of today) and Windhawk v1.3.1 (with latest mods as of today)
- "Taskbar height and icon size" set to 34 px height and 16 px icon size - still larger than my Win10 config with 30 px taskbar height, but I'm sticking to the Winhawk mod slim size default sizes
- "Taskbar clock customization" is set to simply display two lines time+date, font Calibri with e.g. 16 pt (same issue with smaller sizes --> the line distance is always bigger than desired!)
- No other special configuration settings, using mod "Disable grouping on the taskbar" with default settings

Problem:
- I would like to have an option in the "Taskbar clock" mod to **modify the line spacing** to create a maximum slim clock design
- See below screenshots from my old Win10 setup using T-Clock-Redux 2.4.4, Line spacing e.g. -2 was possible there -> this is not yet possible with the Windhawk mods

As follows some reference screenshots:

1) Comparison Win10 T-Clock with my Winhawk config and clear problem visibility:
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/63d6cad3-146c-4fef-9077-b6db56db6d47)
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/156d5c16-2ce9-4be1-a2c4-617265754bdb)
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/1bca0f7b-4dc5-4e20-97a3-cb1c14f66c98)

2) My Windhawk mod settings:
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/b520445d-1795-4562-b85c-0a349f8bc402)
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/f1fd4ecd-8d46-4576-93ad-ae81d32bc2e0)
![image](https://github.com/ramensoftware/windhawk-mods/assets/60714349/212e3d99-ab71-45d3-b441-aed44d80c080)

Thanks for looking into this!! Questions? Shoot! :-)

**Comment by m417z** [comment]
Meanwhile, you can use [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler). Play with the Spacing property. Let me know if you need help with that.

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/5e012515-6a65-4cac-a2b6-8922272106eb)

**Comment by emp-00** [comment]
Thank you @m417z - I read the instructions but can't quite figure out how to correctly input the "Spacing" property in the "Taskbar Styler" mod Settings tab. Control Styles / Target = "**Windows.UI.Xaml.Controls.StackPanel**" and Styles = "**Spacing=-3**" does not work. Can you give me a hint?

**Comment by m417z** [comment]
For properly specifying the target, I had to make a small update to the mod. Update to Windows 11 Taskbar Styler v1.1.1, then use the following:

Target: `systemtray:DateTimeIconContent > Grid#ContainerGrid > StackPanel`
Style: `Spacing=-4`

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/aa2d4f1f-239b-4be0-91c5-15a345b49dcb)

**Comment by emp-00** [comment]
Excellent - this works like a charm in combination with the Taskbar clock customization mod! Problem solved, thank you very much!!!

**Comment by m417z** [comment]
This option was added in Taskbar Clock Customization v1.3, so you can now achieve it without Windows 11 Taskbar Styler.
