### ISSUE TITLE
[Taskbar clock customization 1.2.1] Settings not fully applied when starting windhawk.exe via autostart

### ISSUE THREAD

**Issue by emp-00** [ramensoftware/windhawk-mods#300]
I think I have found a small bug: 

- My PC has "windhawk.exe -tray-only" as shortcut in the autostart folder (in order to start up the tool with my saved settings)
- Problem: The **font size** of the top and bottom lines is not applied, meaning the font size stays in default windows size.
- Workaround: I only need to "touch" the taskbar clock with the mouse for a short time -> then the font size from my settings is also applied. No need to open the settings page, just touching the clock with the mouse is sufficient.

Expected behavior: All settings incl. the font size should be applied when starting windhawk.exe :-)

**Comment by m417z** [comment]
It's a known limitation. If the mod is loaded after the taskbar is created, you need to hover over the clock to apply the style. It's also mentioned in the settings. To avoid this problem, you can use the standard (non-portable) Windhawk version which starts before the taskbar is created.

**Comment by emp-00** [comment]
Thank you @m417z - understood. However, I need to use the portable Windhawk installation due to missing admin rights... But no problem: Thanks to Autohotkey I'm now executing this small script via autostart right after starting Windhawk. This moves the mouse very shortly to the screen corner which triggers Windhawk to update my clock settings and then the mouse returns to it's starting position. Cannot be noticed by the user and "Job done" :-)

`#Requires AutoHotkey v2
CoordMode "Mouse", "Screen"
MouseGetPos &MPosX, &MPosY ; Save current mouse position coordinates
MouseMove(A_ScreenWidth-40, A_ScreenHeight-20) ; Move the mouse to the bottom right corner of the primary screen -> activate/refresh Windhawk toolbar clock mod 
Sleep 10 ; Wait 10ms just to be safe, just a blink of an eye.
MouseMove(MPosX, MPosY) ; Move mouse back to saved position
ExitApp`

**Comment by emp-00** [comment]
@m417z : One more question --> On my system [Taskbar clock customization] works principally on all screens (multi-monitor setup with 1 primary and 2 secondary screens). However, the "trick" of touching the the taskbar clock with the mouse cursor only works on my **primary screen**: The clocks on all secondary screens don't apply my font size modifications. I tried touching the secondary taskbar clocks with the mouse cursor, but that does not work here. Any chance to get the settings applied to all taskbars? I must use the portable Windhawk installation, see above. Thanks for looking into this!

**Comment by m417z** [comment]
Done in Taskbar Clock Customization v1.3.
