### ISSUE TITLE
Generic "It doesnt work on Windows 11 23H2" report

### ISSUE THREAD

**Issue by koblue** [ramensoftware/windhawk-mods#318]
Windhawk no longer works on the 23H2 update

**Comment by Bec-de-Xorbin** [comment]
I think @koblue is referring to preview KB5030310 (OS Build 22621.2361) not 23H2 which is not even released yet. Maybe just symbols missing in this case (due to preview build)?

**Comment by R4mb4Z4mb4** [comment]
Same here. After updating Windows 11 to KB5030310, which is not yet the final W11 23h2 Update but has already a lot of those new features implemented, the Windhawk Mod "Taskbar height and icon size" entirely stopped working.

What I have tried:

Uninstalling Windhawk, including all config files and reinstalling both Windhawk and the Mod.
Multiple Restarts.

None of it worked. 

Sadly, I forgot to catch the log files and I reverted now back to the previous Windows 11 Version, so I uninstalled the new Update. Hence I can't get my hands on a log now. But I will do that later, to provide more technical information.

As a general question though: Any fixes for that in the pipeline?

Thanks in advance!

**Comment by VapidLinus** [comment]
I updated Windows today and some of the mods have stopped working.

These are the ones I use and have noticed no longer works:
- Taskbar minimize/restore on scroll
- Taskbar thumbnail reorder
- Disable grouping on the taskbar _(Windows has this inbuilt now, but it forces labels, which I don't want)_

> Windhawk v1.3.1 beta
> Version 22H2 (0S Build 22621.2361)

**Comment by ergaster-longus** [comment]
I updated Windows today and some of the mods have stopped working.

These are the ones I use and have noticed no longer works:

Disable grouping on the taskbar
Middle click to close on the taskbar
Taskbar height and icon size

Taskbar volume control still work.

**Comment by npf6** [comment]
Also updated Windows today. 

For me, taskbar groupings is working. However, Taskbar labels are not working (1.2.2)

Windhawk v1.3.1 beta

**Comment by Albotech77** [comment]
Also updated Windows today.

For me, taskbar groupings is working. However, Taskbar labels are not working (1.2.2)

Windhawk v1.3.1 beta

Thank you for creating Windhawk 🙏

**Comment by Car0lina5** [comment]
I updated today and realized that of the mods I use, "Taskbar Clock Customization" and "Taskbar minimize/restore on scroll" are not working.

**Comment by Car0lina5** [comment]
I updated today and noticed that the "Taskbar Clock Customization" mod is unfortunately not working.

**Comment by squareloop1** [comment]
Clock on secondary monitors is displaced and cropped down but fine on primary monitor in a multi monitor setup with the taskbar height and icon size mod.

**Comment by m417z** [comment]
@Car0lina5 Taskbar Clock Customization was just updated to v1.3.1, and it should be working with the new "Moment 4" update.

**Comment by Car0lina5** [comment]
@m417z Thank you very much! It's working perfectly now.

**Comment by R4mb4Z4mb4** [comment]
As I was just about to finally grab a log file in order to provide more input for why "Taskbar height and icon size" may not be working on the new Windows 11 KB5030310 Update, it all of a sudden started to work! 😁

@m417z Did you update this Mod as well or what happened?

**Comment by m417z** [comment]
Most taskbar-related mods didn't work on the day the update was published because it took time for Microsoft to publish debug symbols for it. Once published, the mods began working, no update to the mods was required.

The following mods became incompatible and got an update which fixes the incompatibility:
* Taskbar Clock Customization
* Taskbar minimize/restore on scroll
* Cycle taskbar buttons with mouse wheel

The [Taskbar Labels for Windows 11](https://windhawk.net/mods/taskbar-labels) mod is known to be compatible, and has [a dedicated issue](https://github.com/ramensoftware/windhawk-mods/issues/227).

I'm closing this issue. If there are any other incompatibilities or problems, please create a new issue.

**Comment by R4mb4Z4mb4** [comment]
> Most taskbar-related mods didn't work on the day the update was published because it took time for Microsoft to publish debug symbols for it. Once published, the mods began working, no update to the mods was required.
> 
> The following mods became incompatible and got an update which fixes the incompatibility:
> 
> * Taskbar Clock Customization
> * Taskbar minimize/restore on scroll
> * Cycle taskbar buttons with mouse wheel
> 
> The [Taskbar Labels for Windows 11](https://windhawk.net/mods/taskbar-labels) mod is known to be compatible, and has [a dedicated issue](https://github.com/ramensoftware/windhawk-mods/issues/227).
> 
> I'm closing this issue. If there are any other incompatibilities or problems, please create a new issue.

That makes sense! Thanks for the information and work!
