### ISSUE TITLE
[Bug report] <Taskbar Clock Customization> <Taskbar Labels for Windows 11> not working after update to Windows11(KB5030310)

### ISSUE THREAD

**Issue by HumanMus1c** [ramensoftware/windhawk-mods#319]
The Mods 
**Taskbar Clock Customization**
**Taskbar Labels for Windows 11**
not working anymore after update Windows11 September 26, 2023—KB5030310 (OS Build 22621.2361) Preview
[WindHawk] version 1.3.1beta

log file ↓
[DebugViewConsole 1.8.0.102.txt](https://github.com/ramensoftware/windhawk-mods/files/12746973/DebugViewConsole.1.8.0.102.txt)

**Comment by HebrewLantern** [comment]
I am also having the same issue on the same version.

**Comment by GameBurrow** [comment]
Can confirm same happening

**Comment by olluz** [comment]
I guess you already know @m417z, but just in case

**Comment by m417z** [comment]
Taskbar Clock Customization was just updated to v1.3.1, and it should be working with the new "Moment 4" update. I'll look at the Taskbar Labels mod soon.

**Comment by m417z** [comment]
**Taskbar Labels for Windows 11** v1.1.4 fixes the basic functionality with the new update. It still has some unsolved incompatibilities, so if you encounter any, please open a new issue.

Since both mods now work, I'm closing the issue.
