### ISSUE TITLE
[Taskbar height and icon size] Displaced clock on secondary monitors on a multi monitor taskbar

### ISSUE THREAD

**Issue by squareloop1** [ramensoftware/windhawk-mods#323]
With `Taskbar height and icon size` mod by @m417z having a 3 monitor setup everything is working fine on the taskbar of the primary monitor. On the secondary monitors the clock is displaced and offset to the bottom and looks like it doesnt have the full opacity and is not clickable.

Primary monitor:
![image](https://github.com/ramensoftware/windhawk-mods/assets/36505652/60a3bf0e-3327-4ea5-b987-007cbc1cac17)

Secondary monitor:
![image](https://github.com/ramensoftware/windhawk-mods/assets/36505652/819ce015-fb12-4ef4-9865-6c6dd71e03f5)

Mod settings:

Icon size: 20
taskbar height: 38
taskbar button width: 44

**Comment by suntoryslap** [comment]
same issue 
![image](https://github.com/ramensoftware/windhawk-mods/assets/147771925/efa0557f-adcc-48c0-a70f-6e281327fa59)

**Comment by m417z** [comment]
Fixed in version 1.2.1 of the mod.
