### ISSUE TITLE
Taskbar Labels for Windows 11 - Overflow bug

### ISSUE THREAD

**Issue by crystalfunky** [ramensoftware/windhawk-mods#330]
Hello,

I updated the mod mentioned in the title to the newest version 1.1.4 and get an overflow bug now.
The items in the taskbar stretch over the icons and the normal clock in the right corner.

@m417z

**Comment by m417z** [comment]
Please post logs and a screenshot. For log collection, refer to the troubleshooting page.

**Comment by materro** [comment]
Open tasks do not move to the left from the Start button 👀
![image](https://github.com/ramensoftware/windhawk-mods/assets/117664996/decfe82a-0dc8-4f5e-bc8e-2312789db1ba)
`{"taskbarItemWidth":140,"runningIndicatorStyle":"left","progressIndicatorStyle":"fullWidth","fontSize":11,"leftAndRightPaddingSize":10,"spaceBetweenIconAndLabel":8,"labelForSingleItem":"%name%","labelForMultipleItems":"[%amount%] %name%"}`

**Comment by m417z** [comment]
Please post debug logs.

* Disable the mod.
* Go to the mod's Advanced tab.
* Set **Debug logging** to **Detailed debug logs**.
* Click on **Show log output**.
* Enable the mod.
* Verify that the mod doesn't work, copy the log and post it here.
* Set **Debug logging** back to **None**.

**Comment by materro** [comment]
[whlog.txt](https://github.com/ramensoftware/windhawk-mods/files/12796301/whlog.txt)

**Comment by materro** [comment]
Version `1.1.3` was working fine 👍 Downgrade is possible?

**Comment by crystalfunky** [comment]
> Version `1.1.3` was working fine 👍 Downgrade is possible?

That was my question to @m417z  as well.

**Comment by m417z** [comment]
Thank you for the report and the information. I was able to reproduce and fix the issue. Please try Taskbar Labels for Windows 11 version 1.1.5.
