### ISSUE TITLE
Mod：Taskbar Labels for Windows 11 has a bug

### ISSUE THREAD

**Issue by GRAINALCOHOL** [ramensoftware/windhawk-mods#335]
I found this issue in version 22621.2361 of 22H2 in Windows 11, where the mod does not work when the user only has one window open, and the mod becomes normal again when two or more windows are opened

**Comment by Reggie521** [comment]
Same issue in 22621.2428. Also, certain taskbar icons (like Firefox) are flickering with the mod enabled.

**Comment by clover-yan** [comment]
@m417z Met the issue on 22621.2506. The label will disappear, and the padding on left will be wider thannon the right inside the button (not shown in the screenshot, but can be found when hovering). Especially occured when taskbar is nearly filled.

![Screenshot](https://github.com/ramensoftware/windhawk-mods/assets/56215525/d4a19c88-95f9-4e6d-8304-0a3a4ad6c617)

**Comment by Reggie521** [comment]
I'm seeing this same bug in Windows 11 23H2, build 22631.2715

![taskbar1](https://github.com/ramensoftware/windhawk-mods/assets/35973596/d6c0d8b9-e425-475b-81db-3bf9e7fbd4a3)
![taskbar2](https://github.com/ramensoftware/windhawk-mods/assets/35973596/b1d1e64f-e550-4188-a1dd-5885946f2756)

**Comment by m417z** [comment]
Should be fixed in version 1.2 of the mod.

**Comment by Reggie521** [comment]
That fixes one problem, but now I'm not seeing titles for open windows in the taskbar.

![taskbar3](https://github.com/ramensoftware/windhawk-mods/assets/35973596/923d4589-6cd0-4e9a-97e4-7e34f470d883)

**Comment by m417z** [comment]
Should be fixed in v1.2.1, which causes "Combine taskbar buttons and hide labels=Always" to be equivalent to "Never".
