### ISSUE TITLE
Bug Report: Windhawk mods not working with the new Windows Update(KB5030651, KB5030654)

### ISSUE THREAD

**Issue by miguel-henrique** [ramensoftware/windhawk-mods#343]
I just updated my Windows today (11/10/23) and the taskbar setting is not working. 

Mod Taskbar height and icon size

`DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
10:04:55.899 7864 explorer.exe  [WH] [taskbar-icon-size] [807:Wh_ModInit]: >
10:04:55.899 7864 explorer.exe  [WH] [taskbar-icon-size] [573:HookSymbols]: Couldn't resolve all symbols from cache
10:04:56.773 7864 explorer.exe  [WH] [taskbar-icon-size] [578:HookSymbols]: Wh_FindFirstSymbol failed
`

**Comment by theFireProject** [comment]
I have the same problem. Mods work you disable the **Taskbar Height and Icon Size** mod.

**Comment by m417z** [comment]
The symbols were published by Microsoft, so I'm closing this issue. For other problems, please open a new issue.

@theFireProject please create a new issue and attach debug logs as said in the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work
