### ISSUE TITLE
Mute Unmute by Taskbar Double Click

### ISSUE THREAD

**Issue by zFruitSalad** [ramensoftware/windhawk-mods#348]
A feature that I used very often with 7+TT was double-clicking the taskbar to mute and unmute audio from the computer.  I searched for a similar utility but there isn't anything nearly as neat, compact, or efficient as Taskbar Tweaker.  I look forward to being able use that in the near future.

**Comment by m417z** [comment]
Now possible with the [Click on empty taskbar space](https://windhawk.net/mods/taskbar-empty-space-clicks) mod.
