### ISSUE TITLE
[Bug] Taskbar Labels for Windows 11

### ISSUE THREAD

**Issue by Reggie521** [ramensoftware/windhawk-mods#349]
After updating Windows (version 22621.2428), taskbar icons are flickering with the mod enabled and 'Taskbar item width' set any higher than 60 (I had mine at 144). The debug log shows the flickering is caused by a constant reloading loop.

https://pastebin.com/raw/efGXfKWV

**Comment by Reggie521** [comment]
Okay, I figured it out. I had the new 'Combine taskbar buttons and hide labels' in Settings set to "Never". Switching back to "Always" fixed everything.

**Comment by Dook1** [comment]
@m417z [57m] Could you please fix this bug "Combine taskbar buttons and hide labels"=Never ?
