### ISSUE TITLE
[Taskbar minimize/restore on scroll v1.0.5] Do not work

### ISSUE THREAD

**Issue by GlopGlop31** [ramensoftware/windhawk-mods#352]
Windows 11 Pro (x64) 22000.2482 (21H2)
Windhawk v1.3.1 beta
|m417z] Taskbar minimize/restore on scroll v1.0.5

Good morning,
It was following a new reinstallation of Windows 11 that "Taskbar minimize/restore on scroll" no longer worked.
 Attached debug info:
  I use a translation log :-)
 Thanks for the work
 A link in the app for financial support... an idea...

[BUREAU (DebugView 22102023).LOG](https://github.com/ramensoftware/windhawk-mods/files/13064016/BUREAU.DebugView.22102023.LOG)

**Comment by m417z** [comment]
Hi, that's a known limitation. As the mod description says:

> Only Windows 11 version 22H2 or newer is currently supported.

**Comment by GlopGlop31** [comment]
Hi, update done 🤐😉
Everything works... Thanks...
By chance information on the version (10/26/2023) KB5031455 (OS Build 22621.2506) Preview... 🙄
Good evening 😉
Sincerely 🙏
