### ISSUE TITLE
Taskbar Clock Customization does not work on 22622.575

### ISSUE THREAD

**Issue by Tellinq** [ramensoftware/windhawk-mods#37]
I've seen that someone else in Discussions had this issue on 22621 which is similar to 22622 with the key difference where Insider features are enabled, but for them it seems to be fixed.

Unfortunately for me, enabling this mod does not work, despite being on 1.0.3.

Tried Restarting explorer.exe, restarting the computer, re-toggling the mod. None of which worked. I also did disable other modifications in the case that anything else could be interfering with this one - doesn't seem to be the case

**Comment by m417z** [comment]
Please try the following:

* Open Windhawk.
* Disable the Taskbar Clock Customization mod.
* Fork the mod.
* Enable logging.
* Click on Show Log Output.
* Click on Compile Mod.

You should see log output at the bottom of the window. Send me the log that you're getting. Let me know if you need help with one of the steps.

**Comment by Tellinq** [comment]
This was what I ended up getting. Just stops at Missing symbol: 1
![image](https://user-images.githubusercontent.com/59412384/186158374-67685b9d-0f82-4f9a-9f4b-f122daf7dfd9.png)

**Comment by m417z** [comment]
OK, can you please upload the following file from your computer?

> C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll

**Comment by Tellinq** [comment]
Uploaded that DLL in a zip: [Taskbar.View.zip](https://github.com/ramensoftware/windhawk-mods/files/9410333/Taskbar.View.zip)

**Comment by m417z** [comment]
I see why it doesn't work, one of the functions was inlined.
Try the following fix and let me know if it works. If it is, I'll update it for all users.
https://gist.github.com/m417z/f433e92448a29288e0e4320b6f416fb3

To test it, edit your fork (if no longer editing), replace the code with the code above, and compile it.
If it doesn't work, tell me what you see in the log as you did before.

**Comment by Tellinq** [comment]
![image](https://user-images.githubusercontent.com/59412384/186276133-cdebd08d-ec24-4a25-9ffe-d737200daf0a.png)
Looks like it's working now!

**Comment by m417z** [comment]
Great, I've updated the mod to version 1.0.4.
