### ISSUE TITLE
"Taskbar height and icon size" issues on secondary monitor with "Automatically hide the taskbar" enabled

### ISSUE THREAD

**Issue by HighSoldierr** [ramensoftware/windhawk-mods#380]
Hi,

I installed the "Taskbar height and icon size" mod but now my taskbar on my secondary monitor is moved up a little. The problem seems solved when i disable the "Automatically hide the taskbar" function.

![image](https://github.com/ramensoftware/windhawk-mods/assets/151577464/b37d4016-2206-44db-8d28-05ac42438b40)

@m417z

**Comment by m417z** [comment]
Fixed in Taskbar height and icon size v1.2.2.

**Comment by HighSoldierr** [comment]
Yup, seems to be fixed. You're awesome!!
