### ISSUE TITLE
Eradicate immersive menus mod does not affect narrator

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk-mods#382]
The Eradicate Immersive Menus mod does not affect the Windows Narrator context menu.

**Comment by m417z** [comment]
Please tag the mod author as asked in the issue template.

**Comment by Anixx** [comment]
Author: aubymori

**Comment by m417z** [comment]
Next time tag with the `@` symbol, thanks.
@aubymori FYI

**Comment by aubymori** [comment]
Will look into when I get home.
