### ISSUE TITLE
Case systemtray/SystemTray, taskbar/Taskbar in "Windows 11 Taskbar Styler"/UWPSpy

### ISSUE THREAD

**Issue by Dook1** [ramensoftware/windhawk-mods#386]
Why this difference?

**Comment by m417z** [comment]
The difference stems from the fact that UWPSpy gets the class names via the WinRT API, while the mod uses the XAML notation (as can be seen in the XAML files, [for example these files](https://gist.github.com/m417z/ad0ab39351aca905f1d186b1f1c3d8c7) that's also mentioned in the mod's description).

The mod was created before UWPSpy. I agree that it's confusing, and I want to look into making the mod accept the UWPSpy notation as well.

**Comment by m417z** [comment]
Windows 11 Taskbar Styler v1.2, the new mod version, accepts both variants. For example, both `taskbar:TaskListButton` and `Taskbar.TaskListButton` can be used.
