### ISSUE TITLE
[taskbar-button-click] Closing all tasks instead of the clicked one (using system "never combine taskbar buttons")

### ISSUE THREAD

**Issue by materro** [ramensoftware/windhawk-mods#388]
Hi 👋
When I middle click on app it close all it's instances - not the clicked one.

### Windows 11 settings:
![image](https://github.com/ramensoftware/windhawk-mods/assets/117664996/6f3ae7c6-c37e-41c7-bb91-056cfdac6027)
Version 22H2 (OS Build 22621.2715)

### Mod settings:
![image](https://github.com/ramensoftware/windhawk-mods/assets/117664996/156aba6b-6c33-4ee3-b42c-e84a59c2b9f8)
Changing "behavior" settings do nothing.

### Steps:

1. Two or more instances opened:
![image](https://github.com/ramensoftware/windhawk-mods/assets/117664996/5157da9c-e9f0-47ca-b441-577ef02222e7)

2. Middle click on right one

3. All instances closed:
![image](https://github.com/ramensoftware/windhawk-mods/assets/117664996/34223f41-4fda-42f1-9dc5-12b067ff97b2)

**Comment by m417z** [comment]
Hi, fixed in Middle click to close on the taskbar v1.0.5.
