### ISSUE TITLE
Clock customization wont make any difference on Win 11 [Versión 10.0.22622.575]

### ISSUE THREAD

**Issue by SullyPanda76cl** [ramensoftware/windhawk-mods#39]
Clock stays the same

[Img](https://i.imgur.com/LreOF7X.png)

**Comment by m417z** [comment]
Please try the following:

* Open Windhawk.
* Disable the Taskbar Clock Customization mod.
* Fork the mod.
* Enable logging.
* Click on Show Log Output.
* Click on Compile Mod.

You should see log output at the bottom of the window. Send me the log that you're getting. Let me know if you need help with one of the steps.

**Comment by m417z** [comment]
Looks like this issue: https://github.com/ramensoftware/windhawk-mods/issues/37
Please update to v1.0.4 and let me know whether it fixes the problem for you.

**Comment by m417z** [comment]
Closing since it's probably fixed. If not, please let me know.
