### ISSUE TITLE
Build 22622.586 seems to have broken a majority of mods

### ISSUE THREAD

**Issue by Tellinq** [ramensoftware/windhawk-mods#40]
Windows just released a new Insider build for Dev and Beta which provides a bunch of bug fixes. Unfortunately that seems to have also broken the following mods completely:
- Taskbar Labels for Windows 11
- Taskbar Clock Customization
- Large Taskbar Icons
- Middle click to close on the taskbar
- Taskbar Thumbnail Reorder (I actually meant to report this earlier since this didn't always work for me but wanted to mention since this is also on the list)
- Disable grouping on the taskbar
- Show all apps by default in start menu

I have tested the following that still work:
- Slick Window Arrangement
- Chrome/Edge scroll tabs with mouse wheel

I did fork the mods that didn't work to see what the logs would show. All off them seem to just be hanging on explorer.exe, which would make since since Windows did a bunch of bug fixes for File Explorer
![image](https://user-images.githubusercontent.com/59412384/186550066-f19039ed-a939-4796-a321-d052be41337c.png)
![image](https://user-images.githubusercontent.com/59412384/186550568-203d403a-1755-4380-b4ff-439ef9899c8e.png)
![image](https://user-images.githubusercontent.com/59412384/186550949-e3d49460-0000-43b3-aa61-b54eef66b69e.png)

Disable Grouping logs seems to be trying to get new App IDs but still fails to separate applications from groups
![image](https://user-images.githubusercontent.com/59412384/186550894-4e87e4b6-9c29-410e-9768-94b74b468d06.png)

Like last time when Clock Customization didn't work for me in Issue #37 I ended up getting Missing Symbols. Same goes with Thumbnail Reorder
![image](https://user-images.githubusercontent.com/59412384/186551093-091c49ff-d977-4b1b-90b3-c2540dd313f3.png)
![image](https://user-images.githubusercontent.com/59412384/186551140-cfd361a1-3606-45a7-b2c8-396058b740bf.png)

I'm not sure if this will be required but I uploaded these files since I noticed they were updated an hour ago and since these were requested in previous reports (primarily Tasbar.View and FileExplorerExtensions)
![image](https://user-images.githubusercontent.com/59412384/186551436-6c7e9a9c-00de-4dc8-b06b-3f02cdaa5201.png)
[Client Core DLL files.zip](https://github.com/ramensoftware/windhawk-mods/files/9420381/Client.Core.DLL.files.zip)

Let me know anything else I should do or upload.

**Comment by Tellinq** [comment]
Ok... I just checked this morning and all the modules that worked before work fine now. Not sure what the deal was yesterday but so far so good. I'll see what happens today

**Comment by m417z** [comment]
All these mods rely on symbols which are downloaded from the Microsoft symbol server. What could happen is that Microsoft only published the symbols after releasing the build, and so the mods couldn't initialize properly at the first time, but it all worked after restarting later when the symbols were already available.

Regarding handling symbol unavailability - in general, it's possible to implement the mods such that they won't depend on symbols, but it makes the development more difficult and the code prone to breakage after updates. For now, I'm good with requiring symbols.

Regarding diagnostics, that's something I'd certainly want to improve. If symbols are missing, I'd like to convey that to the user without requiring to enable logs with complex steps. And if symbols are being downloaded, I'd like the user to see that that's what's happening. These improvements are on my list.
