### ISSUE TITLE
Taskbar Thumbnail Reorder not work for label on newer Win10

### ISSUE THREAD

**Issue by Cirn09** [ramensoftware/windhawk-mods#403]
Newer Windows 11 add taskbar option "Merge taskbar and hiden label"(I use Chinese version Windows, and I don't know English verison option name...). After setting it to "Never", Taskbar Thumbnail Reorder will only work for thumbnail but label (or Button?) not work (thumbnail reordered but labal keep origin order)

I don't it is BUG or FEATURE, because this mod named Taskbar **Thumbnail** Reorder, seems should not work for labal : )

**Comment by kwyntes** [comment]
Not sure if the original issue was about Windows 10 or 11, but the same thing happens when using Explorer Patcher in Windows 11 to re-enable the Win10-style taskbar.

**Comment by kwyntes** [comment]
Ah, I thought it'd be related since it happens on Win11 only. I did enable the option to customise the old taskbar in the mod's settings - without it I wouldn't have been able to reorder the thumbnails anyway.  
Should I open a new issue for this?

**Comment by m417z** [comment]
@kwyntes yes please.

**Comment by m417z** [comment]
Implemented in version 1.0.4 of the mod.
