### ISSUE TITLE
Classic Explorer Navigation Bar not working after latest insider updates

### ISSUE THREAD

**Issue by queenbiscuit311** [ramensoftware/windhawk-mods#406]
Same issue as #398, but I thought I'd make a specific issue for this mod since that one's all encompassing.

The classic explorer navigation bar mod (made by @m417z) was fully working before my system updated today, but now it seems to have stopped working after Windows 11 23H2 insider build 22635.2776.

Attached are the debug logs from the mod:

[modlog.txt](https://github.com/ramensoftware/windhawk-mods/files/13520173/modlog.txt)

**Comment by queenbiscuit311** [comment]
I did not code block that correctly

**Comment by m417z** [comment]
From the [Troubleshooting page](https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work):

> If the log contains the `HTTP_STATUS_NOT_FOUND` error, debug symbols are unavailable. Microsoft doesn't publish debug symbols for some Windows builds, or publishes them with a significant delay. This often occurs with preview builds (Canary, Dev, Beta, or Release Preview builds). For better compatibility with Windhawk, it's best to avoid preview Windows builds.

So this problem is not specific to this mod. Let's track that at https://github.com/ramensoftware/windhawk-mods/issues/398.
