### ISSUE TITLE
[Taskbar Labels] Last update problem to hide label

### ISSUE THREAD

**Issue by mateusfn98** [ramensoftware/windhawk-mods#409]
I used to hide the taskbar label with this mod, but I can't remove it with the last update.

I already remove the label from here:
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/ef1ec1f3-1eec-4b0e-a1bb-176d83037ee5)
But it doesn't work.

I tried to set the font size to '0', which works, but I got an error and needed to put size '1'.

This is my taskbar now:
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/89a5de98-de9c-40a9-8a48-3567cc195822)

**Comment by m417z** [comment]
I'll add an option for this in the next update. For a temporary solution see https://github.com/ramensoftware/windhawk-mods/discussions/404.

**Comment by mateusfn98** [comment]
I reactivate the Disable grouping mod and deactivate the native disable group option (responsible for showing the label).
I'm using the Taskbar Style mod with Rectangle#RunningIndic for the running indicator.

A switch button in the Taskbar Labels mod to remove the taskbar label would be awesome.

Another suggestion is to remove the 'Taskbar height and icon size'. Including the icon size/button width option in the 'Taskbar Labels' mod (maybe renaming to 'Taskbar Item Style', because the icon size/button affects the items from the taskbar) and the height option in 'Taskbar Style' mod.
