### ISSUE TITLE
[Taskbar height and icon size] Maximized windows leave a gap

### ISSUE THREAD

**Issue by techswede** [ramensoftware/windhawk-mods#413]
Full screen Not working leaves a gap. Seems that hight 48 is default on folders etc in full screen. If i choose 48 it's flush.
![windhawk tbhaisjpg](https://github.com/ramensoftware/windhawk-mods/assets/84215970/e036ce75-cbff-42dc-a9d8-ea568d7cb3e6)

Mod: Taskbar height and icon size v.1.2.2
OS Win 11 pro 1920x1080

![full screen not working](https://github.com/ramensoftware/windhawk-mods/assets/84215970/53ddfa97-67e2-4314-a790-1cf3d7f3b462)

**Comment by techswede** [comment]
Did find a temp solution. Change resolution to nearest lowest (1760x990) and back to 1920x1080 solved the problem. I have Not restart my computer yet to see if that solved this issue permanatly.

**Comment by techswede** [comment]
I can confirm that the issue was solved by changing resolution mentioned before. 
But the initial issue still needs to look into

**Comment by m417z** [comment]
Did you see the issue only once, or did it happen multiple times after the mod was installed? Did it happen after a restart?

**Comment by techswede** [comment]
Got it issue back yesterday after installed KB5033375 and did a restart. I had to change resolution again. After that no more problem. I have restart like 3-4 times thereafter.

**Comment by m417z** [comment]
Let me know if the issue returns. It will be especially helpful to have a way to reproduce the problem. Otherwise, it's quite challenging for me to understand and fix it.

**Comment by m417z** [comment]
I looked at it, and it looks like a Windows bug. It can also be seen when taskbar auto-hide is enabled - maximized windows don't occupy the whole screen as they should, and changing the resolution fixes it. I'll try to find a workaround, but in case I won't find anything, hopefully Microsoft will fix it in one of the next updates.

**Comment by techswede** [comment]
Today when i startup my computer and windows 11 the taskbar was in correct height but icons was not in correct width. Also the maximized was not ok (gap). I did change the taskbar button width from 32 to 36 and saved. Change it back to 32 and saved and then logged out windows. When i logged in again all was OK again.
