### ISSUE TITLE
[Taskbar Labels for Windows 11] Problem with new -1 option.

### ISSUE THREAD

**Issue by mateusfn98** [ramensoftware/windhawk-mods#418]
Using the new -1 option with native windows 11 disable grouping, this is what happens:
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/e2bb1b28-b5bc-48f0-8756-f45bb9443983)
The items use the same "item space" and do not show both on the taskbar, the expected result is:
![image](https://github.com/ramensoftware/windhawk-mods/assets/74764525/54343450-e8e3-473b-befb-e2ec2d3135df)

It would be better not to show the taskbar label if font size = -1

But everything is okay when using the 'Disable grouping on the taskbar' mod, it is just a minor bug report.

I found it when you updated 'Taskbar Thumbnail Reorder' and I was trying to use the native disable group to test.

**Comment by m417z** [comment]
It works as intended, but I agree that adding an option to keep items uncombined and without labels can be useful. Changed from a bug report to an enhancement.

**Comment by mateusfn98** [comment]
After some research, I finally did it :DD

Target: TextBlock#LabelControl
Styles: Visibility=Collapsed

**Comment by m417z** [comment]
Combining with labels is now possible in version 1.3.
