### ISSUE TITLE
[Disable grouping on the taskbar] WSLg programs keep reapearing at the end after (un)focus

### ISSUE THREAD

**Issue by Patrick-Beuks** [ramensoftware/windhawk-mods#423]
@m417z 
**Description**
programs run on WSL through WSLg reappear at the end of the taskbar as if they are just opened after you unfocused or focus the program.

If you focus between other programs this behavior is not seen

**Technical information**
Running on Windows 11.
This behavior is seen with any combination of options in the settings.

**Reproduction steps**
  1. Open a WSLg program (konsole was used for the attached log)
  2. Assuming the program opened as focused program, select another open program.

Result:
- Program icon has a little bounce as if it where just opened.
- If program was not already last program it is now.

Expected:
- Program icon has no additional animation
- Program stays at the same position in the taskbar

**Workaround**
It is possible to add `msrdc.exe` to *Excluded programs*, but this would group WSLg application of the same kind.

**Log**
Steps taken:
 1. Enable mod
 2. Search start menu for "Konsole"
 3. Select "Konsole (Ubuntu)" -> Program opens and is in focus
 4. Select Windhawk -> Konsole icon bounces
 5. Select another program -> Icon does not bound
 6. Select Konsole -> Icon bounces
 7. Select Windhawk to disable mod and logging again (-> Icon bounces)

[reappering-icon-debug.log](https://github.com/ramensoftware/windhawk-mods/files/13661815/reappering-icon-debug.log)

**Comment by Aleksanderis** [comment]
I think it's a general issue, related not only to WSLg. I observe similar behaviour for example with Rider and Vivaldi browser, when I have more than one window of them opened + multi-monitor setup. However it's relevant for all applications with multiple windows opened.

This is how it works under normal conditions, everything is good:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/086d69a1-85e7-4825-a812-84fd10371391)

Then I lock my pc, monitors goes to sleep (it might be also important), and after I unlock PC I see this - all multi-windowed apps are moved to the end of the taskbar, so I need to rearrange everything manually everytime:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/98751ff0-0812-48dc-9c42-8544404d4728)

More apps proving it's absolutely same with all applications appearing at the end of the taskbar:
![image](https://github.com/ramensoftware/windhawk-mods/assets/2393205/dd966efd-2dd1-4900-83f2-48cc357dc7c3)

**Comment by Aleksanderis** [comment]
@m417z any clues about this one? I think it can be quite easily reproduced. It's not something really critical, but still a bit annoying. :)

**Comment by m417z** [comment]
@Patrick-Beuks thanks for the detailed report, should be fixed in version 1.3 of the mod.
@Aleksanderis please try your scenario with the new version. If the issue wasn't fixed, please open a new issue.

**Comment by Patrick-Beuks** [comment]
1.3 fixed it for me after reopening relevant windows.

Thank you for the quick fix

**Comment by Aleksanderis** [comment]
@m417z
Sorry for the late reply, but yes, seems like my issues was a different one after all. I'm still able to reproduce it.
I opened a separate issue - #461
