### ISSUE TITLE
HELP - Task Labels for Windows 11 v1.2.2 no combined same app in taskbar

### ISSUE THREAD

**Issue by rodhack** [ramensoftware/windhawk-mods#425]
Hi. With version 1.2.2 of Task Labels for Windows 11 the windows of the same application are no longer combined in the taskbar.

With version 1.2.1 this did not happen. How can I reinstall this version?
![taskbar_label_windows11_1 2 2](https://github.com/ramensoftware/windhawk-mods/assets/40393967/ae5d1fac-7901-4599-9139-5e57a920d6ec)

Do you know this problem? What can I do?

{"taskbarItemWidth":85,"runningIndicatorStyle":"centerFixed","progressIndicatorStyle":"sameAsRunningIndicatorStyle","fontSize":12,"leftAndRightPaddingSize":10,"spaceBetweenIconAndLabel":8,"labelForSingleItem":"%name%","labelForMultipleItems":"[%amount%] %name%","minimumTaskbarItemWidth":0}

Thank you.

**Comment by m417z** [comment]
The reason for the difference is that previous versions of the mod added the labels manually, while newer versions rely and improve upon the native Windows implementation.

You can revert to v1.1.5, but note that it has some bugs in newer Windows versions. You can get it here:
https://github.com/ramensoftware/windhawk-mods/blob/4a1778822b1ce783729ec3fde550d59fdc7ce547/mods/taskbar-labels.wh.cpp

To install it, disable the existing labels mod, then click the bottom right button to create a new mod, replace the code with the content from the link above, click "Compile Mod", then "Exit Editing Mode".

**Comment by rodhack** [comment]
I have already applied the indicated solution and it works. Thank you very much! :)

I don't understand why in the new version if you have only changed the native Windows labels, it doesn't combine the windows of the same application. 

Do you expect to be able to combine them in future versions?

Chears

**Comment by m417z** [comment]
> I don't understand why in the new version if you have only changed the native Windows labels

Because this solution is less buggy and less likely to break in the future.

> Do you expect to be able to combine them in future versions?

I spent some time on it, but it's not trivial. I'll give it another try someday.

**Comment by rodhack** [comment]
Ok. Thank you for your help and time! :)

**Comment by m417z** [comment]
Combining with labels is now possible in version 1.3.

**Comment by rodhack** [comment]
Hi, I am testing version 1.3.2 of Taskbar Labels for Windows 11” and as you can see it does not group the applications in the taskbar:

[cid:0c0ca4f8-7055-4f45-a59d-443dee38f227]

While version 1.1.5, which I have offline, works correctly:

[cid:eca06c3f-08a4-48d8-bb02-52f0d2cbc4bc]

I don't know if it has been corrected and I am missing something to configure on my side.

Best regards.

________________________________
De: Michael Maltsev ***@***.***>
Enviado: sábado, 28 de septiembre de 2024 17:43
Para: ramensoftware/windhawk-mods ***@***.***>
Cc: rodhack ***@***.***>; Author ***@***.***>
Asunto: Re: [ramensoftware/windhawk-mods] HELP - Task Labels for Windows 11 v1.2.2 no combined same app in taskbar (Issue #425)


Combining with labels is now possible in version 1.3.

**Comment by m417z** [comment]
Hi @rodhack, images weren't posted properly because you commented through email. Post them on GitHub instead.

Also, did you change the mod's settings as following?

![image](https://github.com/user-attachments/assets/827dd4be-8c74-4440-989a-da662cc14c9a)

**Comment by rodhack** [comment]
Hi, I had not changed that setting. Now it works correctly, thank you very much for your help and patience. 🙂
________________________________
De: Michael Maltsev ***@***.***>
Enviado: lunes, 21 de octubre de 2024 10:28
Para: ramensoftware/windhawk-mods ***@***.***>
Cc: rodhack ***@***.***>; Mention ***@***.***>
Asunto: Re: [ramensoftware/windhawk-mods] HELP - Task Labels for Windows 11 v1.2.2 no combined same app in taskbar (Issue #425)


Hi @rodhack<https://github.com/rodhack>, images weren't posted properly because you commented through email. Post them on GitHub instead.

Also, did you change the mod's settings as following?

image.png (view on web)<https://github.com/user-attachments/assets/827dd4be-8c74-4440-989a-da662cc14c9a>
