### ISSUE TITLE
[taskbar-grouping] Pinned icons and running windows are always separate icons

### ISSUE THREAD

**Issue by ygoe** [ramensoftware/windhawk-mods#454]
Have I missed something? After upgrading this mod to v1.3, the pinned Firefox icon and the running window are always two separate taskbar icons. I guess that shouldn't be the case. The running window always replaced the pinned icon, I checked the setting, and it still doesn't work as expected.

Same problem for Thunderbird.

Works (as single icon) for Notepad++, VSCode, MS Word 2016 and others.

**Comment by m417z** [comment]
I could reproduce the bug, it should be fixed in version 1.3.1.
