### ISSUE TITLE
Middle click to close on the taskbar can' work

### ISSUE THREAD

**Issue by Anivie** [ramensoftware/windhawk-mods#465]
@m417z 

After installing patch KB5034123, I was surprised to find that this plugin  no longer works, instead, middle-clicking now opens a new instance.

**Comment by ergaster-longus** [comment]
+1 it's not working for me after the update today

**Comment by ttodua** [comment]
with ExplorerPatcher, no-grouping taskbar icons, and after update it does not work for me too.

**Comment by ergaster-longus** [comment]
i'm restart windhavk and now it work for me

**Comment by m417z** [comment]
Similar to #464. As with [one of the previous updates](https://github.com/ramensoftware/windhawk-mods/issues/318#issuecomment-1741725866):

> Most taskbar-related mods didn't work on the day the update was published because it took time for Microsoft to publish debug symbols for it. Once published, the mods began working, no update to the mods was required.
> [...]
> I'm closing this issue. If there are any other incompatibilities or problems, please create a new issue.
