### ISSUE TITLE
[taskbar-grouping] broken after latest windows update (KB5034123)

### ISSUE THREAD

**Issue by soredake** [ramensoftware/windhawk-mods#466]
Probably this one KB5034123

**Comment by ergaster-longus** [comment]
+1 it's not working for me after the update today

**Comment by boyangma** [comment]
Apparently, the KB5034123 is a bomb.

**Comment by mayureshs** [comment]
+1 taskbar grouping is not working on KB5034123
![image](https://github.com/ramensoftware/windhawk-mods/assets/1014702/b12904e6-7121-471b-aa93-b50f587dac35)

**Comment by ergaster-longus** [comment]
i'm restart windhavk and now it work for me

**Comment by mayureshs** [comment]
Worked after restart. Thanks!

**Comment by samgabriel** [comment]
+1 worked after restarting windows. 

Restarting windhawk by itself or disabling and renabling the module did not work.

**Comment by m417z** [comment]
Similar to #464. As with [one of the previous updates](https://github.com/ramensoftware/windhawk-mods/issues/318#issuecomment-1741725866):

> Most taskbar-related mods didn't work on the day the update was published because it took time for Microsoft to publish debug symbols for it. Once published, the mods began working, no update to the mods was required.
> [...]
> I'm closing this issue. If there are any other incompatibilities or problems, please create a new issue.
