### ISSUE TITLE
[taskbar-thumbnail-reorder] broken after latest windows update (KB5034123)

### ISSUE THREAD

**Issue by k0t0fey** [ramensoftware/windhawk-mods#468]
Broken after install this update `2024-01 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5034123)`.

Mod cant load
![image](https://github.com/ramensoftware/windhawk-mods/assets/8201604/6354fecf-e1b9-4e34-af23-940e16fab81d)

**Comment by m417z** [comment]
It should work now. Please disable and re-enable the mod, or restart Windhawk.

The issue is smilar to #464. As with [one of the previous updates](https://github.com/ramensoftware/windhawk-mods/issues/318#issuecomment-1741725866):

> Most taskbar-related mods didn't work on the day the update was published because it took time for Microsoft to publish debug symbols for it. Once published, the mods began working, no update to the mods was required.
> [...]
> I'm closing this issue. If there are any other incompatibilities or problems, please create a new issue.
