### ISSUE TITLE
Taskbar Thumbnail reorder restarts Explorer and opens "Windhawk toolkit", did not reorder anything.

### ISSUE THREAD

**Issue by kwyntes** [ramensoftware/windhawk-mods#469]
Using Windhawk v1.4.1 running on Windows 10 22H2.

No idea what's happening here. Once I start dragging any of the thumbnails (happens as soon as I move my mouse while holding left-click on a thumbnail), Windows Explorer suddenly restarts, and a little "Windhawk toolkit" window pops up. Expectedly, nothing is reordered on the taskbar.

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

Also, can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by kwyntes** [comment]
I've attached [the debug log output](https://github.com/ramensoftware/windhawk-mods/files/13906509/debuglogoutput.txt).

I'm not sure I'm comfortable publishing a memory dump containing a huge portion of my RAM contents yet, but I suppose I could email a WeTransfer link or something (the file is 848 MB in size and I'm not sure where I should upload it right now).

**Comment by m417z** [comment]
You can find my email address here, thanks:
https://ramensoftware.com/contact

**Comment by kwyntes** [comment]
I've sent the crash dump in an email.

**Comment by m417z** [comment]
Thanks, I believe that Taskbar Thumbnail Reorder v1.0.5 should fix it. Please try it and let me know whether it works or not.

**Comment by kwyntes** [comment]
Yes, it works again! Thank you!
