### ISSUE TITLE
Taskbar Labels for Windows 11: Broken icon and text layout after update

### ISSUE THREAD

**Issue by jessey-git** [ramensoftware/windhawk-mods#481]
I was happily running version 1.1.5 for quite some time and decided to give the newer updates a try but that seems to have been a mistake. It doesn't seem like the settings for padding and space between are being used correctly and most taskbar entries show overlapping elements.

Here's 2 examples, all with the same settings. The problem bounces around each time I apply "8" for left-right padding and "8" for space-between:

![ex1](https://github.com/ramensoftware/windhawk-mods/assets/7989986/5d7bedee-a533-49d8-8108-4a985068d2ba)
![ex2](https://github.com/ramensoftware/windhawk-mods/assets/7989986/850782f8-557d-4878-9428-f5c591e9a13a)

Logs from one attempt:
[logs.txt](https://github.com/ramensoftware/windhawk-mods/files/13972640/logs.txt)

@m417z

**Comment by jessey-git** [comment]
I had to go back to 1.1.5 in the meantime.

**Comment by m417z** [comment]
I don't see this problem. Perhaps it's a conflict with another mod such as [Taskbar height and icon size](https://windhawk.net/mods/taskbar-icon-size). Can you disable other mods and check this?

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/eaf023bb-72ed-43d9-8b58-b04902d95403)

**Comment by m417z** [comment]
Note that there's a known incompatibility with the "Taskbar button width" option of the **Taskbar height and icon size** mod. If you're using this option, make sure it's not too small to have space for the icon, and adjust "Space between icon and label" to a larger value. Also make sure to restart explorer for the option to apply.

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/8f47de98-6211-48b8-b835-c7f6210e019d)

**Comment by jessey-git** [comment]
Ah, I think that "Taskbar button width" was the problem. I had mine set to 20.  After bumping back to the default of 44 things seem ok now I think.
