### ISSUE TITLE
[taskbar-wheel-cycle] Feature request: add an option to loop through the TaskItem (instead of reaching the end)

### ISSUE THREAD

**Issue by Skylli202** [ramensoftware/windhawk-mods#483]
Hi @m417z,

I'd like to suggest a feature request, that could be an option (?) for an opt-in behavior. When you scroll through the taskbar, it stops whenever you reach the end/start (same behavior with the key binds).

I would like to suggest the "loop" behavior, calling next on the last taskbar item goes to the first taskbar item. And calling previous on the first taskbar item goes to the last taskbar item. Implementation wise, I think it is just a matter of having the complete eligible taskbar item list length and performing a modulo operation on it with current task bar item +/- 1. What I do not know is if you have the whole taskbar stored in an array (or vector, you get the point). If not, it makes things more difficult. I tried to take a look at it, but I cannot be 100% certain, I need more time.

I definitely can see two different usages, that's why I think an option would be nice.

Thanks in advance for reading me, and for your job. Your tool is really much appreciated over here!

**Comment by m417z** [comment]
Isn't it exactly what the "Wrap around" option does?

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/913bb610-8b4c-461d-aeef-32ba068ff804)

**Comment by Skylli202** [comment]
Hi,

It actually does. Mine was enabled, but not working. I disabled it, saved, and enabled it back. And just work. Thanks.
