### ISSUE TITLE
Duplicate pinned icon at the end of the taskbar / Disable grouping on the taskbar

### ISSUE THREAD

**Issue by kinggreedy** [ramensoftware/windhawk-mods#501]
Mod name: Disable grouping on the taskbar.
Version: 1.3.1
Setting: Pinned items remain in place
Winver: 22631.3085
Other Windhawk mod: No
Taskbar settings: Always show Label
Also running ExplorerPatcher, but no setting affecting Taskbar.

![image](https://github.com/ramensoftware/windhawk-mods/assets/6055140/65ad94cb-c301-46b6-9877-db36614572c0)

Problem: Pinned item, in this case, explorer, reappear at the end of the taskbar. Sometimes I can click it and it will launch Windows Explorer. Sometimes it won't do anything.
I am not sure if this is the same problem with #461 but clearly not a duplicate.

Workarounds: Downgrade to version 1.3 work without this issue.

Note: This issue is the entirely reason I'm not using Win10 taskbar. And it happens even with native Windows Never Combine, Show Label setting without 7+ Taskbar Tweaker, but it happens more with 7+ Taskbar Tweaker. I hope it's possible to debug the problem and reapply the fix retroactive to 7+ Taskbar Tweaker if a fix is possible.

**Comment by m417z** [comment]
Version 1.3 had this issue: https://github.com/ramensoftware/windhawk-mods/issues/454

If you're using the Win11 taskbar, then 7+ Taskbar Tweaker doesn't work with it, so I'm not sure why you're mentioning it.

In any case, please try to come up with a way to reproduce the problem. It difficult to try and fix it without reproduction steps.

**Comment by kinggreedy** [comment]
> If you're using the Win11 taskbar, then 7+ Taskbar Tweaker doesn't work with it, so I'm not sure why you're mentioning it.

This issue typically happened in the past when I was using Windows 10, or using ExplorerPatcher and switch the taskbar to Windows 10 combining with using 7+Taskbar Tweaker. 

> In any case, please try to come up with a way to reproduce the problem. It difficult to try and fix it without reproduction steps.

This issue only happen after a long time usage, once it happen it will manifest, typically only explorer icon, but I will try to notice and come up with a way to reproduce the problem

**Comment by m417z** [comment]
I made some improvements in version 1.3.3, hopefully this issue is fixed. If you see the bug with the new version, please let me know.
