### ISSUE TITLE
[Taskbar notification icon spacing] Spacing  & icon size does not work on system icons

### ISSUE THREAD

**Issue by klaritan** [ramensoftware/windhawk-mods#506]
![2024-02-05_06-53-10](https://github.com/ramensoftware/windhawk-mods/assets/37451289/32f471ed-a06e-4507-96cb-801cb8787c02)

Microphone usage (which app is using it),
Keyboard selector (Microsoft IME, English),
and that ethernet/sound icons are not being affected by the settings in the mod.

Other user app icons like Discord are properly modded.

Using Windows 11 Pro (10.0.22631 Build 22531)

**Comment by m417z** [comment]
> and that ethernet/sound icons are not being affected by the settings in the mod.

Those two are affected. The others you mentioned - microphone, keyboard - are indeed not affected. I'll look into adding support for them.

**Comment by klaritan** [comment]
> Those two are affected. The others you mentioned - microphone, keyboard - are indeed not affected. I'll look into adding support for them.

Ah I see that now those two are affected.

And thank you! Those have incredibly huge padding around them.

**Comment by m417z** [comment]
I didn't have the time to look at it yet, but for completeness: note that meanwhile, you should be able adjust the padding with the [Windows 11 Taskbar Styler](https://windhawk.net/mods/windows-11-taskbar-styler) mod.

**Comment by HMwancheng** [comment]
![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/1a8aa718-b554-48c1-b072-71ffc541e342)
It can't control the IME indicate

**Comment by m417z** [comment]
How did you come up with these styles?
For me, the following worked:
Target: `SystemTray.LanguageTextIconContent`
Style: `Width=26`
You can adjust the width according to the text.

**Comment by HMwancheng** [comment]
I'm so sorry of my poor english(●ˇ∀ˇ●)

-->How did you come up with these styles?
I get them from https://github.com/ramensoftware/windows-11-taskbar-styling-guide/blob/main/README.md#themes
I just try witch one can adjust the IME indicate😂

-->You can adjust the width according to the text.SystemTray.LanguageTextIconContentWidth=26
It's work!!!!!  tks!!!!!!  useful!!!!!

**Comment by HMwancheng** [comment]
I'm not sure
but this "Width" maybe minimum is 28？
![image](https://github.com/ramensoftware/windhawk-mods/assets/91036325/90f8f317-f83f-4a78-b345-c64536797321)

**Comment by m417z** [comment]
As I said, it depends on the text inside the IME indicator. Set the width that works best for you.

**Comment by HMwancheng** [comment]
Get it！
Tks！！！

**Comment by Tiger-Heli** [comment]
Michael,

Appreaciate all your work with this. The mod currently doesn't change the inactive icons (the ones hidden until you click the up chevron. They are still 40 pixels.

Could a future update correct these also?

**Comment by m417z** [comment]
Done in version 1.1. If anything is still not affected, please let me know.
