### ISSUE TITLE
Slick Window Arrangement detected as Trojan:Win32/Bearfoos.B!ml

### ISSUE THREAD

**Issue by clau-bucur** [ramensoftware/windhawk-mods#518]
Windows Security on my Windows 10 machine detected the mod `Slick Window Arrangement ` v1.0.1 as a `Trojan:Win32/Bearfoos.B!ml`
![image](https://github.com/ramensoftware/windhawk-mods/assets/47672949/2378411f-aec6-432e-b087-0c46b23a1871)

What would be the reason for that?
And is there some solution for it?

**Comment by m417z** [comment]
It looks like a false positive detection. Please report it as a false positive to Microsoft here:
https://www.microsoft.com/en-us/wdsi/filesubmission

Meanwhile, you can exclude it, or the whole mods folder (`D:\Apps\Windhawk\AppData\Engine\Mods`) in Windows Defender. The files in this folder are compiled locally from the mods' source code, so they're as safe as the mods' source code is, which is short and fairly easy to verify.

**Comment by m417z** [comment]
I'm closing this issue as there's not much I can do in Windhawk to fix or improve this.
