### ISSUE TITLE
"Additional clock" tooltip displays wrong time

### ISSUE THREAD

**Issue by MuscularPuky** [ramensoftware/windhawk-mods#52]
(im win11 but not sure this is also applies on 10)

taskbar clock tooltip is on this format:

**"full date format"**(changed by language)\n
\n
**"Windhawk's Week day format" "Windhawk's Top line format" "(Clock name)"**\n(whatever language)
**2nd clock with 1st's format**\n
**3rd clock**

it's cool taskbar clock tooltip following Windhawk's Top line format i think but there is a bit problem

ex) i setted additional clock to PST; main clock displays **sunday, 00:30**. 2nd clock displays **saturday, 00:30**.

Local Time and PST are displaying same time, as Windhawk's Top line format.
i should check timezone often. of course nofitication center displays correct time but incorrect tooltip makes confuse me.

**Comment by m417z** [comment]
Actually, the mod shouldn't affect the tooltip text at all. That's something I wanted to implement, but didn't yet.
Here's what I see on my Windows 11 computer:

![image](https://user-images.githubusercontent.com/4129781/196038275-4e8a4f92-2b7e-4484-94a9-bae73204c2c9.png)

Are you seeing a different tooltip with the mod enabled and disabled?
If not (which I assume is the case), I take it as a feature request to customize the tooltip.

**Comment by MuscularPuky** [comment]
this only occured when "additional clock" is enabled. "Sunday, October 16, 2022" test is displaying even in that but next lines are displaying incorrect time. 

![image](https://user-images.githubusercontent.com/93962018/196044918-47adbe33-c29c-4250-a05f-7afca4c04eb5.png)
(without tweak)

![image](https://user-images.githubusercontent.com/93962018/196044250-c425b600-a532-4349-871d-fbd10288e3b1.png)
(with tweak)

it seems to tooltip is coded to must display same format as taskbar clock aka "Top line" format in Windhawk and if so, may should replace taskbar clock tooltip text i think. i trired modifying tooltip but im not good with UWP–english neither :(

**Comment by smnio** [comment]
I'm seeing this too, on two different machines running 22621.963:

With tweak
![image](https://user-images.githubusercontent.com/84639976/209439199-7007e54f-9b5a-4d02-b133-ed1f48163e20.png)

Without tweak
![image](https://user-images.githubusercontent.com/84639976/209439221-f27ac608-d3dc-40b9-9574-5babaae0102c.png)

The tooltip shows the system time for the additional clocks when the tweak is enabled, so the CET time in the example above is incorrect when the tweak is enabled.

**Comment by m417z** [comment]
Thanks for the detailed explanation and the screenshots. Fixed in Taskbar Clock Customization v1.0.6.
