### ISSUE TITLE
With new Windows update, the Taskbar height and icon size doesnt work anymore @m417z

### ISSUE THREAD

**Issue by GryAsl** [ramensoftware/windhawk-mods#525]
after the [new update](https://support.microsoft.com/en-us/topic/february-13-2024-kb5034467-cumulative-update-for-net-framework-3-5-and-4-8-1-for-windows-11-version-22h2-and-windows-11-version-23h2-dc19c781-bae4-4c66-bff0-143be84ac99d), the mod doesnt work (as expected).

is there going to be any new update to fix that? and thx for this mod its clearly most essential thing on W11.

**Comment by Werner-Wolff** [comment]
Overcame problem via:
click Windows Start, click User Name, Disconnect User and Reconnect. 
Werner-Wolff

**Comment by GryAsl** [comment]
@Werner-Wolff thanks for advice but it didnt work.

I tried everything (I guess) but the only **solition** was downloading the installer of Windhawk and install Windhawk again. (Idk why but installing with already downloaded installer didnt solve anything)
