### ISSUE TITLE
Large Taskbar Icons mod causes first Explorer window show delay

### ISSUE THREAD

**Issue by ErmineMD** [ramensoftware/windhawk-mods#53]
0. Enable Large Taskbar Icons mod.
1. Close all Explorer windows.
2. Wait until it’s process is stopped or stop it manually.
3. Start Explorer.
4. Explorer starts but it’s window is shown after about 11 seconds.

Here is video: https://youtu.be/fNQU7yi_MWU

If mod is disabled, Explorer window is shown immediately.

Windows 11 22H2 22621.675
Windhawk v0.9.2 beta

**Comment by m417z** [comment]
It's a known issue, also mentioned [here](https://github.com/ramensoftware/windhawk-mods/issues/36#issuecomment-1226849943). I plan to address it in one of the next mod updates.

**Comment by m417z** [comment]
Should be fixed in v1.0.2 of the mod. It still might be slightly slow because of the issue I linked above, but not 10-seconds slow which was causes by another problem and should now be fixed.
