### ISSUE TITLE
Middle click to close on the taskbar no longer working

### ISSUE THREAD

**Issue by Gravarty** [ramensoftware/windhawk-mods#540]
17:48:44.793 10644 explorer.exe  [WH] [taskbar-button-click] [532:Wh_ModInit]: >
17:48:44.793 10644 explorer.exe  [WH] [taskbar-button-click] [311:GetWindowsVersion]: Version: 10.0.22621.3227
17:48:44.793 10644 explorer.exe  [WH] [taskbar-button-click] [473:HookSymbols]: Couldn't resolve all symbols from cache
17:48:45.292 10644 explorer.exe  [WH] [taskbar-button-click] [478:HookSymbols]: Wh_FindFirstSymbol failed

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by Gravarty** [comment]
DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
20:26:18.749 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
20:26:18.749 6768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.22631
20:26:18.749 6768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
20:26:18.749 6768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-button-click
20:26:18.749 6768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.5
20:26:18.774 6768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFAC5360000
20:26:18.774 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
20:26:18.774 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
20:26:18.774 6768 explorer.exe  [WH] [taskbar-button-click] [532:Wh_ModInit]: >
20:26:18.774 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringSetting
20:26:18.774 6768 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueName: multipleItemsBehavior
20:26:18.774 6768 explorer.exe  [WH] [LoadedMod::GetStringSetting]: valueNameFormatted: multipleItemsBehavior
20:26:18.774 6768 explorer.exe  [WH] [LoadedMod::GetStringSetting]: value: closeAll
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringSetting
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FreeStringSetting
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FreeStringSetting
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: oldTaskbarOnWin11
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: oldTaskbarOnWin11
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 0
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
20:26:18.775 6768 explorer.exe  [WH] [taskbar-button-click] [311:GetWindowsVersion]: Version: 10.0.22621.3227
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-taskbar.dll
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
20:26:18.775 6768 explorer.exe  [WH] [taskbar-button-click] [473:HookSymbols]: Couldn't resolve all symbols from cache
20:26:18.775 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FFAB43C0000
20:26:18.775 6768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\Windows\System32\Taskbar.dll
20:26:18.776 6768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 10.0.22621.3227
20:26:18.794 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
20:26:18.795 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\EDEE05FDCD1189DB9D0094125D9C6CED1\Taskbar.pdb - path not found
20:26:18.795 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\EDEE05FDCD1189DB9D0094125D9C6CED1\Taskbar.pd_ - path not found
20:26:18.795 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.pdb\EDEE05FDCD1189DB9D0094125D9C6CED1\file.ptr - path not found
20:26:18.795 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/index2.txt
20:26:18.900 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
20:26:18.900 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/EDEE05FDCD1189DB9D0094125D9C6CED1/Taskbar.pdb
20:26:19.060 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
20:26:19.060 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/EDEE05FDCD1189DB9D0094125D9C6CED1/Taskbar.pd_
20:26:19.164 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
20:26:19.164 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.pdb/EDEE05FDCD1189DB9D0094125D9C6CED1/file.ptr
20:26:19.267 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
20:26:19.268 6768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x80190194
20:26:19.271 6768 explorer.exe  [WH] [LoadedMod::LogFunctionError]: Mod taskbar-button-click error: engine\symbol_enum.cpp(201)\windhawk.dll!00007FFABD30CD74: (caller: 00007FFABD2FA66E) Exception(2) tid(858) 806D0005 
20:26:19.271 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
20:26:19.271 6768 explorer.exe  [WH] [taskbar-button-click] [478:HookSymbols]: Wh_FindFirstSymbol failed
20:26:19.271 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
20:26:19.271 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
20:26:19.271 6768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod

**Comment by m417z** [comment]
According to the log, you're using Windows 11 version 10.0.22621.3227, which is a release preview build. Microsoft didn't release debug symbols for this build, that's why the mod doesn't work (you can see the `HTTP_STATUS_NOT_FOUND` error in the log).

From the [Troubleshooting page](https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work):

> If the log contains the `HTTP_STATUS_NOT_FOUND` error, debug symbols are unavailable. Microsoft doesn't publish debug symbols for some Windows builds, or publishes them with a significant delay. This often occurs with preview builds (Canary, Dev, Beta, or Release Preview builds). For better compatibility with Windhawk, it's best to avoid preview Windows builds.

**Comment by Gravarty** [comment]
Sorry for the late response but the version i was using then and now is the default version you get from the Microsoft ISO site. I'm not participating in any Insider Beta builds or downloading any Pre-Release updates. The mod is still not working and looking at the changelogs, it seems it got its last update in Nov 2023.
