### ISSUE TITLE
explorer-frame-classic missing nav bar when from EverythingToolbar

### ISSUE THREAD

**Issue by 70V07** [ramensoftware/windhawk-mods#543]
if the mod explorer-frame-classic is enabled and open a path in File Explorer from [EverythingToolbar](https://github.com/srwi/EverythingToolbar) the navigation bar disappear... just not present, but everything and file explorer both work fine

![Untitled](https://github.com/ramensoftware/windhawk-mods/assets/46967291/46b06879-5ed2-4742-88af-e774966bfedc)

_not really a bug, simply progs incompatibility_

**Comment by m417z** [comment]
It's a known issue: https://github.com/ramensoftware/windhawk-mods/issues/487, closing as duplicate.
