### ISSUE TITLE
[Taskbar Thumbnail Reorder] Doesn't work anymore

### ISSUE THREAD

**Issue by justsomebodyhere** [ramensoftware/windhawk-mods#558]
Hi @m417z,

As of several days ago, this is no longer working.

In Windows' Taskbar settings, I have both of the following set to "Never":

- Combine taskbar buttons and hide labels
- Combine taskbar buttons and hide labels on other taskbars

Log's below. Thank you!
[debug_log.txt](https://github.com/ramensoftware/windhawk-mods/files/14593130/debug_log.txt)

**Comment by m417z** [comment]
Hi,
I'm using the same Windows version and the mod works for me.
According to the logs, the mod was loaded, then loaded another time without being unloaded. That can happen if explorer crashes. Does it crash when you enable the mod? When you try to re-order items? Please provide more details, what does "no longer working" mean, what exactly happen? A video recording will help as well.

**Comment by justsomebodyhere** [comment]
By "not working", I mean that trying to rearrange multiple windows of the same program doesn't work when clicking on the program in the taskbar. It only works when you hover over the window preview.

See https://www.loom.com/share/d5a15df22ac248458417f0386b55e73e

In the first part of this screen-recording, I'm trying to switch the order of the Chrome windows in the taskbar and then the Explorer ones. In the 2nd part, I show that it only works when first hovering over the program and rearranging the preview thumbnails.

Thanks!

**Comment by m417z** [comment]
That's exactly how it's supposed to work, it's Taskbar <ins>**Thumbnail**</ins> Reorder.

If you want your taskbar items completely separated, you can use the [Disable grouping on the taskbar](https://windhawk.net/mods/taskbar-grouping) mod. In this case, the thumbnails will be separated as well and the Taskbar Thumbnail Reorder mod won't be necessary.
