### ISSUE TITLE
 [Taskbar Labels for Windows 11] Hiding labels combines items

### ISSUE THREAD

**Issue by thewbuk** [ramensoftware/windhawk-mods#561]
Setting _-1_ in Taskbar Item Width hides the labels, but it **also combines items**, even though in Windows 11, combining apps is set to never.

My workaround is to set the taskbar item width to 1 and font size to 100, but it's not ideal as it makes the icons slightly bigger, even though the labels are not visible.

**Comment by m417z** [comment]
Thanks for the feedback. Closing as a duplicate of #418.

**Comment by mateusfn98** [comment]
@thewbuk After some research with UWPSpy and reversing some presented logic.

Using the tweak Windows 11 Taskbar Styler
In Control styles, add a new item and put:
Target: TextBlock#LabelControl
Styles: Visibility=Collapsed

Hope you like it :)

**Comment by thewbuk** [comment]
@mateusfn98 That works wonders thanks!
