### ISSUE TITLE
[ Taskbar height and icon size ] Not working anymore starting from 26080

### ISSUE THREAD

**Issue by RTFTR** [ramensoftware/windhawk-mods#562]
Starting from Windows 11 Build 26080 ge_release, The [ Taskbar height and icon size ] mod won't affect the size of taskbar icons and taskbar height.
What windhawk displays is just "Initializing" explorer.exe, and then it just closes.

![image](https://github.com/ramensoftware/windhawk-mods/assets/83257329/be40e967-568e-43e4-ac5e-6cf62daf65ee)

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by RTFTR** [comment]
> Please attach debug logs by following the instructions on the Troubleshooting page: https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work
> 
> > * Disable the mod.
> > * Go to the mod's Advanced tab.
> > * Set **Debug logging** to **Detailed debug logs**.
> > * Click on **Show log output**.
> > * Enable the mod.
> > * Verify that the mod doesn't work, copy the log and save it to a file.
> > * Set **Debug logging** back to **None**.

oops, didn't know that, here's the log

`DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
07:44:43.414 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
07:44:43.414 9960 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26080
07:44:43.414 9960 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
07:44:43.415 9960 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-icon-size
07:44:43.415 9960 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.2.4
07:44:43.440 9960 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FF973AA0000
07:44:43.440 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
07:44:43.440 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
07:44:43.441 9960 explorer.exe  [WH] [taskbar-icon-size] [1149:Wh_ModInit]: >
07:44:43.441 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: IconSize
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: IconSize
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 16
07:44:43.441 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
07:44:43.441 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarHeight
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarHeight
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 36
07:44:43.441 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
07:44:43.441 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
07:44:43.441 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarButtonWidth
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarButtonWidth
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 20
07:44:43.442 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
07:44:43.442 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.View.dll
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#1707251086#7716864#public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const #983712#public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)#5938624#public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)#5808108#private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)#1475932#__real@4048000000000000#6901992#public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
07:44:43.442 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
07:44:43.442 9960 explorer.exe  [WH] [taskbar-icon-size] [839:HookSymbols]: Couldn't resolve all symbols from cache
07:44:43.442 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FF9B3AB0000
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll
07:44:43.442 9960 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 2024.6000.0.0
07:44:43.446 9960 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
07:44:43.453 9960 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  PATH: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\67710BAA2C83453A950CA6954D95AB921\Taskbar.View.pdb
07:44:43.453 9960 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x00000000
07:44:43.462 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
07:44:44.226 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.226 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3ACFF24
07:44:44.226 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1970
07:44:44.226 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.227 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3ACFF24: public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const 
07:44:44.256 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.256 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3DC6050
07:44:44.256 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1D00
07:44:44.256 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.256 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3DC6050: public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)
07:44:44.262 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.262 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3D54794
07:44:44.262 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1D50
07:44:44.262 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.262 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3D54794: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)
07:44:44.276 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.276 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3CD41CC
07:44:44.276 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1DD0
07:44:44.276 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.276 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3CD41CC: private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
07:44:44.292 9960 explorer.exe  [WH] [taskbar-icon-size] [762:operator()]: Found 00007FF9B4175E68: __real@4048000000000000
07:44:44.293 9960 explorer.exe  [WH] [taskbar-icon-size] [762:operator()]: Found 00007FF9B3DBE390: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const 
07:44:44.401 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.402 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3CB68DC
07:44:44.402 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1F60
07:44:44.402 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.402 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3CB68DC: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::SystemTray::SystemTrayFrame>::Height(double)const 
07:44:44.408 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.408 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3CD418C
07:44:44.408 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1F10
07:44:44.408 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.408 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3CD418C: private: void __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::UpdateFrameSize(void)
07:44:44.461 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.461 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3D09520
07:44:44.461 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1F80
07:44:44.461 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.461 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3D09520: private: void __cdecl winrt::Taskbar::implementation::TaskbarController::OnFrameSizeChanged(void)
07:44:44.533 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.533 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3D45240
07:44:44.533 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA2030
07:44:44.533 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.533 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3D45240: protected: virtual void __cdecl winrt::Taskbar::implementation::AugmentedEntryPointButton::UpdateButtonPadding(void)
07:44:44.547 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.547 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3AF71A0
07:44:44.547 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1E30
07:44:44.547 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.547 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3AF71A0: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
07:44:44.556 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.556 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3CB6840
07:44:44.556 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA2080
07:44:44.556 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.556 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3CB6840: public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Windows::UI::Xaml::Controls::Primitives::RepeatButton>::Width(double)const 
07:44:44.595 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
07:44:44.595 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FF9B3ADCF30
07:44:44.595 9960 explorer.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FF973AA1D30
07:44:44.595 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
07:44:44.595 9960 explorer.exe  [WH] [taskbar-icon-size] [758:operator()]: Hooked 00007FF9B3ADCF30: public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)
07:44:44.599 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindCloseSymbol
07:44:44.605 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindCloseSymbol
07:44:44.605 9960 explorer.exe  [WH] [taskbar-icon-size] [864:HookSymbols]: Optional symbol 5 doesn't exist
07:44:44.605 9960 explorer.exe  [WH] [taskbar-icon-size] [860:HookSymbols]: Unresolved symbol: 9
07:44:44.605 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
07:44:44.605 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
07:44:44.605 9960 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod
`

**Comment by m417z** [comment]
One of the functions hooked by the mod is no longer available. I'll have to install the new build and check out what exactly changes.

**Comment by jibnew** [comment]
In my case it seems Bitdefender was blocking the mod - when I added it to the exceptions it started working

**Comment by MuscularPuky** [comment]
me too at 26090, even I don't have Bitdefender and just only have MS Defender

**Comment by beralbdom** [comment]
> Starting from Windows 11 Build 26080 ge_release, The [ Taskbar height and icon size ] mod won't affect the size of taskbar icons and taskbar height. What windhawk displays is just "Initializing" explorer.exe, and then it just closes.
> 
> ![image](https://private-user-images.githubusercontent.com/83257329/312841855-be40e967-568e-43e4-ac5e-6cf62daf65ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MjQ3MjksIm5iZiI6MTcxNDYyNDQyOSwicGF0aCI6Ii84MzI1NzMyOS8zMTI4NDE4NTUtYmU0MGU5NjctNTY4ZS00M2U0LWFjNWUtNmNmNjJkYWY2NWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA0MzM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDM0YTQ0NDY5MDA3ZGI4ZTc2ZjQwYjAxN2EwOWM5M2RjYmY3NTYzOTljNjM2ZTk2YjdiMzUwMTEyNGZkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoH9G4BGbDrVMByRrfF1IClUfC4-FjJAk79eFPT7LY8)

Sorry for the unrelated question, but what are you using to force dark mode on that window?

**Comment by m417z** [comment]
Support for Windows 11 Version 24H2 was added in version 1.2.10 of the mod.
