### ISSUE TITLE
Taskbar Labels for Windows 11: Closed windows fill space in taskbar ()

### ISSUE THREAD

**Issue by Biosphakus** [ramensoftware/windhawk-mods#585]
Problem: Using "Taskbar labels for Windows 11", windows take up size in the taskbar even after closing. The size of the windows doesn't seem to be refreshing (see picture below: after Thunderbird has been closed, it still takes up space in the taskbar). 

Details: This problem seems to have arisen with the latest Windows Update (KB5035942). Apparently, this update has fixed some of Windows 11 own issues with the ungrouped taskbar. However, I still prefer the Windhawk implementation. I would be very happy if this could be fixed :) 

Mod author: @m417z 

![grafik](https://github.com/ramensoftware/windhawk-mods/assets/58983561/1f7d1fd4-9a70-43d5-9840-1e823accfe2c)

**Comment by m417z** [comment]
Fixed in version 1.2.3.
