### ISSUE TITLE
[Taskbar Labels for Windows 11] Max width for the taskbar item with adaptive width

### ISSUE THREAD

**Issue by dreamsynth** [ramensoftware/windhawk-mods#588]
@m417z 

I think it makes sense to add the ability to set both the minimum and maximum width of a taskbar item, because when setting the width value to "0", an item with a long name may take up the entire taskbar, which is not good.

I am currently using Windows 11 Taskbar Styler and the following code for this:
```
{"controlStyles[0].target":"taskbar:TaskListButton","controlStyles[0].styles[0]":"MaxWidth=160"}
```
Comparison for clarity:

Before:
![изображение](https://github.com/ramensoftware/windhawk-mods/assets/84819091/a38bf897-eb60-4202-bcb2-07d866157705)
After:
![изображение](https://github.com/ramensoftware/windhawk-mods/assets/84819091/2101f342-3759-4195-9fe6-9b5f2747f4cd)

So the width of the taskbar items remains adaptive, but at the same time does not exceed 160 pixels.

**Comment by m417z** [comment]
Thanks for the suggestion, it's also a bug as I intended for it to have the default Windows maxWidth. Added an option for it in 1.2.4.
