### ISSUE TITLE
[Taskbar Scroll Actions] adjusting the Volume through scrolling on the Audio Icon

### ISSUE THREAD

**Issue by YAKSL** [ramensoftware/windhawk-mods#616]
Hi @m417z  for (Change Monitor Brightness) the current behavior when selecting the taskbar as the scroll area essentially blocks you from scrolling on the Volume button in the Notifications Area to adjust the Volume. so having the option to scroll on the Taskbar except for the Notif Area (or the Volume Icon) leaves you able to adjust the volume through scrolling on the Icon while still being able to scroll on the rest of the Taskbar to adjust the brightness.

https://github.com/ramensoftware/windhawk-mods/assets/90788845/8d5f8487-f558-4b13-bc2f-ec74846e2045

**Comment by YAKSL** [comment]
@m417z maybe a code for 'Advanced Mod settings' could suffice for this?

**Comment by m417z** [comment]
There's "Scroll area" in settings, and currently there are two options: The taskbar, The notification area. Perhaps I could add a third option: All but notification area. What do you think?

**Comment by YAKSL** [comment]
> Perhaps I could add a third option: All but notification area. What do you think?

yeah that's the best way you could go with this 'issue' @m417z

**Comment by m417z** [comment]
Added in version 1.0.1.
