### ISSUE TITLE
Taskbar Labels for Windows 11 not working after 2024-04 Windows update KB5036980

### ISSUE THREAD

**Issue by ishalev** [ramensoftware/windhawk-mods#620]
See attached for debug log. The log indicates "Unexpected button properties"

[
[4-25-2024 Debug log Windhawk taskbar labels for windows 11.txt](https://github.com/ramensoftware/windhawk-mods/files/15113008/4-25-2024.Debug.log.Windhawk.taskbar.labels.for.windows.11.txt)
](url)

**Comment by m417z** [comment]
Works on my computer with the same update. Do you think you have some specific configuration? Maybe a conflicting third party customization tool or another mod? If not, I can create a special version of the mod with extra logging, so you can load it and gather detailed logs that will hopefully help to figure out the problem.

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/33209ceb-94d6-4770-835a-a7e9be880981)

**Comment by ishalev** [comment]
I was able to resolve the issue. The feature for combining buttons/labels was not turned on, so I didn't even have the option in my taskbar settings, even though my system had the relevant update installed. This was not an issue in the past, but after the last update, it seems like it broke the mod functionality. I used the ViveTool to turn the feature on, and everything is working normally again.

**Comment by m417z** [comment]
> I used the ViveTool to turn the feature on

Can you tell me which feature was it exactly? The mod has a check for that, but perhaps the feature has a new id or something.

**Comment by m417z** [comment]
Thanks, due to a change in the function names, the check stopped working. I'll fix it in the next version of the mod.

**Comment by mtrskeen** [comment]
> Thanks, due to a change in the function names, the check stopped working. I'll fix it in the next version of the mod.

i have same bug with "middle clock to close" after KB5036980 update

**Comment by m417z** [comment]
@mtrskeen that's likely to be a different issue, see here for a workaround: https://github.com/ramensoftware/windhawk-mods/issues/640#issuecomment-2091810033

**Comment by mtrskeen** [comment]
> @mtrskeen that's likely to be a different issue, see here for a workaround: [#640 (comment)](https://github.com/ramensoftware/windhawk-mods/issues/640#issuecomment-2091810033)

Thanks, this fixed both (middle click and taskbar height) extensions working.

**Comment by m417z** [comment]
> Thanks, due to a change in the function names, the check stopped working. I'll fix it in the next version of the mod.

Done in version 1.2.5.
