### ISSUE TITLE
bug research zone "Taskbar height and icon size" @m417z

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#624]
after the last stable "window" update. My search area has a magnifying glass icon which is enlarged
but It return to the right size when you activate it.
@m417z

https://github.com/ramensoftware/windhawk-mods/assets/142233342/c0fc4f7c-60c3-4ac8-a38a-a514ba054ea6

**Comment by m417z** [comment]
Fixed in version 1.2.5 of the mod.

**Comment by gilnett** [comment]
thanks, it works fine now
