### ISSUE TITLE
[disable-rounded-corners] Don't seem to load as it should

### ISSUE THREAD

**Issue by improwise** [ramensoftware/windhawk-mods#637]
Can't get this to load it seems

16:49:28.032 2272 <system>  [WH] [disable-rounded-corners] [52:Wh_ModInit]: >
16:49:28.032 2272 <system>  [WH] [disable-rounded-corners] [318:HookSymbols]: Couldn't resolve all symbols from cache
16:49:28.050 2272 <system>  [WH] [disable-rounded-corners] [323:HookSymbols]: Wh_FindFirstSymbol failed

![image](https://github.com/ramensoftware/windhawk-mods/assets/2812422/fb157e68-4a94-4c61-9ba3-cbf7796dbfc7)

Am I doing something wrong?

**Comment by improwise** [comment]
Just to make sure WindHawk itself is working, I installed the taskbar-volume-control which seem to load and work fine.

**Comment by m417z** [comment]
> 16:49:28.050 2272 [WH] [disable-rounded-corners] [323:HookSymbols]: Wh_FindFirstSymbol failed

The mod wasn't able to load or find the relevant symbols. To see the reason of the failure, please include all logs.

**Comment by improwise** [comment]
Seems like there is some kind of "network problem". Unlike with the taskbar-volume-control, I never got any popup window about installation/downloading of symbols. Not when I tried to reinstall it now either. Please note that I am running latest Windows 11 even though it seem to be mentioned as Windows 10 in the logs. 

DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
00:04:21.201 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
00:04:21.201 2288 <system>  [WH] [LoadedMod::LoadedMod]: Windows 10.0.22631
00:04:21.201 2288 <system>  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
00:04:21.201 2288 <system>  [WH] [LoadedMod::LoadedMod]: Mod id: disable-rounded-corners
00:04:21.202 2288 <system>  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.1
00:04:21.202 2288 <system>  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFCC2550000
00:04:21.202 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
00:04:21.203 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
00:04:21.203 2288 <system>  [WH] [disable-rounded-corners] [52:Wh_ModInit]: >
00:04:21.203 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
00:04:21.203 2288 <system>  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-udwm.dll
00:04:21.203 2288 <system>  [WH] [LoadedMod::GetStringValue]: value: 
00:04:21.204 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
00:04:21.204 2288 <system>  [WH] [disable-rounded-corners] [318:HookSymbols]: Couldn't resolve all symbols from cache
00:04:21.204 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
00:04:21.204 2288 <system>  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FFCF8E40000
00:04:21.204 2288 <system>  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\WINDOWS\SYSTEM32\udwm.dll
00:04:21.204 2288 <system>  [WH] [LoadedMod::FindFirstSymbol3]: Version: 10.0.22621.3527
00:04:21.206 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
00:04:21.207 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\uDWM.pdb\90376BC5BD29A0F53913A5BCB8FE27851\uDWM.pdb - path not found
00:04:21.207 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\uDWM.pdb\90376BC5BD29A0F53913A5BCB8FE27851\uDWM.pd_ - path not found
00:04:21.207 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\uDWM.pdb\90376BC5BD29A0F53913A5BCB8FE27851\file.ptr - path not found
00:04:21.220 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/index2.txt
00:04:21.225 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpSendRequest: 800C2EFD - ERROR_INTERNET_CANNOT_CONNECT
00:04:21.225 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/uDWM.pdb/90376BC5BD29A0F53913A5BCB8FE27851/uDWM.pdb
00:04:21.229 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpSendRequest: 800C2EFD - ERROR_INTERNET_CANNOT_CONNECT
00:04:21.230 2288 <system>  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x800C2EFD
00:04:21.230 2288 <system>  [WH] [LoadedMod::LogFunctionError]: Mod disable-rounded-corners error: engine\symbol_enum.cpp(201)\windhawk.dll!00007FFCC92ECD74: (caller: 00007FFCC92DA66E) Exception(2) tid(7ae4) 806D0005 
00:04:21.230 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
00:04:21.230 2288 <system>  [WH] [disable-rounded-corners] [323:HookSymbols]: Wh_FindFirstSymbol failed
00:04:21.230 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
00:04:21.230 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
00:04:21.230 2288 <system>  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod

**Comment by m417z** [comment]
Indeed, the target process (dwm.exe) tries to download debug symbols, but fails to connect to the internet as the log says. Are you using a firewall? Are you using a proxy server? 

If you can't find a solution, as a workaround, what might work is running [Windhawk Symbol Helper](https://github.com/ramensoftware/windhawk-symbol-helper/releases/latest), then setting the following under "Target executable": `C:\Windows\System32\udwm.dll`, clicking "Get symbols", then disabling and re-enabling the mod. If it will work, note that you'll need to do it after every Windows update.

**Comment by improwise** [comment]
No firewall besides Windows normal ones. I recall seeing something about the taskbar-volume-control downloading stuff so I assumed that was working but didn't really read it all that carefully. You happen to have the URL it tries to reach and I can try it manually?

**Comment by m417z** [comment]
Yes, it's:
https://msdl.microsoft.com/download/symbols/uDWM.pdb/90376BC5BD29A0F53913A5BCB8FE27851/uDWM.pdb

**Comment by m417z** [comment]
Either way, it's not a mod bug, so I'm closing this issue. If it's still unsolved, feel free to follow up.

**Comment by improwise** [comment]
I can browse the URL above fine from the same machine but still not possible to use the mod due to the same reason.

**Comment by improwise** [comment]
When I restarted the computer today the mod worked even though I have not made any changes on my end so guessing this might have gotten fixed somehow.

![image](https://github.com/ramensoftware/windhawk-mods/assets/2812422/c5874ff8-be75-462f-a0d7-6296da384c0f)
