### ISSUE TITLE
[Resource Redirect] File copy dialog missing text after UIFILE support was added

### ISSUE THREAD

**Issue by Cynosphere** [ramensoftware/windhawk-mods#639]
Text for "Replace", "Rename" and "Don't Copy" is missing. None of my redirected resources should be breaking it, as they are the original versions with only icons replaced.
![Screenshot of file copy dialog with missing text](https://toaster.sh/i/mropn3ry.png)

@m417z

**Comment by m417z** [comment]
There isn't enough info in your report to understand what the issue is about. What have you tried? Which redirection file causes it? Does the issue happen if the redirection file is identical to the redirected file? Does the issue happen if the redirection file is empty? Which specific resource causes the problem? Also try to provide a way for me to reproduce the problem on my computer.

**Comment by Cynosphere** [comment]
> Which redirection file causes it?

shell32.dll

> Does the issue happen if the redirection file is identical to the redirected file?

Yes, copying `C:\Windows\System32\SystemResources\shell32.dll.mun` to somewhere else and pointing to it causes it.

**Comment by Cynosphere** [comment]
Legacy File Copy mod

**Comment by m417z** [comment]
I can reproduce it. I'll look at it in detail later.

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/f3273c0c-82ea-456f-8ffd-c90ef1a9526b)

**Comment by m417z** [comment]
I'm not familiar with the UIFILE format, but what I discovered is that if I import the String Table resources from shell32.dll.mui to the redirected file, the issue gets fixed. I assume that the UIFILE resource somehow references strings from the same file. For the original shell32.dll, these strings are found in the mui file, but your file neither has the strings, nor a mui file, so no strings can be loaded.

**Comment by m417z** [comment]
Please try the following: Copy the OS shell32.dll.mun, then importing everything from shell32.dll.mui to it (fairly easy in reshacker), then try it as a redirection file. Do you see the issue in this case?

**Comment by Cynosphere** [comment]
> Do you see the issue in this case?

Yes

**Comment by m417z** [comment]
OK, that's a tricky one, I spent some more time on it, and I think I understand the issue.

> I assume that the UIFILE resource somehow references strings from the same file. For the original shell32.dll, these strings are found in the mui file, but your file neither has the strings, nor a mui file, so no strings can be loaded.

I believe that my assumption was correct. I used [DuiTool](https://github.com/ahmed605/DuiTool) to decompile the resource, and indeed it contains `resstr` occurrences such as:
```xml
	<element resid="cmdMove" layout="filllayout()">
		<macro expand="CommandTile">
			<bind connect="tileAction" content="resstr(13610)" />
			<bind connect="tileExplanation" content="resstr(13611)" />
		</macro>
	</element>
```

> > Do you see the issue in this case?
> 
> Yes

I tried it, and could reproduce the issue as well, even though I believed it should work. After some debugging I saw that in this case, string loading fails with the `ERROR_MUI_FILE_NOT_LOADED` error. After some trail and error, I believe that the `MUI` resource instructs the string loading function to search for MUI files, which in this case aren't being used.

So now, please try the following (new part is in bold): Copy the OS shell32.dll.mun, then importing everything from shell32.dll.mui to it (fairly easy in reshacker), **then remove the `MUI` resource**, then try it as a redirection file. Do you see the issue in this case?

**Comment by Cynosphere** [comment]
> Copy the OS shell32.dll.mun, then importing everything from shell32.dll.mui to it (fairly easy in reshacker), **then remove the `MUI` resource**, then try it as a redirection file. Do you see the issue in this case?

Works as normal

**Comment by m417z** [comment]
In this case, mystery solved, and I assume that the problem is solved as well.

**Comment by m417z** [comment]
I got feedback from other users that while this behavior can be explained and a workaround exists, it's usually undesirable. I took another look at it and I believe that I found a solution. You can find the improved version here:
https://github.com/m417z/my-windhawk-mods/blob/c44aa2ea721ea7a2d146551f18be6c4ed64163e2/mods/icon-resource-redirect.wh.cpp
Let me know if it works as expected for you before I officially release an update for the mod.
