### ISSUE TITLE
[Taskbar Thumbnail Reorder] requires disable/enable to work

### ISSUE THREAD

**Issue by jibbers42** [ramensoftware/windhawk-mods#64]
After rebooting, I can't reorder taskbar thumbnail unless I open Windhawk and disable then enable Taskbar Thumbnail Reorder.

Windhawk v0.9.2 beta
Taskbar Thumbnail Reorder 1.0.2

Windows...
Edition	Windows 11 Pro
Version	22H2
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

edit: To clarify, Windhawk is set to run on Windows startup - so it is running. The module needs to be disabled and then enabled to work.

**Comment by m417z** [comment]
Fixed in version 1.0.3 of the mod.
