### ISSUE TITLE
Mods won't load - Windows 11 23H2 (22631.3447)

### ISSUE THREAD

**Issue by nazzy121** [ramensoftware/windhawk-mods#641]
Windhawk has worked great for MOST of my computers except 1 computer some mods won't load.  See screenshot below.  

Does NOT load:  
1) taskbar-grouping  (unloaded) 
2) taskbar-notification-icon-spaciing (unloaded) 

However, this mod DOES load:   windows-11-start-menu-styler.   (loaded)

On the PC with this problem, I had ExplorerPatcher previously installed.  Uninstalled it, then installed Windhawk.  I used this same procedure on other PC's without issue, however this particular PC just won't load these 2 mods that I need.  How would I begin to troubleshoot the unloaded mods?   I have tried reinstalling Windhawk several times,  rebooting PC multiple times, etc, nothing worked so far.  

Windows 11 23H2 (22631.3447)
Windhawk v1.4.1

![Screenshot 2024-05-03 004558](https://github.com/ramensoftware/windhawk/assets/158132428/2789a13e-b29e-4ad3-8a45-3a858a190f74)

**Comment by m417z** [comment]
Let's start with one of the mods, for example taskbar-grouping. The problem for both is probably the same and is related to debug symbol downloading.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by schimschewski** [comment]
same here, it happens after the update on KB5036980 (Get Windows updates as soon as they're available-option is disabled!)
all taskbar relevant mods are unloaded. uninstall of this update fixes this problem

![image](https://github.com/ramensoftware/windhawk-mods/assets/37181405/f8edd986-1e4f-49d8-80b9-08c2993001a8)

**Comment by schimschewski** [comment]
`DebugViewConsole 1.8.0.102
Listening for OutputDebugString messages...
10:00:12.489 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
10:00:12.489 7768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.22631
10:00:12.489 7768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.4.1
10:00:12.489 7768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod id: taskbar-icon-size
10:00:12.489 7768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.2.5
10:00:12.489 7768 explorer.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFA49460000
10:00:12.489 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
10:00:12.490 7768 explorer.exe  [WH] [taskbar-icon-size] [1149:Wh_ModInit]: >
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: IconSize
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: IconSize
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 32
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarHeight
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarHeight
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 64
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueName: TaskbarButtonWidth
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: valueNameFormatted: TaskbarButtonWidth
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetIntSetting]: value: 40
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetIntSetting
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::GetStringValue
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetStringValue]: valueName: symbol-cache-Taskbar.View.dll
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::GetStringValue]: value: 1#1709675630#8499200#public: __cdecl winrt::impl::consume_Windows_Foundation_Collections_IMap<struct winrt::Windows::UI::Xaml::ResourceDictionary,struct winrt::Windows::Foundation::IInspectable,struct winrt::Windows::Foundation::IInspectable>::Lookup(struct winrt::Windows::Foundation::IInspectable const &)const #212196#public: virtual int __cdecl winrt::impl::produce<struct winrt::Taskbar::implementation::TaskListItemViewModel,struct winrt::Taskbar::ITaskListItemViewModel>::GetIconHeight(void *,double *)#711392#public: static double __cdecl winrt::Taskbar::implementation::TaskbarConfiguration::GetIconHeightInViewPixels(double)#960052#private: double __cdecl winrt::SystemTray::implementation::SystemTraySecondaryController::GetFrameSize(enum winrt::WindowsUdk::UI::Shell::TaskbarSize)#711596#__real@4048000000000000#7177512#public: __cdecl winrt::impl::consume_Windows_UI_Xaml_IFrameworkElement<struct winrt::Taskbar::implementation::TaskbarFrame>::MaxHeight(double)const #36
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::GetStringValue
10:00:12.490 7768 explorer.exe  [WH] [taskbar-icon-size] [839:HookSymbols]: Couldn't resolve all symbols from cache
10:00:12.490 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
10:00:12.490 7768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FFA3F100000
10:00:12.491 7768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\Taskbar.View.dll
10:00:12.491 7768 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 624.7317.60.0
10:00:12.492 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
10:00:12.492 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\B51E5C03E5D6421AAF62E494EAA5365E1\Taskbar.View.pdb - path not found
10:00:12.492 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\B51E5C03E5D6421AAF62E494EAA5365E1\Taskbar.View.pd_ - path not found
10:00:12.492 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  UNC: C:\ProgramData\Windhawk\Engine\Symbols\Taskbar.View.pdb\B51E5C03E5D6421AAF62E494EAA5365E1\file.ptr - path not found
10:00:12.492 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/index2.txt
10:00:12.606 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
10:00:12.606 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/B51E5C03E5D6421AAF62E494EAA5365E1/Taskbar.View.pdb
10:00:12.617 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
10:00:12.617 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/B51E5C03E5D6421AAF62E494EAA5365E1/Taskbar.View.pd_
10:00:12.628 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
10:00:12.628 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HTTPGET: /download/symbols/Taskbar.View.pdb/B51E5C03E5D6421AAF62E494EAA5365E1/file.ptr
10:00:12.640 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
10:00:12.641 7768 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x80190194
10:00:12.642 7768 explorer.exe  [WH] [LoadedMod::LogFunctionError]: Mod taskbar-icon-size error: engine\symbol_enum.cpp(201)\windhawk.dll!00007FFA53C9CD74: (caller: 00007FFA53C8A66E) Exception(8) tid(1c64) 806D0005 
10:00:12.642 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
10:00:12.642 7768 explorer.exe  [WH] [taskbar-icon-size] [844:HookSymbols]: Wh_FindFirstSymbol failed
10:00:12.642 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
10:00:12.642 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::~LoadedMod
10:00:12.642 7768 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::~LoadedMod
`

**Comment by m417z** [comment]
@schimschewski Update KB5036980 is Windows build 22621.3527 or 22631.3527, different than what @nazzy121 is using (22631.3447). For your issue, please see https://github.com/ramensoftware/windhawk-mods/issues/640#issuecomment-2091810033.

**Comment by nazzy121** [comment]
> Let's start with one of the mods, for example taskbar-grouping. The problem for both is probably the same and is related to debug symbol downloading.
> 
> Please attach debug logs by following the instructions on the Troubleshooting page: https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work
> 
> > * Disable the mod.
> > * Go to the mod's Advanced tab.
> > * Set **Debug logging** to **Detailed debug logs**.
> > * Click on **Show log output**.
> > * Enable the mod.
> > * Verify that the mod doesn't work, copy the log and save it to a file.
> > * Set **Debug logging** back to **None**.

Indeed it does look like a problem with symbols.  Getting "HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND".  

How to fix this?  

Log attached below. 

[DebugViewConsole 1.8.0.102.txt](https://github.com/ramensoftware/windhawk-mods/files/15197501/DebugViewConsole.1.8.0.102.txt)

**Comment by m417z** [comment]
It seems that not only that Microsoft didn't publish symbols for the latest Windows build (22631.3527), they somehow managed to remove the symbols of the previous build, even though the symbols were definitely available earlier.

I still have the symbols on my computer, so as a temporary workaround, you can download the symbol files here:
[Windows-symbols-22631.3447.zip](https://github.com/ramensoftware/windhawk-mods/files/15197636/Windows-symbols-22631.3447.zip)

Just extract the archive and run `copy-symbols.bat`.

**Comment by nazzy121** [comment]
> It seems that not only that Microsoft didn't publish symbols for the latest Windows build (22631.3527), they somehow managed to remove the symbols of the previous build, even though the symbols were definitely available earlier.
> 
> I still have the symbols on my computer, so as a temporary workaround, you can download the symbol files here: [Windows-symbols-22631.3447.zip](https://github.com/ramensoftware/windhawk-mods/files/15197636/Windows-symbols-22631.3447.zip)
> 
> Just extract the archive and run `copy-symbols.bat`.

That fixed it, thank you!  Now, why would MS not publish symbols for future builds?  And even more concerning, why would they remove existing symbols from previous builds??   Does it mean someday if MS decides never to publish symbols for future builds then some Windhawk mods will simply stop working forever?

**Comment by m417z** [comment]
Great, I'm glad that it works now!

> Now, why would MS not publish symbols for future builds?

That's a great question. I tend to believe (and hope) that it's a mistake on their side. Of course, we can't know for sure. If Microsoft decides to stop publishing symbols, it doesn't mean that all is lost for Windhawk, there are alternative solutions (such as pattern matching), but it will make mods more difficult to develop and more likely to stop working after updates.

**Comment by nazzy121** [comment]
> Great, I'm glad that it works now!
> 
> > Now, why would MS not publish symbols for future builds?
> 
> That's a great question. I tend to believe (and hope) that it's a mistake on their side. Of course, we can't know for sure. If Microsoft decides to stop publishing symbols, it doesn't mean that all is lost for Windhawk, there are alternative solutions (such as pattern matching), but it will make mods more difficult to develop and more likely to stop working after updates.

I feel much relief knowing there are workarounds to this potential problem.  Windhawk has been great so far and I hope it continues.  Thank you again for all your help today.

**Comment by Sett17** [comment]
> It seems that not only that Microsoft didn't publish symbols for the latest Windows build (22631.3527), they somehow managed to remove the symbols of the previous build, even though the symbols were definitely available earlier.
> 
> I still have the symbols on my computer, so as a temporary workaround, you can download the symbol files here: [Windows-symbols-22631.3447.zip](https://github.com/ramensoftware/windhawk-mods/files/15197636/Windows-symbols-22631.3447.zip)
> 
> Just extract the archive and run `copy-symbols.bat`.
@m417z

This unfortunately doesn't seem to work for me. I am also on build `22631.3527`. Where does the hash in the path and filename come from, do I maybe need to change it?

**Comment by m417z** [comment]
@Sett17 Please post debug logs as instructed in my first comment in this issue.

**Comment by Sett17** [comment]
[TaskbarClockCustomization.log](https://github.com/ramensoftware/windhawk-mods/files/15199051/TaskbarClockCustomization.log)

Very similiar error but different hash on the filenames in the error

**Comment by m417z** [comment]
@Sett17 Unfortunately, there's no solution or workaround for build 22631.3527 (update KB5036980), only for 22631.3447. See the relevant issue here: https://github.com/ramensoftware/windhawk-mods/issues/640

**Comment by Sett17** [comment]
Ah, I didn't know that option was getting preview releases. So just waiting for the symbols to be published and/or the next update. Thanks tho

**Comment by m417z** [comment]
I've updated some of the popular mods with a temporary workaround. The updated mods should work with Windows 11 versions 22631.3447 and 22631.3527. For details, see the following blog post:
https://ramensoftware.com/windhawk-and-symbol-download-errors

**Comment by sammykip** [comment]
> ## Update - workaround
> As a temporary workaround, you can download the symbol files here: [Windows-missing-symbols.zip](https://github.com/ramensoftware/windhawk-mods/files/15199280/Windows-missing-symbols.zip)
> 
> Just extract the archive, go to the folder that matches your Windows version and run `copy-symbols.bat`.
> 
> ## Original comment
> Let's start with one of the mods, for example taskbar-grouping. The problem for both is probably the same and is related to debug symbol downloading.
> 
> Please attach debug logs by following the instructions on the Troubleshooting page: https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work
> 
> > * Disable the mod.
> > * Go to the mod's Advanced tab.
> > * Set **Debug logging** to **Detailed debug logs**.
> > * Click on **Show log output**.
> > * Enable the mod.
> > * Verify that the mod doesn't work, copy the log and save it to a file.
> > * Set **Debug logging** back to **None**.

my windows is 22635.2915,  your fix doesnt include a folder for such and i;m facing the same problem, please assist
