### ISSUE TITLE
Disable grouping on taskbar - bug with pinned items

### ISSUE THREAD

**Issue by theFireProject** [ramensoftware/windhawk-mods#644]
### Problem Description

Windows Explorer is pinned to the taskbar but the wrong icon is displayed.

![image](https://github.com/ramensoftware/windhawk/assets/61639215/6087869f-06c7-404a-887d-724e16a29bed) <- Wrong icon

![image](https://github.com/ramensoftware/windhawk/assets/61639215/587c69dd-d9ba-499c-815a-0ac45e6f7e2f) <- Correct icon

It is caused by the `Use window icons` option. Some programs like Windows Explorer display a window icon that is different from their program icon.
- The **program icon** is the icon of the explorer.exe file. (see second screenshot)
- The **window icon** of an Explorer window is the icon of your current folder. In this case it's the icon of `This PC` because I opened `This PC` and then closed the window.

The icon from the last opened folder is displayed on the taskbar, even if no Explorer window is open anymore.

In my opinion window icons like the `This PC` icon should only be shown when an Explorer windows is open. When no Explorer window is open, the pinned icon should be the program icon. Not the icon of the last opened folder.

### Settings

The `Use window icons` option is enabled and `Pinned items mode` is set to `Running items replace pinned items`.

**Comment by m417z** [comment]
Thanks for reporting, should be fixed in version 1.3.3.
