### ISSUE TITLE
Middle click to close on the taskbar no longer working

### ISSUE THREAD

**Issue by Gravarty** [ramensoftware/windhawk-mods#651]
This is a repost of this bug report because it was assumed i was Pre-Release software which isn't true. The Windows 11 version i was using back then and now is the default "Stable, Release" version you can get from the official Microsoft RTM ISO site.

https://github.com/ramensoftware/windhawk-mods/issues/540

**Comment by m417z** [comment]
Currently there's a problem which caused the required symbol files to become unavailable. For details, see [the relevant blog post](https://ramensoftware.com/windhawk-and-symbol-download-errors).

I've just published an update, version 1.0.6, which implements a workaround. If you’re using Windows 11 version 22631.3447 or 22631.3527, it should work for you. Please update and let me know if it fixes the problem.

**Comment by Gravarty** [comment]
Nice, that finally fixed it, thanks!
