### ISSUE TITLE
[Taskbar minimize/restore on scroll] when I scroll then scroll backwards. the preview seems buggy

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#661]
when I scroll then scroll backwards. the preview seems buggy

https://github.com/ramensoftware/windhawk-mods/assets/142233342/3197dd3c-f2ee-449f-8dcd-44f36987a615

**Comment by m417z** [comment]
Why did you close it? I can reproduce it with some apps, such as Windhawk and VSCode, but not most others, such as Chrome and Explorer. I'll try to find a solution when I have time.

**Comment by m417z** [comment]
Fixed in version 1.0.7, the thumbnail is now refreshed after scrolling.
