### ISSUE TITLE
[taskbar-icon-size] value reset button, automatic Explorer restart 

### ISSUE THREAD

**Issue by pimozone** [ramensoftware/windhawk-mods#663]
mod title: Taskbar height and icon size
mod's auther: @m417z 

It would be great to have value reset button and automatic Explorer restart features.
They will save much time of many people

**Comment by m417z** [comment]
Taskbar height and icon size v1.2.8 now shows a restart prompt when the taskbar button width is changed in settings. I assume that's what you meant.
