### ISSUE TITLE
[Large Taskbar Icons] Secondary taskbar height

### ISSUE THREAD

**Issue by m417z** [ramensoftware/windhawk-mods#68]
Reported on Discord ([link](https://discord.com/channels/923944342991818753/923955312808038451/1050146244762279937)):

> I am having an issue where the taskbar on my secondary display is ignoring the taskbar height set with the Large Taskbar Icons mod
>
> ![image](https://user-images.githubusercontent.com/4129781/206864488-be790795-3cf3-4a8c-912a-fb591fe15780.png)
> 
> ![image](https://user-images.githubusercontent.com/4129781/206864494-0d6c7c97-11b0-4bd1-bedc-52879cd392db.png)

**Comment by MarceloZapatta** [comment]
I'm having a similar issue that my secondary display gets a wrong alignment of icons and a margin has below (primary monitor is at right):
![image](https://user-images.githubusercontent.com/39474221/224833784-8a35516f-98f0-47bc-879d-3c7a69ebadc7.png)

**Comment by m417z** [comment]
Fixed in version 1.1 of the mod.
