### ISSUE TITLE
Taskbar Labels for Windows 11 not working after 2024-05 Windows update KB5037771

### ISSUE THREAD

**Issue by iknownoth1ng** [ramensoftware/windhawk-mods#683]
![image](https://github.com/ramensoftware/windhawk-mods/assets/54530758/58a0f175-ab69-4413-ad32-cbc1158a9e86)

**Comment by m417z** [comment]
Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by iknownoth1ng** [comment]
It worked! Thanks! 
The automatic startup I set only doesn't work when the computer is turned on.

**Comment by m417z** [comment]
I suspect that it didn't work because symbol files weren't available for the first couple of hours after the update on Tuesday. If you see that the issue happens constantly on each boot, please let me know.

**Comment by iknownoth1ng** [comment]
The situation has persisted for two days, following an automatic update to Windows 11.

**Comment by m417z** [comment]
Did you reboot or disable the mod during these two days?

**Comment by iknownoth1ng** [comment]
No, I thought it would be like before, just wait a few days for the mod to update, but I can't wait

**Comment by m417z** [comment]
Then it makes sense, the symbols became available, but the mod had to be re-enabled to start working. I'll think about improving this in the future, maybe to keep trying to load the symbols if they're missing.
