### ISSUE TITLE
[taskbar-icon-size] Stopped working after latest windows update

### ISSUE THREAD

**Issue by eggfooyoung** [ramensoftware/windhawk-mods#687]
Mod identifier: taskbar-icon-size
Mod author: @m417z 

I recently reformatted my setup and updated to the latest windows update (not insider builds), but for some reason taskbar-icon-size stopped working even though the other windhawk mods I have installed alongside this mod that hooks to the taskbar like taskbar and start menu styler still works.

I tried excluding windhawk from windows security, the only antivirus running on my setup. Closed all other programs that may also be hooking to the taskbar like roundedTB and reopened windhawk with only taskbar-icon-size enabled, but, to no avail.

Current windows version is: 23H2 (Build 22631.3593)

Here's the debug log, hope this can be fixed.
[Taskbar_icon_Log_.txt](https://github.com/ramensoftware/windhawk-mods/files/15368876/Taskbar_icon_Log_.txt)

**Comment by m417z** [comment]
Thanks for the log. Can you upload the following file?
```
C:\Windows\System32\Taskbar.dll
```

**Comment by maylique** [comment]
[Taskbar.zip](https://github.com/ramensoftware/windhawk-mods/files/15369685/Taskbar.zip)

Same for me, but im on 22631.3668 (May 28th Release Preview update) and the mods which doesnt work are: taskbar-icon-size, taskbar-clock-customization and taskbar-labels. Taskbar-Styler is working. 

Thank you for your work btw <3

**Comment by eggfooyoung** [comment]
Here's mine, thanks for the quick reply.

[Taskbar.zip](https://github.com/ramensoftware/windhawk-mods/files/15369867/Taskbar.zip)

**Comment by m417z** [comment]
@eggfooyoung it seems that this file was edited, it's similar to the original Taskbar.dll file from Microsoft, but it's not signed and has different resources. My guess is that you edited it to replace some icons. Is that right?

Due to the way symbol retrieval works, the editing causes the workaround mechanism (see https://github.com/ramensoftware/windhawk-mods/issues/685) to stop working.

If that's right, the best solution is to avoid modifying system files (which is a bad idea for other reasons, too). For icon replacement, you can use the [Resource Redirect](https://windhawk.net/mods/icon-resource-redirect) mod instead.

**Comment by m417z** [comment]
@maylique Due to a Microsoft maintenance, some symbol files are unavailable. As a result, some mods temporary don't work on preview builds.
For details, see https://github.com/ramensoftware/windhawk-mods/issues/685.

**Comment by eggfooyoung** [comment]
I haven't actually edited it to replace the icons, although I did install Rectify11 and perhaps it may have changed the dll file together with the other patches it does to the explorer and system files. Thanks!

**Comment by m417z** [comment]
@eggfooyoung a workaround that might work is opening regedit at:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Windhawk\Engine\ModsWritable\taskbar-icon-size\LocalStorage
```
And modifying `symbol-cache-taskbar.dll` to replace the `1#1878917014#3756032#` prefix with `1#1878917014#3637248#`.

**Comment by eggfooyoung** [comment]
Just tried it and it worked wonderfully, thanks for your great work!
