### ISSUE TITLE
middle click to close programs on taskbar not working 

### ISSUE THREAD

**Issue by mato200** [ramensoftware/windhawk-mods#69]
Middle click to close on the taskbar
"Close programs with a middle click on the taskbar instead of creating a new instance"
not working, other mods are working
Also, using explorer patcher and TranslucentTB programs if thats important. Latest Win11

**Comment by m417z** [comment]
Support for Explorer Patcher, and generally for using the old taskbar on Windows 11, was added in version 1.0.2 of the mod. Please update the mod and try it. Note that you have to enable the relevant option in the mod's settings.
