### ISSUE TITLE
[Disable grouping on the taskbar] Pinned icons disappear on virtual desktop

### ISSUE THREAD

**Issue by tenthousandcoffins** [ramensoftware/windhawk-mods#690]
**Mod**
Disable grouping on the taskbar

**Author**
@m417z

**Description**

I've noticed that the pinned icons disappear on the virtual desktop when I have more than one instance open.
I didn't notice anything when I just had single instance. Also, it's not limited to Edge case (pun intended), but happens with any other multiple instances such as File Explorer.

This is my Desktop 1. Note that I have two Edge (these are pinned to taskbar) windows opened.
![dt1](https://github.com/ramensoftware/windhawk-mods/assets/170146399/7f078654-f72c-4287-950f-aa7023b4a0af)

I switch to Desktop 2. The pinned Edge icon disappeared from the taskbar.
![dt2](https://github.com/ramensoftware/windhawk-mods/assets/170146399/999a3d98-4a1a-4c99-8c2d-108616ef32dd)

This is when I switch back to Desktop 1. The icon orders are not preserved and moved to the end of the taskbar.
Tried using [Virtual Desktop Preserve Taskbar Order] for this case, but it did not help.
![dt3](https://github.com/ramensoftware/windhawk-mods/assets/170146399/3544d892-96cb-49e9-a94c-b91b6b9004e6)

**Comment by m417z** [comment]
I spent some time trying to fix it, more time than I hoped.
Here's a version of the mod with the changes. Please install it and try experimenting and doing crazy stuff as much as you can. Let me know if you find bugs like the one reported in this issue.
https://github.com/m417z/my-windhawk-mods/blob/e16c05b77bd71bb8850e18b01f42305002c983db/mods/taskbar-grouping.wh.cpp

To install it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the content from the link above, click "Compile Mod", then "Exit Editing Mode".

**Comment by m417z** [comment]
I made some improvements in version 1.3.3, hopefully this issue is fixed. If you see the bug with the new version, please let me know.
