### ISSUE TITLE
[Classic Explorer navigation bar] Missing address bar after installing latest 24H2 IoT LTSC build

### ISSUE THREAD

**Issue by cawfeechino** [ramensoftware/windhawk-mods#700]
![image](https://github.com/ramensoftware/windhawk-mods/assets/15659900/f63f138b-04e0-4efc-b0df-8641f0ad55ff)
![image](https://github.com/ramensoftware/windhawk-mods/assets/15659900/d8ff7f63-2947-41b3-bd9b-15f99758ec3b)

Attached is what I see visually, along with the log output from Windhawk.

@m417z 

Windows 11 IoT Enterprise LTSC
Version 24H2
OS Build 26100.560

**Comment by m417z** [comment]
Thanks for the report. I don't have this Windows version, but I tried to fixed it based on your logs. Please try the fix and let me know if it works:
https://github.com/m417z/my-windhawk-mods/blob/e6f229faaf5836de4ac0d4e041b38b6d9cc26d3a/mods/explorer-frame-classic.wh.cpp

To install it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the content from the link above, click "Compile Mod", then "Exit Editing Mode".

**Comment by cawfeechino** [comment]
Confirmed it works

**Comment by m417z** [comment]
Great, thanks for confirming. I pushed a new version with the update.
