### ISSUE TITLE
'pinned items remain in place' doesn't work anymore | 'Disable grouping on the taskbar' Mod issue

### ISSUE THREAD

**Issue by Fazyfaz** [ramensoftware/windhawk-mods#725]
@m417z 
Winver: Win11 version 23H2 (OS build 22631.3672)
Mod name: Disable grouping on the taskbar
Version: 1.3.3
Setting: Pinned items remain in place
Other Windhawk mod: *attached in a screenshot
![240610_JiDx5Js3rj](https://github.com/ramensoftware/windhawk-mods/assets/172136320/1255ecab-cf3c-43ce-8930-40e38a557b03)

Issue: *as shown on this GIF
![240610_J7fai58Gj2](https://github.com/ramensoftware/windhawk-mods/assets/172136320/3f320675-1b4e-4bef-ae00-3522bd5c4a95)

Details: Click any pinned app from taskbar (in this example: file explorer & google chrome app). Instead of item remaining in place and create a new window, it instead acts like "running items replaced pinned items". But the difference is that the newly opened app moved to the right of every app on the taskbar.   When you close the first window of each app (the one on the left), pinned but unopened item logo re-appears at the end of the taskbar for a moment. As if it was confused. It disappeared again if you click on an opened version of the app (just regular left click, not right click). After you close every running window of the app, the pinned item icon comes back. But it repositioned at the end of the taskbar (on the right). Which you then have to re-order everytime.

How it happened: I think issue occured after I upgraded the mod from 1.3.2 to 1.3.3 before that, I remember the mod works as its intended (unopened pinned items stayed in place on the left, no matter how many times I click on it to open a new window of that app).

Sidenote: I want to try downgrading this specific mod to the previous 1.3.2 version to see if the issue persist, but have no idea how to do that yet. Also, the issue is only specific to the "Pinned items remain in place" setting. The other setting (running items replace pinned items) works just fine. But I want to keep my pinned apps in place.

**Comment by rumifloss** [comment]
Been facing the exact same issue here since I updated the mod to 1.3.3.

**Comment by mateusfn98** [comment]
Your windows taskbar personalization is set to "Never" in "Combine Taskbar buttons and hide labels"?

**Comment by Fazyfaz** [comment]
@mateusfn98 My windows taskbar setting in "Combine Taskbar buttons and hide labels" is set to "always" because I like it that way. Don't care for labels. But even when I tried changing it to "never", the issue still persist. Pinned items failed to remain in place.

**Comment by m417z** [comment]
Thank you for the detailed report. Should be fixed in version 1.3.4.
