### ISSUE TITLE
[Taskbar Height and Icon Size] restart prompt fails to start explorer

### ISSUE THREAD

**Issue by jmain33** [ramensoftware/windhawk-mods#727]
@m417z
Restarting from the prompt when changing the button width closes out explorer and leaves everything blacked out (both the desktop and taskbar), not bringing back any of the GUI elements for Windows 11.

**Comment by m417z** [comment]
The restart option just runs the following command:
```cmd
cmd.exe /c "taskkill /F /IM explorer.exe & start explorer"
```

If you open cmd and run the `taskkill /F /IM explorer.exe & start explorer` command, does it work? If not, are you getting any errors?

**Comment by jmain33** [comment]
Doing precisely as you instructed: On my system, running that exact command; closed explorer and relaunched it as would be expected.

This is the result from the cmd entry.
![Screenshot 2024-06-12 172222](https://github.com/ramensoftware/windhawk-mods/assets/364460/357ec1f2-24d0-43d7-ad29-cc9b4a93d1d6)

 

When doing this through the command prompt, there was a delay of less than 2 seconds before the GUI reappeared. When the mod executes those instructions the visuals never come back - the entire screen stays black... once this has occurred (with the screen still blacked out...) when I once again run the command you provided, cmd says explorer.exe cannot be found.
![Screenshot 2024-06-12 174521](https://github.com/ramensoftware/windhawk-mods/assets/364460/efb2c7ed-35a6-4828-980f-b2101c07199f)

 
Yet in this very condition launching explorer from the task manager dialogue works just fine.

Here is what the logs collected of the TH&IS mod restart attempt: [DebugViewConsole 1.8.0.102 Failed Restart of Explorer.txt](https://github.com/user-attachments/files/15811243/DebugViewConsole.1.8.0.102.Failed.Restart.of.Explorer.txt)

**Comment by m417z** [comment]
Not sure why there would be a difference between cmd and the mod running the same command. What if you run (Win+R) this command:
```cmd
cmd.exe /c "taskkill /F /IM explorer.exe & start explorer"
```
Does it work?

**Comment by jmain33** [comment]
Doing that fails to restart explorer, just like the Windhawk mod; then, I went back and executed the instructions in cmd.exe itself, this time without choosing run as administrator, and it failed just like all the other methods. So it seems like this is very likely about system privileges.

**Comment by m417z** [comment]
Hmm, maybe there's some policy on your computer which forbids a regular user from running explorer.exe. Do you have any security software such as an antivirus?

Other than that, I'm not sure why it wouldn't work, and what can be done in the mod to fix that. If you have an idea of how to reproduce the issue, let me know.

**Comment by jmain33** [comment]
I have security software installed (Malwarebytes & Trend Micro), but stopped paying for them a while a go since they're not really useful to cautious users; and disabled all their startup entries and Windows services. So it's just the standard Windows Security that runs on my PC, the other applications don't have any active processes.

Other than that, the only tweaking I use is Winaero Tweaker. Though, nothing that I've changed with it (it does list everything that it has made a change to) should have effected my admin privileges?! I only have one user account and it is listed as the default administrator account, so I'm at a loss for now.

_I also haven't enabled "Require UAC elevation for running Windhawk", so Windhawk should still have admin privileges. Anyway, from the trouble shooting you had me do, this clearly isn't about Windhawk's settings._

**Comment by Freezekiss** [comment]
bro, i have same problem like that guy, but on the Windows that I have, it is on the Windows 11 24h2 version

**Comment by m417z** [comment]
Restarting explorer is no longer required in version 1.2.15 of the mod, and so the restart prompt was removed.
