### ISSUE TITLE
[Vertical Taskbar for Windows 11] Move taskbar to the right

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#731]
I just wonder if there is a way to add the possibility of placing the taskbar at the top and to the right

**Comment by m417z** [comment]
Thanks for the suggestion, this is planned. For moving taskbar to the top, there's a dedicated issue (https://github.com/ramensoftware/windhawk-mods/issues/166), that's also planned as a separate mod.

**Comment by m417z** [comment]
Done in version 1.2.
