### ISSUE TITLE
Office 365 apps won't start if Windhawk is running

### ISSUE THREAD

**Issue by nazzy121** [ramensoftware/windhawk-mods#732]
Documenting here, in case anyone runs into this issue.  

With the latest Microsoft/Office 365 update version 2405 on Current Channel, none of the apps  (Word, Excel, Outlook etc) will run while Windhawk is enabled.  When Windhawk is disabled the Office apps work fine.   

The solution is to exclude Office app executables in Windhawk.  I don't know if this should be filed as a bug or feature request, but it would be nice if Windhawk can automatically exclude/ignore Office processes without user having to do it themselves.  

Steps:  Go to "Settings" -> "Advanced Settings" -> "More Advanced Settings" -> "Process exclusion list"  then copy/paste the below entries, then "Save & Restart Windhawk".  

C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
C:\Program Files\Microsoft Office\root\Office16\excelcnv.exe
C:\Program Files\Microsoft Office\root\Office16\XLICONS.exe
C:\Program Files\Microsoft Office\root\Office16\GRAPH.EXE
C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE
C:\Program Files\Microsoft Office\root\Office16\WORDICON.EXE
C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.exe
C:\Program Files\Microsoft Office\root\Office16\MISC.exe
C:\Program Files\Microsoft Office\root\Office16\MSACCESS.exe
C:\Program Files\Microsoft Office\root\Office16\MSPUB.exe
C:\Program Files\Microsoft Office\root\Office16\WORDCONV.exe
C:\Program Files\Microsoft Office\root\Office16\ONENOTEM.exe
C:\Program Files\Microsoft Office\root\Office16\ONENOTE.exe
C:\Program Files\Microsoft Office\root\Office16\PPTICO.exe
C:\Program Files\Microsoft Office\root\Office16\ACCICONS.exe

**Comment by Undisputed00x** [comment]
Issue is already known https://github.com/ramensoftware/windhawk/issues/198

**Comment by nazzy121** [comment]
> Issue is already known [ramensoftware/windhawk#198](https://github.com/ramensoftware/windhawk/issues/198)

Ah, didn't see it, thank you.   It's nice we can use asterisk to exclude the entire path.

**Comment by nazzy121** [comment]
> Issue is already known [ramensoftware/windhawk#198](https://github.com/ramensoftware/windhawk/issues/198)

Ah, didn't see it, thank you. It's nice we can use asterisk to exclude the entire path.
