### ISSUE TITLE
Latest 1.41 version of windhawk causes microsoft 365 doesn't work!!!!!!

### ISSUE THREAD

**Issue by yzhzhkok** [ramensoftware/windhawk-mods#734]
Latest 1.41 version of windhawk causes microsoft 365 doesn't work!!!!!!
When i install the 1.41 version of windhawk the  microsoft 365 doesn't work!!!!

**Comment by m417z** [comment]
It’s a known issue. I haven’t had the chance to look at it yet, but for now, you can add office to the exclusion list, see:
https://github.com/ramensoftware/windhawk/issues/198#issuecomment-2169560663

Thanks for reporting. Closing as a duplicate.
