### ISSUE TITLE
[Windows 11 Start Menu Styler] doesn't load [Win11 Enterprise 10.0.22631.3737]

### ISSUE THREAD

**Issue by thepsyborg** [ramensoftware/windhawk-mods#747]
No errors, no debug log output, it just never appears in "Loaded Mods", or has any effect. I have:

- Restarted Windhawk, Start, and Windows Explorer
- Removed and reinstalled Windows 11 Start Menu Styler
- Rebooted
- Checked on both administrator and non-administrator accounts, the latter both with and without UAC elevation
- Checked multiple themes, including empty.
- Checked without DisplayFusion or TranslucentTB active just in case, although they certainly _used_ to be compatible.

Happy to try anything else if it would help.

Edit: tagging mod author @m417z

**Comment by m417z** [comment]
Are you using the standard or the portable Windhawk version?
Do other mods work?

We can try enabling all Windhawk logs and check for error messages. First, download and run DebugView. Then, in Windhawk, make sure the mod is enabled, go to settings, then "More advanced settings", then change both verbosity values to "Error" and save. Windhawk will be restarted. After Windhawk is restarted, copy the logs from DebugView and post them here.

**Comment by thepsyborg** [comment]
> Are you using the standard or the portable Windhawk version? Do other mods work?

Standard version. Other mods work. (I mean, I dunno about _every_ mod, but all the ones I'm using work (that being Taskbar Volume Control and Disable grouping on the taskbar).

> We can try enabling all Windhawk logs and check for error messages. First, download and run DebugView. Then, in Windhawk, make sure the mod is enabled, go to settings, then "More advanced settings", then change both verbosity values to "Error" and save. Windhawk will be restarted. After Windhawk is restarted, copy the logs from DebugView and post them here.

````[11964] [WH] ERR: 00000241
[13080] [WH] ERR: 00000241
[17696] [WH] ERR: 00000241
[13232] [WH] [LazyInitialize]: Initialization failed: status: Access is denied.: "C:\ProgramData\Windhawk\Engine"
[8892] [WH] ERR: 00000241
[34988] [WH] ERR: 00000241
[62416] [WH] ERR: 00000241
[60108] [WH] ERR: 00000241
[61636] [WH] ERR: 00000241
[63340] [WH] ERR: 00000241

**Comment by m417z** [comment]
> [13232] [WH] [LazyInitialize]: Initialization failed: status: Access is denied.: "C:\ProgramData\Windhawk\Engine"

I assume that 13232 is the process id of StartMenuExperienceHost.exe, right?

> The permissions on C:\ProgramData\Windhawk\Engine are:
> [...]

That's the problem, the folder is missing [access for application packages](https://i.imgur.com/NUA7vuQ.png). The access should be added during setup. On the other hand, the library is loaded, so I assume that permissions were set correctly for `C:\Program Files\Windhawk\Engine`. Can you verify in properties?

In the list of things that you tried, you didn't list re-installing Windhawk? Can you try to reinstall is? The permissions should be set again by the installer.
