### ISSUE TITLE
[Windows 11 Start Menu Styler] Recommended section sub text and recent files comes in shifted to the left when using SidebySide1

### ISSUE THREAD

**Issue by dburow03** [ramensoftware/windhawk-mods#751]
No errors, no debug log output, the recommended section issue is a visual bug that does not output an error log

Restarted Windhawk, Start, and Windows Explorer
Removed and reinstalled Windows 11 Start Menu Styler
Rebooted both multiple times

Checked on multiple devices running different OS versions below:
Surface Laptop Studio running 24H2 Pro Insider 26100
Lenovo P16 Gen 2 running 23H2 Enterprise 22621 

tagging mod author @m417z

![Screenshot 2024-06-24 104950](https://github.com/ramensoftware/windhawk-mods/assets/171621576/ec9ceb69-96ff-4e1b-a228-358bab2dff24)

**Comment by m417z** [comment]
Fixed in Windows 11 Start Menu Styler v1.1.5.
