### ISSUE TITLE
[Aerexplorer] These symbols aren't loading [19044.4529] any fix?

### ISSUE THREAD

**Issue by SeaMantis** [ramensoftware/windhawk-mods#755]
![Capture](https://github.com/ramensoftware/windhawk/assets/173709810/3e4a6bc0-e45d-465e-90c4-03b2b0d674e8)

**Comment by m417z** [comment]
Tagging @aubymori, the mod author.

**Comment by SeaMantis** [comment]
> Tagging @aubymori, the mod author.

oh I thought it was a windhawk issue because of the symbols not loading. I didn't consider it to be a mod issue. Or maybe it's an issue with the fact that my pc crashed when the symbols were just loading, so it might've not loaded correctly. Even after reinstalling it.

**Comment by m417z** [comment]
It could be a Windhawk issue, but you didn't provide any reason to assume that at this point.

Normally "Unloaded" means that the mod returned `FALSE` from `Wh_ModInit`, indicating that the mod either failed to initialize or isn't relevant for the target process. The first step would be to understand why `FALSE` is returned.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by SeaMantis** [comment]
sure here's the log: 
[debug.txt](https://github.com/user-attachments/files/15987521/debug.txt)

**Comment by m417z** [comment]
Here's the error:
```
17:24:07.646 12648 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::FindFirstSymbol3
17:24:07.647 12648 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Module: 00007FF81D6E0000
17:24:07.647 12648 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Path: C:\Windows\SYSTEM32\windows.storage.dll
17:24:07.648 12648 explorer.exe  [WH] [LoadedMod::FindFirstSymbol3]: Version: 10.0.19041.4522
17:24:07.650 12648 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  BYINDEX: 0x1
17:24:07.652 12648 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  PATH: C:\ProgramData\Windhawk\Engine\Symbols\Windows.Storage.pdb\06457EFAFE02A5D27AA8B69B51A831C51\Windows.Storage.pdb
17:24:07.653 12648 explorer.exe  [WH] [`anonymous-namespace'::LogSymbolServerEvent]: SYMSRV:  RESULT: 0x00000000
17:24:07.655 12648 explorer.exe  [WH] [LoadedMod::LogFunctionError]: Mod aerexplorer error: engine\symbol_enum.cpp(201)\windhawk.dll!00007FF8021CCD74: (caller: 00007FF8021BA66E) Exception(2) tid(2bec) 806D0005 
17:24:07.655 12648 explorer.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::FindFirstSymbol3
17:24:07.655 12648 explorer.exe  [WH] [aerexplorer] [323:HookSymbols]: Wh_FindFirstSymbol failed
17:24:07.655 12648 explorer.exe  [WH] [aerexplorer] [3157:Wh_ModInit]: Failed to hook one or more symbol functions in windows.storage.dll
```

Can you post the following file from your computer?
```
C:\ProgramData\Windhawk\Engine\Symbols\Windows.Storage.pdb\06457EFAFE02A5D27AA8B69B51A831C51\Windows.Storage.pdb
```

**Comment by SeaMantis** [comment]
The file is too large to upload it here... i gotta try something else

**Comment by m417z** [comment]
You can upload it to Google Drive or a similar service, and post a link.

**Comment by SeaMantis** [comment]
okay, I managed to fix it by updating windows and reloading the symbols
