### ISSUE TITLE
WindHawk Mod "disable grouping on taaskbar" v1.3.4 not working..

### ISSUE THREAD

**Issue by HumanMus1c** [ramensoftware/windhawk-mods#758]
WindHawk Mod "disable grouping on taaskbar" v1.3.4.
Windows 11 Pro 23H2 ‎22631.3737 Windows Feature Experience Pack 1000.22700.1009.0
v1.3.3 was normal.
![recording](https://github.com/ramensoftware/windhawk-mods/assets/46023154/cbcff113-33ed-4dcf-ba6a-1731ec3a7efc)

_Originally posted by @HumanMus1c in https://github.com/ramensoftware/windhawk-mods/issues/729#issuecomment-2168473687_

**Comment by m417z** [comment]
As I asked you previously, did you close and re-open the windows after enabling the mod?

If you did, please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by HumanMus1c** [comment]
I did, even restart explorer.exe process after disable/enable the mod. Also did Restart the Windows system after disable/enable the mod.
[DebugViewConsole 1.8.0.102.txt](https://github.com/user-attachments/files/16026325/DebugViewConsole.1.8.0.102.txt)

**Comment by m417z** [comment]
You didn't enable **Detailed debug logs**. Please follow the instructions. Without it I can't see your mod settings, for example.

Also, please start logging when Steam isn't open, then open two windows of Steam, and only then stop logging. So:

* Disable the mod.
* Go to the mod's Advanced tab.
* Set **Debug logging** to **Detailed debug logs**.
* Click on **Show log output**.
* Enable the mod.
* Verify that the mod doesn't work.
  * 👉 Here, open two Steam windows.
  * Then, copy the log and save it to a file.
* Set **Debug logging** back to **None**.

Also, does it only happen with Steam? Or does it happen with all programs?

**Comment by HumanMus1c** [comment]
[030128.001 7780 explorer.exe  [WH] .txt](https://github.com/user-attachments/files/16035742/030128.001.7780.explorer.exe.WH.txt)
![recording](https://github.com/ramensoftware/windhawk-mods/assets/46023154/be035a8e-ce4e-4358-8684-916010755e31)

**Comment by m417z** [comment]
This is the reason, you chose to exclude all programs:

![image](https://github.com/ramensoftware/windhawk-mods/assets/4129781/cfec10ff-0c64-45d2-b5ef-20c825262cda)

**Comment by HumanMus1c** [comment]
Sorry for my stupid.
