### ISSUE TITLE
[Windows-11-Taskbar-Styler] theme cannot be rendered rightly

### ISSUE THREAD

**Issue by crazy-zxx** [ramensoftware/windhawk-mods#797]
https://github.com/ramensoftware/windhawk-mods/blob/b16412c8ab6de3303ecb179ddcb39a2fe8b28e25/mods/windows-11-taskbar-styler.wh.cpp#L45-L47

In the **1.3.6** version of the Windows-11-Taskbar-Styler module, the theme of **Translucenttaskbar** cannot be rendered rightly, making the task bar show a **black background**!

This theme can be rendered rightly in version 1.3.5!

**Comment by m417z** [comment]
Thanks for reporting. It's an issue with the theme, not with the mod, I moved the issue here, let's continue the discussion in the moved issue: https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/46
