### ISSUE TITLE
[BUG] Taskbar Clock Customization does not work after updating to 1.0.6

### ISSUE THREAD

**Issue by Trixlight** [ramensoftware/windhawk-mods#81]
The mod does not work after updating to 1.0.6. I tried to restarting explorer.exe, the computer etc.

I'm currently using Windows 11, build 22610.1.

I followed the instructions from #37, here is the result:
![image](https://user-images.githubusercontent.com/33410668/210750771-cbd34a47-7d13-46cf-a69e-a8ed69d4280d.png)

**Comment by m417z** [comment]
22610 is a dev build from April. Dev builds aren't officially supported, but you can probably make it work by finding "22621" in the code and replacing it with "22610", as your build is more similar to Windows 11 22H2 than to 21H2	.

**Comment by m417z** [comment]
Yeah, in the previous version of the mod I didn't look at the OS version number, and instead deduced it from the libraries that are available in the system. That supported a wider range of builds, but I changed it for consistency with other code and mods, and didn't think it will cause issues in practice.

Perhaps it's better to treat anything newer than build 22000 (Windows 11 21H2 ) as 22H2. I'll look into changing it in the next update of the mod.
