### ISSUE TITLE
taskbar-icon-size mod fails to compile

### ISSUE THREAD

**Issue by Amon-san** [ramensoftware/windhawk-mods#853]
taskbar-icon-size.wh.cpp version 1.2.10
from the repository https://github.com/m417z/my-windhawk-mods/tree/main/mods
by @m417z 
using windhawk 1.5.1
fails to compile.
last known good version was 1.2.6 (i think).
tried removal and fresh install of 1.2.10 but didn't work.
Running Windows 11 Pro 23H2 (22631.3958) Windows Feature Experience Pack 1000.22700.1026.0
no idea how to get debug logs. i'm no programmer, but i try to report as many details as i can.

error message as follows:

> In file included from <built-in>:480:
> <command line>:11:9: warning: 'WINVER' macro redefined [-Wmacro-redefined]
>    11 | #define WINVER 0x0605
>       |         ^
> <command line>:3:9: note: previous definition is here
>     3 | #define WINVER 0x0A00
>       |         ^
> In file included from c:\ProgramData\Windhawk\EditorWorkspace\mod.wh.cpp:77:
> In file included from c:/Program Files/Windhawk/Compiler/include/winrt/Windows.Foundation.h:6:
> In file included from c:/Program Files/Windhawk/Compiler/include/winrt/base.h:10:
> In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/algorithm:1794:
> In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/copy.h:12:
> In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/copy_move_common.h:14:
> In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__algorithm/unwrap_range.h:19:
> In file included from c:/Program Files/Windhawk/Compiler/include/c++/v1/__utility/pair.h:17:
> c:/Program Files/Windhawk/Compiler/include/c++/v1/__fwd/get.h:18:10: fatal error: '__tuple/tuple_element.h' file not found
>    18 | #include <__tuple/tuple_element.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning and 1 error generated.

**Comment by m417z** [comment]
The solution is to reinstall Windhawk, see https://github.com/ramensoftware/windhawk-mods/issues/833
Just download the setup from https://windhawk.net/, run it and choose "Reinstall", it should solve the problem.
