### ISSUE TITLE
Taskbar Clock Customization - Day of Year

### ISSUE THREAD

**Issue by KuleRucket** [ramensoftware/windhawk-mods#866]
In my industry (space systems), the time format often uses a date format including the day of year starting from 1st Jan in the format YYYY-DDDThh:mm:ss. E.g. 2024-201T00:00:00. In the space industry this is known as CCSDS ASCII TIME CODE B from https://public.ccsds.org/Pubs/301x0b4e1.pdf

So I always need a quick way to know what the current day number is. Is it possible to add a %daynum% tag to be used, similar to %weeknum%. I was previously using T-Clock for this but it no longer works in Windows.

@m417z

**Comment by KuleRucket** [comment]
This was pretty straightforward to using the first part of CalculateWeeknumIso(). If I can get my fork to link I can submit it as a PR.

**Comment by m417z** [comment]
Added in version 1.4.
