### ISSUE TITLE
[BUG] There is a problem with the icon display of the "Disable grouping on the taskbar"

### ISSUE THREAD

**Issue by TomIsFat** [ramensoftware/windhawk-mods#88]
Example with the Google Chrome extension: Bitwarden
![图片](https://user-images.githubusercontent.com/76768214/214756043-5943a8f8-0149-4a8d-8f49-d485040df48e.png)

When the mod is turned on, the icon on the taskbar looks like this, replaced by the Google Chrome icon
![图片](https://user-images.githubusercontent.com/76768214/214755473-eb1e1109-e716-4ca4-a17f-d0876e69b668.png)

But after closing the mod and restarting the taskbar, the icon in the taskbar looks like this, which is the original one
![图片](https://user-images.githubusercontent.com/76768214/214755374-39d14902-8342-44ed-924f-34b25d5e1a8e.png)

Maybe the latter is better

**Comment by m417z** [comment]
Should be fixed in version 1.2.

**Comment by m417z** [comment]
> Maybe the latter is better

Maybe... in version 1.2.1, you can choose the behavior you prefer in the settings.
