### ISSUE TITLE
Vertical Taskbar for Windows 11 - Rotate labels for taskbar items along with the icons - @m417z 

### ISSUE THREAD

**Issue by GentlePurpleRain** [ramensoftware/windhawk-mods#886]
I like to have a vertical taskbar specifically because I want labels visible for each item on the taskbar, and that takes up too much room on a horzontal taskbar.  But when I enable labels on taskbar items, the labels are shown with vertical sideways text, running from top to bottom instead of horizontal text next to the icon.

![image](https://github.com/user-attachments/assets/308f2a8b-6c49-4b37-86ff-4a6bcca9b21e)

Please ensure that the labels for taskbar items are rotated along with the icons, so that it looks more like this screenshot from Windows 10:
![Win10SideTaskbar](https://github.com/user-attachments/assets/91341f21-7ac2-49ea-939c-ce4f926eea42)

**Comment by m417z** [comment]
Done in version 1.2.

![image](https://github.com/user-attachments/assets/3389a418-6883-4e8e-95ad-7b9f0c515be1)
