### ISSUE TITLE
Middle click to close on the taskbar no longer working

### ISSUE THREAD

**Issue by JoeBarouneD** [ramensoftware/windhawk-mods#905]
Hello, the mod doesn't change anything and doesn't work.
Tried toggling on/off, rebooting.
The log doesn't capture anything.

On Windows 22631.4037 with last updates (last on date is KB5041585).

**Comment by JoeBarouneD** [comment]
Yes i use Startallback, but with 7+ Taskbar Tweaker, it worked like a charm.
Same for "Cycle taskbar buttons with mouse wheel".

**Comment by m417z** [comment]
If you're using StartAllBack older than version 3.8, it uses the old Win10 taskbar, so you can use 7+ Taskbar Tweaker. For the Middle click to close on the taskbar mod, there's also an option that can be enabled to make it work, "Customize the old taskbar on Windows 11".

StartAllBack 3.8 uses its own taskbar, so 7+ Taskbar Tweaker doesn't work with it, and most Windhawk mods don't work with it too.

**Comment by JoeBarouneD** [comment]
I know for the 3.8 version, i was in 3.7.x (with 7+TT) and upgraded to begin using Windhawk...
Thanks for your time !

**Comment by m417z** [comment]
@123SONIC321 Compatibility with ExplorerPatcher is not a priority, sorry. You can also try asking the ExplorerPatcher authors about it, perhaps there's an easy solution on their side.
