### ISSUE TITLE
Windows 11 Control Center Customization after W11 24H2 Update.

### ISSUE THREAD

**Issue by OsamaHJT** [ramensoftware/windhawk-mods#909]
I got the second update of the year for windows 11 and now the Quick Actions/Control Center runs on a different exe, previously it ran on ShellExperienceHost.exe along with the notification center, but after the update it now runs on ShellHost.exe, which means you can't customize the W11 control center with "notification center styler" mod anymore, I'm hoping to get an official mod for the new exe soon.

Sorry if this is the wrong place to post a mod request, but since this type of mods is made by the app author himself I thought it could be appropriate, please let me know if it's the right place for such a request or not.

**Comment by m417z** [comment]
Thanks, moved to https://github.com/ramensoftware/windhawk-mods.

Have you tried adding `ShellHost.exe` to the mod's inclusion list in the advanced options? Perhaps it will work, if no other major changes were made.

**Comment by OsamaHJT** [comment]
Thanks for moving the issue, yes I have done it already and it does work, but for some reason it keeps unloading after few minutes needing to unload and reload to apply again, seems like ShellHost.exe shutsdown after being idle. I also prefer to have an official mod because it's safer to share with others who are not so tech oriented

**Comment by m417z** [comment]
Done in Windows 11 Notification Center Styler v1.1.3.
