### ISSUE TITLE
Activity Indicators of applications are out of place and label overflow into system tray..

### ISSUE THREAD

**Issue by AritraNath** [ramensoftware/windhawk-mods#91]
The activity indicators specific to an application are out of place and display abruptly in the middle of the taskbar button.

Teams indicator here in the attached screenshot.

Also please note that the taskbar buttons overflow into the system tray area which make them inaccessible.

![Screenshot 2023-02-01 095313](https://user-images.githubusercontent.com/38553944/215946639-536d03f8-e3ce-48f1-81b6-ecb2e46a0d1d.png)

**Comment by m417z** [comment]
Fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version:
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11
