### ISSUE TITLE
taskbar-icon-size Broken After Update

### ISSUE THREAD

**Issue by dxnnv** [ramensoftware/windhawk-mods#920]
Taskbar height and icon size seems to be broken after the latest Windows update, appears to hang at `Entering LoadedMod::FindCloseSymbol`. Windhawk indicates the mod is still initializing infinitely. Debug logs can be found [here](https://pastebin.com/YLm3dQqd).
During this time, taskbar refuses to appear, windows key doesn't bring up start menu, etc.

Using OS Microsoft Windows 11 Home (x64) Build 22631.4112 (23H2)
Happy to provide any additional information if needed :)
@m417z

**Comment by m417z** [comment]
One of the users had a similar problem and it turned out to be because of Application Verifier. Any chance you have it enabled?

**Comment by dxnnv** [comment]
This did fix it, had no idea that was even installed. Thank you!
