### ISSUE TITLE
Disable Rounded Corners doesn't load

### ISSUE THREAD

**Issue by nazzy121** [ramensoftware/windhawk-mods#926]
![image](https://github.com/user-attachments/assets/27a2e735-81db-469f-acd4-724cc1052417)

![image](https://github.com/user-attachments/assets/73061580-3012-4315-85a1-7026d2ddfe89)

![image](https://github.com/user-attachments/assets/358ff837-6d0c-4d94-b8a6-86c4472676ab)

dwm.exe is in the process inclusion list
no log output when re-starting the mod
doesn't seem like Windhawk even recognizes it?   please help. 

This was after reinstalling fresh OS (W11 23h2)

**Comment by SandTechStuff** [comment]
You need to put DWM in the Windhawk inclusion list and not just the mod inclusion list I think. It looks like you went to the advanced settings of the mod and not Windhawk as a whole.

**Comment by nazzy121** [comment]
> You need to put DWM in the Windhawk inclusion list and not just the mod inclusion list I think. It looks like you went to the advanced settings of the mod and not Windhawk as a whole.

bingo that was it, thank you!    closing this.
