### ISSUE TITLE
[Taskbar Labels for Windows 11] Hide labels for a user-specified set of applications

### ISSUE THREAD

**Issue by mkacct** [ramensoftware/windhawk-mods#927]
@m417z

Not entirely sure how feasible this is, but the Taskbar Labels for Windows 11 mod could benefit from a setting to hide labels only for apps pinned to the taskbar. This would somewhat resemble the behavior of "pinned tabs" in browsers. For example, I always have a todo app open at the beginning of the taskbar, and could free up space for other item labels if it didn't have to show its name.

If it is not feasible to get whether the item is pinned, it could simply be an option to hide labels for a user-specified set of applications.

**Comment by mkacct** [comment]
@m417z I have just noticed that this seems to have been implemented (the "user-specified set of applications" solution, that is). However, I can not seem to use it with UWP apps (Microsoft To Do is the one I am specifically attempting to use).

**Comment by m417z** [comment]
Yeah. You can use `ApplicationFrameHost.exe` which hosts UWP apps, but it will affect all UWP apps. I'll look at adding an option to specify app IDs in the future, like it's possible to do in the "Disable grouping on the taskbar" mod.

**Comment by m417z** [comment]
Here's an implementation you can test:
https://github.com/m417z/my-windhawk-mods/blob/2e9bb6f9fac9244ec9b0a334f1f9b50966209363/mods/taskbar-labels.wh.cpp

If you'd like to try it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the test mod code, click "Compile Mod", then "Exit Editing Mode".

**Comment by mkacct** [comment]
@m417z works in my case!

**Comment by m417z** [comment]
Great, thanks for confirming, I'll include it in the next update.

**Comment by m417z** [comment]
> it could simply be an option to hide labels for a user-specified set of applications

Added in 1.3.2. If the original request is still relevant (Option to hide labels on pinned apps), please create a new issue.
