### ISSUE TITLE
Week number in 'Taskbar Clock Customization' is incorrect

### ISSUE THREAD

**Issue by heldheld** [ramensoftware/windhawk-mods#93]
Right now, %weeknum% gives me an output of 7, but it should be 5 at the moment.

Tbf I'm not completely sure if it's just incorrect or using a different standard. If the second, I'd like to have the option of changing the standard (to at least ISO-8601) and to set the day the week starts (only necessary if it somehow differs from whatever you inputted in the Windows settings).

**Comment by m417z** [comment]
We discussed it here: https://github.com/ramensoftware/windhawk-mods/discussions/47#discussioncomment-4699549

> The number is 1 for Sunday, 2 for Monday, ... 7 for Saturday. There's a [First day of week](https://stackoverflow.com/questions/39325212/how-get-start-day-of-week) setting in Windows, I'll look into using that to adjust the numbers to the user preference.

**Comment by heldheld** [comment]
Ohhh so it shows the number of the day IN the week, not the actual number of the week in the year. That is something completely different from what I expected.

Any chance you could add the other kind of week number as well? So, ranging from 1 to 52 depending on the date according to the ISO-8601 standard?

**Comment by m417z** [comment]
Yeah, I haven't thought of the other interpretation, perhaps %weeknum% should have been called %weekday_num%, and %weeknum% should translate to the week number as you suggest.

BTW do you think is it preferable to use ISO-8601 and not the week number according to the user's configuration of the first day of the week?

**Comment by heldheld** [comment]
> Yeah, I haven't thought of the other interpretation, perhaps %weeknum% should have been called %weekday_num%, and %weeknum% should translate to the week number as you suggest.

That sounds good, I think that will prevent confusion in the future for most people.


> BTW do you think is it preferable to use ISO-8601 and not the week number according to the user's configuration of the first day of the week?

I'm not sure what exactly is implied with the ISO-8601 standard tbh, I just know that I use that personally. If the only thing it means is that the week starts on Monday, then I definitely think it's best to use the user's configuration of the first day of the week.

**Comment by marcelser** [comment]
Had exactly the same confusion, would be great if you could change %weeknum% to %weekday_num% and add %weeknum% to week number in year and I also don't know ISO-8601 but it as @heldheld said, it probably makes sense to use users configuration for first day of week

**Comment by marcelser** [comment]
@m417z I know you're probably buried in other mods and other software too but any chance to solve this soon?

**Comment by m417z** [comment]
Done in Taskbar Clock Customization v1.0.7.

**Comment by m417z** [comment]
I also added ISO week number in Taskbar Clock Customization v1.0.8 as requested by one of the users.

**Comment by heldheld** [comment]
> I also added ISO week number in Taskbar Clock Customization v1.0.8 as requested by one of the users.

Awesome, it's perfect! Thanks a lot :)
