### ISSUE TITLE
Taskbar Volume Control - changed behavior

### ISSUE THREAD

**Issue by ttodua** [ramensoftware/windhawk-mods#934]
@m417z
question about the mod - before I reinstalled windows, when I did mousewheel-scroll, it opened volume control like this:
![image](https://github.com/user-attachments/assets/5c44ccb6-e8f8-418d-98f0-b8adca0b6430)

however, now it just shows volume-progressbar hover in the center of the screen:
![image](https://github.com/user-attachments/assets/d4b3e1e3-9167-428e-a8cd-be1b870aef45)

how to restore the functionality to use the first approach.

**Comment by m417z** [comment]
The first screenshot is the Win10 volume control UI, you can select it in the mod settings.

**Comment by ttodua** [comment]
i used explorerpatcher, probably that's reason. thanks!

**Comment by ttodua** [comment]
ah found it, thanks
