### ISSUE TITLE
Taskbar Volume Control - Doesn't work if certain programs are in focus

### ISSUE THREAD

**Issue by ufuksarp** [ramensoftware/windhawk-mods#94]
After installing the mod I immediately tried and it didn't work. Because Windhawk was in focus. I tried bunch of programs. One other program I caught was HWiNFO, version 7.36 in particular. It didn't matter if the said programs are in fullscreen mode or not.

**Comment by m417z** [comment]
I believe that it is now fixed in version 1.1. Please try it and let me know if it's still an issue.
