### ISSUE TITLE
Windows 11 Start Menu Styler - Cannot work after system reboot

### ISSUE THREAD

**Issue by HMwancheng** [ramensoftware/windhawk-mods#944]
![image](https://github.com/user-attachments/assets/41748dbf-ad2a-4c9d-a8c1-f251b747043b)

But it worked after turn off and turn on the mod again

![image](https://github.com/user-attachments/assets/2e4d76e3-a30a-49f6-b64e-d0730bb15c3b)

**Comment by m417z** [comment]
I haven't encountered this issue. Do you have any other customization tools that might conflict with the mod?
Also, try to open Task Manager, go to Details, and terminate the StartMenuExperienceHost.exe process. It should relaunch automatically once you open the start menu. Does the mod work in this case?

**Comment by HMwancheng** [comment]
it's working normal now...
![image](https://github.com/user-attachments/assets/017da817-113b-49fa-8558-7d65df30b53b)
