### ISSUE TITLE
With taskbar-icon-size 1.2.11, I Still Get Taskbar Pushed Half Offscreen on Touchscreen

### ISSUE THREAD

**Issue by dhb33** [ramensoftware/windhawk-mods#947]
@m417z... it happens just when the Win11 (KB5042099) comes back from hibernation on my Surface Book. Compare with Win10, coming back from hibernation, I also loose the Windows Sticky Key icon on the taskbar.

To get the full taskbar (except Sticky Key), I made a kill-start-explorer,bat
For the Sticky Key, it's easy to get it back. Still, I should report that lost from Win10 to Microsoft. 

Best Regards,
Denis

**Comment by m417z** [comment]
Are you using tablet mode? It's not supported, see https://github.com/ramensoftware/windhawk-mods/issues/184.
Also, could it be the same issue as https://github.com/ramensoftware/windhawk-mods/issues/529?

**Comment by MuscularPuky** [comment]
you'd schedule to disable then enable (my interval is 2s) "TabletPostureTaskbar" reg valueevery security event trigger `ID 4624` `LogonType 7`
or `VerticalAlignment = Bottom` to taskbar frame'd be helpful. either'll work as I know but I needed the former for taskbar label

**Comment by dhb33** [comment]
> Are you using tablet mode? It's not supported, see #184. Also, could it be the same issue as #529?

Yes, in fact, "taskbar-icon-size" v1.2.11 fixed issue #529  for reboot but not for return from hibernation (long sleep) in my case.
