### ISSUE TITLE
Taskbar height and icon size mod does not use real 16px icons, instead shrinks bigger ones.

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk-mods#953]
@m417z

Win11 taskbar:

![изображение](https://github.com/user-attachments/assets/3b10977d-cef9-4e71-919d-e8ab0bd22fa7)

Win10 taskbar:

![изображение](https://github.com/user-attachments/assets/b5c81c82-0bf2-4240-9ad5-06e8fb64275f)

**Comment by m417z** [comment]
It was discussed on Discord recently, and I pushed a fix to test:
https://github.com/m417z/my-windhawk-mods/blob/8eab90f960ef96f7c8ba6134d8cb86dc0a7ff61a/mods/taskbar-icon-size.wh.cpp

**Comment by Anixx** [comment]
Yes, this fixes the issue. Do you plan the update?

**Comment by m417z** [comment]
Done in version 1.2.13.
