### ISSUE TITLE
[Windows 7 Alt+Tab Loader] Prequisites instructions clarification

### ISSUE THREAD

**Issue by mayureshs** [ramensoftware/windhawk-mods#955]
[Windows 7 Alt+Tab Loader] Hello @aubymori, Thank you for creating this mod. But I am having difficulty in following the pre-requisites for making this mod work. 

Can you please give more details on how can I get the Alt + Tab Loader to work in Windows 11. 

1. From where can I get the  AltTab.dll from Windows 7 (x64)
2. AltTab class - I do not have any experience with Windows Style Builder. Can you please send over the needed files to be copied over ?

**Comment by mayureshs** [comment]
This mod does not work on Win 11 v24H2.

**Comment by aubymori** [comment]
> [Windows 7 Alt+Tab Loader] Hello @aubymori, Thank you for creating this mod. But I am having difficulty in following the pre-requisites for making this mod work.
> 
> Can you please give more details on how can I get the Alt + Tab Loader to work in Windows 11.
> 
>     1. From where can I get the  AltTab.dll from Windows 7 (x64)
> 
>     2. AltTab class - I do not have any experience with Windows Style Builder. Can you please send over the needed files to be copied over ?

1. Windows 7 ISO. Open with 7-Zip, go to sources\install.wim, then it'll be at Windows\System32\AltTab.dll.
2. Sorry, I don't have experience with making themes myself. It's best you ask someone else about this.

**Comment by mayureshs** [comment]
> > [Windows 7 Alt+Tab Loader] Hello @aubymori, Thank you for creating this mod. But I am having difficulty in following the pre-requisites for making this mod work.
> > Can you please give more details on how can I get the Alt + Tab Loader to work in Windows 11.
> > ```
> > 1. From where can I get the  AltTab.dll from Windows 7 (x64)
> > 
> > 2. AltTab class - I do not have any experience with Windows Style Builder. Can you please send over the needed files to be copied over ?
> > ```
> 
> 1. Windows 7 ISO. Open with 7-Zip, go to sources\install.wim, then it'll be at Windows\System32\AltTab.dll.
> 2. Sorry, I don't have experience with making themes myself. It's best you ask someone else about this.

I tried it for Win 11 v24H2 and it does not work. No icons show up upon Alt Tab, would it be possible to create an updated version of this mod?

**Comment by lucaspestana** [comment]
> Can you please give more details on how can I get the Alt + Tab Loader to work in Windows 11.
> 1. From where can I get the  AltTab.dll from Windows 7 (x64)

Hello there! I am a Windows 10 user of Windhawk. I have no experience with styles/themes, I'll have to look into that later.

As for the DLL file itself, "AltTab.dll", I seem to have figured my way through. The DLL version from Windows 7 (x64, aka 64-bits) that we require is "6.1.7600.16385".
Also, I feel we might also need to add "AltTab.dll.mui" (MUI means Multilingual User Interface -- that means it's responsible for displaying the menus and buttons et cetera either in English and/or in your OS's language); I guess you'll need to place it in C:\Windows\System32\en-US and C:\Windows\System32\<yourlanguage-COUNTRY> (for instance, in my case, it's C:\Windows\System32\pt-BR -- Brazilian Portuguese).

Higher and lower version numbers are those from Windows 8 (or higher) or Windows Vista (or lower), respectively -- and thus probably not what we want.
https://www.exefiles.com/en/dll/alttab-dll/
https://www.exefiles.com/en/mui/alttab-dll-mui/
https://www.pconlife.com/searchfile/windowsosfile/ (search for the files you want)

I guess the best place to look for a Windows 7 ISO is on The Internet Archive; try these searches:
https://archive.org/search?query=Windows+7+x64+ISO
https://archive.org/search?query=Windows+7+ISO
When browsing through the files, make sure that you're selecting the files from a x64 (64-bit) version Windows 7, not a x86 (32-bit) version.
I was able to find a collection of [Brazilian Portuguese (my language) ISOs of Windows 7](https://archive.org/details/Windows7_x86-x64_ptBR_Pack_MSDN) through a Google search. Then, go to the sidebar, and under "Download Options", click "Show All" -- this will allow you to preview all the files included without having to download it all; choose the ISO you want and click "View Contents". From there, just look for the "install.wim" file, it's about 1 GB in size.

Edit: After struggling a lot, and failing miserably to unpack the "install.wim" files from The Internet Archive, I ended up trying to use the .DLL from ExeFiles and the .DLL.MUI from PCOnLife (which didn't want to unzip either). Both did not work without the MSSTYLES part though -- pressing Alt+Tab does absolutely nothing (thankfully Win+Tab still works fine).

And that's all for now, folks. I failed miserably, again, at the MSSTYLES step, lol.
I really wish the mod author themself provided clearer instructions, and even better, that sample files were provided for download, as well as the means and/or instructions to modify them when applicable.

**Comment by ThisWasNotTaken** [comment]
i got the file it now on internet archive https://archive.org/details/tree.zip

**Comment by ThisWasNotTaken** [comment]
> [Windows 7 Alt+Tab Loader] Hello [@aubymori](https://github.com/aubymori), Thank you for creating this mod. But I am having difficulty in following the pre-requisites for making this mod work.
> 
> Can you please give more details on how can I get the Alt + Tab Loader to work in Windows 11.
> 
>     1. From where can I get the  AltTab.dll from Windows 7 (x64)
> 
>     2. AltTab class - I do not have any experience with Windows Style Builder. Can you please send over the needed files to be copied over ?

found it https://archive.org/details/tree.zip
