### ISSUE TITLE
The "Disable rounded corners in Windows 11" mod is irreversible

### ISSUE THREAD

**Issue by oep42** [ramensoftware/windhawk-mods#962]
Mod Dev: @m417z
Mod Name: "Disable rounded corners in Windows 11"
Issue: This mod is irreversible.
System: Windows 11, Version 22H2.

**To reproduce this problem:**
- Install Windhawk. 
- Add in Windhawk to the "Process inclusion list: "dllhost.exe"; "dwm.exe"; "winlogon.exe". 
- Install and enable these mods in Windhawk: "Classic Theme Enable with extended compatibility"; "Classic Task Dialog Fix"; "Classic Taskbar 3D buttons Lite"; "Classic Taskbar background fix"; "Classic UWP Fix"; "Clientedge Everywhere"; "Disable rounded corners in Windows 11". 
- Restart the computer. 
- Now the rounded corners are disabled. 
- Disable in Windhawk the "Disable rounded corners in Windows 11" mod. 
- Remove in Windhawk the "Disable rounded corners in Windows 11" mod by clicking the "Remove" button. 
- Restart the computer. 
- Now the rounded corners are still disabled. 
- (I guess that some of the other other mods are not needed to reproduce this problem, but this is how I found out about it.)

**Suggestion**: Add the functionality to undo the effect of this mod by clicking on the "Remove" button for this mod. If this is not possible, add an option to this mod to undo the effect this mod. If this is not possible, create a new mod to undo the effect of this mod.

**Comment by SandTechStuff** [comment]
I've used this mod before and haven't had this issue. Are you testing in a VM or a computer without drivers? If you do not have a display driver rounded corners are automatically disabled by Windows.

**Comment by m417z** [comment]
The Disable rounded corners in Windows 11 mod does no permanent changes to the system. [The code](https://github.com/ramensoftware/windhawk-mods/blob/1c369113ba4582b572663e7bde2999bd70c7a1f1/mods/disable-rounded-corners.wh.cpp) is very simple, it hooks a single function, which only lasts as long as the dwm.exe process is running. After disabling the mod and restarting the process or the computer, it's impossible for the mod to still have any effect. So it's likely that you're not seeing the rounded corners for another reason, perhaps related to display drivers as @SandTechStuff suggested.

**Comment by oep42** [comment]
I looked into this again. It turns out that the "Classic Theme Enable with extended compatibility" mod by itself disables the rounded corners in Windows 11, while this is not documented in the "Details" page of this mod. So if you only install and enable the two mods "Classic Theme Enable with extended compatibility" and "Disable rounded corners in Windows 11", the rounded corners will be disabled in Windows 11. If you, after that, remove the "Disable rounded corners in Windows 11" mod, rounded corners will still be disabled in Windows 11 because of the enabled "Classic Theme Enable with extended compatibility" mod. Sorry for mistakenly raising this issue.

**Comment by m417z** [comment]
> If you, after that, remove the "Disable rounded corners in Windows 11" mod, rounded corners will still be disabled in Windows 11 because of the enabled "Classic Theme Enable with extended compatibility" mod.

Does it persist after reboot?

The following two series of steps should result in the same:

* Install "Classic Theme Enable with extended compatibility"
* Install "Disable rounded corners in Windows 11"
* Remove "Disable rounded corners in Windows 11"
* Reboot

And:

* Install "Classic Theme Enable with extended compatibility"
* Reboot

I'm not sure where's the "mod is irreversible" part. If rounded corners are gone after doing the first steps, I'd assume they'll be gone after doing the second steps too, in which case why "Classic Theme Enable with extended compatibility" suggests to install "Disable rounded corners in Windows 11" if it does it by itself? If, on the other hand, rounded corners are back after reboot, then there's nothing irreversible here.

**Comment by oep42** [comment]
I tried to explain that I was wrong to say that the "Disable rounded corners in Windows 11" mod was irreversible. Perhaps I wasn't clear enough.

I found out that another mod was also disabling rounded corners in Windows 11, while I was unaware that this was happening, and while this was not mentioned in the documentation of this other mod.

So two mods were, at the same time, disabling the rounded corners in Windows 11. After removing one of these mods, the other mod continued to disable rounded corners in Windows 11. (This led me to mistakenly believe that the removed mod was irreversible.) Only after removing both these mods, the Windows 11 corners were rounded again. 

So none of these two mods is irreversible.

Indeed, both sets of steps have the same result: Windows 11's rounded corners are disabled by the "Classic Theme Enable with extended compatibility" mod. After removing this mod and rebooting (while the "Disable rounded corners in Windows 11" is not installed), the rounded corners are no longer disabled in Windows 11.

**Comment by m417z** [comment]
Gotcha. In this case, perhaps it's better to mention it in the "Classic Theme Enable with extended compatibility" mod's description, and to remove the suggestion for installing "Disable rounded corners in Windows 11" alongside it. @levitation WDYT?

**Comment by oep42** [comment]
I agree. I am now in the process of trying/testing the "Classic Theme Enable with extended compatibility" mod. When done with this, I will mention this in my feedback to @levitation.

**Comment by levitation** [comment]
The classic theme mod only triggers Classic Theme. If the rounded corners go away with Classic Theme mod then this is because that is how Classic Theme is implemented by Windows itself. Besides enabling Classic Theme, the mod itself does not actively do additional operations that would directly change the corners.

Why I added recommendation for adding the "disable rounded corners" mod is, because some windows still had rounded corners in Win 11 without the additional mod.

So I imagine if somebody finds out how some programs natively managed to have rounded corners with Classic Theme, then they could write a mod that maybe enables rounded corners for all windows under Classic Theme.

Hopefully these thoughts make things more clear.
