### ISSUE TITLE
[Vertical Taskbar for Windows 11] Mods like "Taskbar Volume Control" and "Click on empty taskbar space" don't work

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#970]
@m417z 
Mods like "Taskbar Volume Control" and "Click on empty taskbar space" don't work when the vertical taskbar mod is enabled.

Also, thanks for the vertical taskbar update :)

**Comment by JullianSL** [comment]
Before reading this issue I didn't know this happened, but same here, also thank you for the update.

**Comment by m417z** [comment]
Fixed in version 1.2.1.
