### ISSUE TITLE
[Vertical Taskbar for Windows 11] The hidden icons go behind the screen

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#971]
The hidden icons go behind the screen when the taskbar is placed on the right.
@m417z 

![image](https://github.com/user-attachments/assets/94a89f79-0662-45dd-af02-dc33dff3ff5a)

**Comment by JullianSL** [comment]
I've also experienced the same issue.

**Comment by m417z** [comment]
Fixed in version 1.2.1.
