### ISSUE TITLE
[Vertical Taskbar for Windows 11] Widget Icon not rotating

### ISSUE THREAD

**Issue by JullianSL** [ramensoftware/windhawk-mods#972]
Hi @m417z, thanks for implementing right vertical alignment, and rotating the co-pilot button!
I noticed in the changelog it said the widget button is supposed to rotate as well, but I haven't noticed this behaviour.

This is what it looks like for me currently, and I'm sure this isn't what its meant to look like.

![Wx4vtXqXzu](https://github.com/user-attachments/assets/c0210c14-60c9-4dd5-8365-c763ae0c7894)

I believe the widget button with the weather is meant to rotate, unless my understanding is incorrect, anyway thanks again for your the feature implementations and your hard work!

**Comment by JullianSL** [comment]
Huh, I just tried again and it works properly now, I disabled, re-enabled it earlier and it didn't work, I even restarted my computer and it ended up like above, but now its rotated. I'm going to close this issue since the problem seems to have resolved itself.

**Comment by m417z** [comment]
The mod only rotates the icons, not the text. In newer Windows versions, there's no text at all, so I figured it's not worth investing the time on it.

![image](https://github.com/user-attachments/assets/1047df98-421c-4767-b6e5-5a9261191f32)

**Comment by JullianSL** [comment]
> The mod only rotates the icons, not the text. In newer Windows versions, there's no text at all, so I figured it's not worth investing the time on it.
> 
> ![image](https://private-user-images.githubusercontent.com/4129781/369408440-1047df98-421c-4767-b6e5-5a9261191f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDY1NDksIm5iZiI6MTcyNjg0NjI0OSwicGF0aCI6Ii80MTI5NzgxLzM2OTQwODQ0MC0xMDQ3ZGY5OC00MjFjLTQ3NjctYjZlNS01YTkyNjExOTFmMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTUzMDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUzZTNhZmY1ZjgxNGM4ZTMwZWVkYjljOWMwZGRiMjMzMzJhNTdlYzQ5NjIyODhhNWEzNTEwMmVlMmU5OTBiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J2SGasWrJOXFRgyGdiXvOuRm4k624YVOjFuPNEnsT34)

Ahhh, okay, well I had an instance on 23H2 where it showed up like the above, but it doesn't seem to turn to icon only all the time, but if its going to be icon only in 24H2 onward then I agree, it won't be worth investing the time.

Thanks for implementing all this though.
