### ISSUE TITLE
[taskbar-start-button-position] Start menu alignment

### ISSUE THREAD

**Issue by DwayneHawkins** [ramensoftware/windhawk-mods#979]
@m417z 

Hello, I saw this mod was added quite recently, neat!
I can now use the windows setting to align my taskbar buttons to the center, and still have left aligned start button thanks to this mod.

Two questions, sometimes, the button is not quite 100% to the left; there seems to be a gap of a pixel (or two).
Also, I was wondering if aligning the actual menu to the left would be possible in the future.

**Comment by m417z** [comment]
Just updated to version 1.1.

> Two questions, sometimes, the button is not quite 100% to the left; there seems to be a gap of a pixel (or two).

I increased the delay for the position adjustment, let me know if you still see the issue. If you do, try to come up with a way to reproduce it.

> Also, I was wondering if aligning the actual menu to the left would be possible in the future.

Done in version 1.1.
