### ISSUE TITLE
[Vertical Taskbar for Windows 11] Intermittently taskbar starts with all icons collapsed into a ellipsis / Misplaced and cut off pop-over

### ISSUE THREAD

**Issue by Venthe** [ramensoftware/windhawk-mods#981]
Intermittently taskbar starts with all icons collapsed into a ellipsis / Misplaced and cut off pop-over

Possible regression as this happens on L and R; This one might again be related to my multi display setup;

> I have three displays, from left to right; including their detected number:
(1)4k@150%, (2)4k@150%(main) [ and disconnected for now  (3)HD@100% vertical]

On (1) the taskbar opens correctly, on (2) the taskbar sometimes opens with no app icons except for the "see all apps" ellipsis; which is cut off from the top.
![image](https://github.com/user-attachments/assets/79d645b6-b886-4d1e-8a86-7b96204be5f9)
which is cut off from the top. Once it opened near the start icon; this time at the opposite end of the screen.
![image](https://github.com/user-attachments/assets/8a794424-e184-4ae7-9048-9a2167122610)
Though interestingly, when I swap to the left, the ellipsis stays
![image](https://github.com/user-attachments/assets/eda6a1b1-7101-4805-a99d-4e159facbdbe)

[log ellipsis.txt](https://github.com/user-attachments/files/17077191/log.ellipsis.txt)

e: I can trigger this on the left, by enabling/disabling the mod a few times

**Comment by m417z** [comment]
I saw this as well. Here's an attempt at fixing it, let me know if it works for you:
https://github.com/m417z/my-windhawk-mods/blob/346e157eae5ef61da877a33659c08a8bc30b01ed/mods/taskbar-vertical.wh.cpp

**Comment by m417z** [comment]
Fixed in version 1.2.2.
