### ISSUE TITLE
[Vertical Taskbar for Windows 11] Modals from other applications do not respect the screen boundary when taskbar is on the right

### ISSUE THREAD

**Issue by Venthe** [ramensoftware/windhawk-mods#982]
Sorry, I hope this is the last one related to multi display :(

> I have three displays, from left to right; including their detected number:
(1)4k@150%, (2)4k@150%(main), [disconnected (3)HD@100% vertical]

When taskbar is on the right; the popups from e.g. `photoshop` will open to the "left" (From 1 into the 2) without respecting the screen boundary.
![image](https://github.com/user-attachments/assets/6ee77bbb-ab21-403f-b260-0250a86d7a02)

As I've uploaded the picture; I notice that the popup can be seen between the maximized photoshop and the taskbar from the "left" screen as well.

Logs, as usual - nothing interesting here
```text
17:26:15.762 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:15.762 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:15.763 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:15.763 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:20.886 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:20.886 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:20.886 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
17:26:20.886 11604 explorer.exe  [WH] [local@taskbar-vertical-test] [1588:TaskListButton_UpdateVisualStates_Hook]: >
```

**Comment by m417z** [comment]
Look more like Photoshop not supporting this kind of setup to me. How does it behave on Win10 with the native taskbar being located between the two monitors?

Generally, IMO it's out of scope for this mod to handle such program-specific behavior.

**Comment by Venthe** [comment]
Sorry, this one is on me; I've filed it as a bug without checking if it happens without the vertical taskbar. I'm pinning this one on a long night and filing a bug report one after the other.

Cheers.
