### ISSUE TITLE
taskbar height and icon size broken in tablet mode

### ISSUE THREAD

**Issue by aspizu** [ramensoftware/windhawk-mods#985]
In tablet mode (2 in 1 laptop is folded), the taskbar becomes larger and bigger. With taskbar height modified, the taskbar disappears making it unusable.

![](https://media.discordapp.net/attachments/1216842627379363924/1286771258826035220/image.png?ex=66ef1e9f&is=66edcd1f&hm=90158165b9327e575819609723ed439fbad23a6d26682eb77b679daa309b6aad&=&format=webp&quality=lossless&width=1100&height=74)

**Comment by m417z** [comment]
Tablet mode isn't supported, it's a known limitation, see:
https://github.com/ramensoftware/windhawk-mods/issues/184
