### ISSUE TITLE
[Vertical Taskbar for Windows 11] Right Align Task Tray Button is reversed

### ISSUE THREAD

**Issue by julliansl** [ramensoftware/windhawk-mods#986]
@m417z The task tray's expand and collapse button is reversed, for example...

Expand (as viewed from Right alignment):
![kOumTaRycN](https://github.com/user-attachments/assets/3c19416d-7346-4dc8-9935-4e6960d63543)

Collapse (as viewed from Right alignment):
![ldAP5XerW0](https://github.com/user-attachments/assets/1368c60b-99ed-494d-951f-3f0d43e441d0)

These should be reversed so that the expand points outward, and the collapse points inward to the taskbar.

**Comment by m417z** [comment]
Fixed in version 1.2.3.
