### ISSUE TITLE
[Vertical Taskbar for Windows 11] Taskbar App Overflow shows on the left side when right aligned

### ISSUE THREAD

**Issue by julliansl** [ramensoftware/windhawk-mods#987]
@m417z The taskbar overflow opens up on the left side of the monitor when its right aligned

![zr1leSMCFC](https://github.com/user-attachments/assets/d056863c-6dc6-45bd-a934-2988ada3838d)

**Comment by m417z** [comment]
Fixed in version 1.2.3.
