### ISSUE TITLE
[Vertical Taskbar for Windows 11] Attaching new display causes the old display to not show the taskbar

### ISSUE THREAD

**Issue by Venthe** [ramensoftware/windhawk-mods#998]
The setup is already well known at this point :)
> three displays, from left to right; including their detected number:
(1)4k@150%, (2)4k@150%(main),(3)HD@100% vertical

Repro:
1. Start with all displays attached (log start)
2. Power off one screen (in my case, it was (2) i.e. the main one)
3. Power on the screen
    1. The taskbar draw on (1) disappears; bbox stays in the right place
    2. ![image](https://github.com/user-attachments/assets/d89341e1-ac7b-4701-b010-afa2adb48a8c)

Disabling and re-enabling the mod ususally solves the issue

[Display reattach.windhawk.log](https://github.com/user-attachments/files/17146722/Display.reattach.windhawk.log)

**Comment by Venthe** [comment]
One note - this does not happen all the time, but restarting display seems like a quite reliable way to reproduce

**Comment by m417z** [comment]
I believe it's fixed in version 1.2.3. Please try it and let me know if not, in which case I'll reopen the issue.

**Comment by Venthe** [comment]
It seems to be working, at lest in terms of the taskbar coming back.
